전남대 BE_박민규 6주차 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #107
Opened 2024-07-31 06:37 UTC by ps9319

https://illustrious-date-5eb.notion.site/c1f834ae81e74e2fbda76b138cdef1bf?pvs=4
위의 api 명세서를 참고해서 uri와 로직 몇 가지를 수정했습니다!

2024-08-01 00:39 UTC, dc-choi requested changes
안녕하세요 민규님!

코드에 대한 코멘트는 하단에 남겼습니다! 확인 부탁드려요!

그리고 민규님께 몇가지 질문을 드리려고 합니다! 이것도 같이 확인 부탁드려요!

1. 노션으로 팀끼리 작업하신게 맞으신가요? 맞다면 매우 잘하신거 같습니다!
2. 기존에 작업하신 부분에서 서로 토론을 하게 되면서 어떤 부분이 달라지셨는지 궁금합니다!

2024-08-01 00:39 UTC, dc-choi commented on src/main/java/gift/controller/OptionController.java
> +    @DeleteMapping("/api/products/{productId}/options/{optionId}")
이 부분에서 `/api/api`로 두번 중복되는거 같습니다!

2024-08-01 00:39 UTC, dc-choi commented on src/main/java/gift/controller/ProductController.java
> +    @GetMapping("/normal")
이 엔드포인트는 어떤 이유로 있는걸까요?

노션의 명세에는 없던 부분인거 같습니다!

2024-08-01 00:39 UTC, dc-choi commented on src/main/java/gift/controller/WishController.java
> +    @GetMapping("/normal")
마찬가지로 노션에는 없는 명세인거같은데 어떤 이유에서 사용하는 API인지 궁금합니다!

2024-08-01 00:39 UTC, dc-choi commented on src/main/java/gift/controller/AuthController.java
>      @GetMapping("/api/oauth/redirect")
이 부분도 노션의 명세와 다른거 같습니다! 확인 부탁드려요!

2024-08-01 01:03 UTC, ps9319 commented on src/main/java/gift/controller/OptionController.java
> +    @DeleteMapping("/api/products/{productId}/options/{optionId}")
앗 맞습니다!... 수정하겠습니다!!

2024-08-01 01:11 UTC, ps9319 commented on src/main/java/gift/controller/ProductController.java
> +    @GetMapping("/normal")
명세서에는 없지만 이미 있는 기능을 없애고 싶지 않아서 uri만 바꾸었습니다!...
명세서에는 상품 조회 페이지네이션만 있습니다.

2024-08-01 01:12 UTC, ps9319 commented on src/main/java/gift/controller/WishController.java
> +    @GetMapping("/normal")
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-point/pull/107#discussion_r1699262792
이것도 같은 이유로 없애지 않았습니다.

2024-08-01 01:32 UTC, ps9319 commented on src/main/java/gift/controller/AuthController.java
>      @GetMapping("/api/oauth/redirect")
아 알고보니 프론트에서는 소셜 로그인 기능을 구현하지 않았더라구요.
그래서 공통 명세서에 작성하지 않았고, https://github.com/kakao-tech-campus-2nd-step2/spring-gift-point/pull/107#discussion_r1699262792 이것도 마찬가지로 없애고 싶지 않아서 남겨두었습니다

2024-08-01 03:16 UTC, ps9319 commented
> 1. 노션으로 팀끼리 작업하신게 맞으신가요? 맞다면 매우 잘하신거 같습니다!

네 맞습니다! 월요일 저녁 늦게까지 만나서 명세서 통일시켜보았습니다

> 2. 기존에 작업하신 부분에서 서로 토론을 하게 되면서 어떤 부분이 달라지셨는지 궁금합니다!

저는 기존에 조회할 때 제외하고는 모두 해당 엔티티의 아이디값만 보내주었는데, 다른 분들은 해당 엔티티의 정보를 전부 반환하더라구요. 그래서 저도 그렇게 변경하였습니다. 또 여러 연관관계가 엮여 있는 엔티티의 response dto 코드를 짤 때 그냥 필드값으로 다른 엔티티의 값을 넣어줬었는데, 
(ex. wish에 private Long productId, private String productName 등) 다른 엔티티의 response dto를 넣어주는 방법이 좋아보여서 적용해보았습니다.

2024-08-02 02:01 UTC, dc-choi approved these changes
네 민규님 확인하였습니다~

다음 과제로 넘어가시면 될 거 같습니다!

2024-08-02 02:01 UTC, merged