경북대 BE_김건 6주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #137
Opened 2024-07-31 16:01 UTC by gunGeongun

백엔드,프론트엔드 팀원들과 토의하여 API 명세를 통일하였고 , URI,에러처리 코드,메시지 등을 리팩터링하였습니다!

2024-08-04 12:10 UTC, MangKyu requested changes
안녕하세요 건님! 먼저 리뷰가 조금 늦어서 죄송합니다!
이번 미션은 스펙 협의를 팀원들과 하는 부분이 상당히 중요한데요, API 스펙에 대해 협의하면서 어떠한 변경들이 생겼고, 어떠한 부분들을 새롭게 느끼셨는지 궁금하네요! 개발자라는 직군이 코딩만 하는 사람들이 아니라, 비즈니스 문제를 개발로 해결하는 사람들이다보니까요! 이를 위해 다른 사람들과 협업하는 자세와 이해가 상당히 중요한 것 같네요ㅎㅎ
추가로 배포스크립트는 따로 Git으로 관리하지 않으시려는 걸까요~? (작업 하셨다고 적어주셨는데 보이지 않아서 질문드려요!)

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/config/AuthInterceptor.java
> +        if ("OPTIONS".equalsIgnoreCase(request.getMethod())) { // preFlight 해결
주석 달아주신 부분까지 좋은 것 같습니다! 💯  요렇게 변경되면 더욱 좋을 것 같아요~
```suggestion
        if(HttpMethod.valueOf(request.getMethod()).equals(HttpMethod.OPTIONS))
```

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/controller/OAuth/KakaoAuthSpecification.java
> +    ResponseEntity<Map<String, String>> getAccessToken(@Parameter(description = "카카오 인증 코드") @RequestParam String code,@RequestParam("redirect-url") String redirectUrl);
```suggestion
    ResponseEntity<Map<String, String>> getAccessToken(@Parameter(description = "카카오 인증 코드") @RequestParam String code, @RequestParam("redirect-url") String redirectUrl);
```

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/controller/admin/AdminController.java
> +    @PatchMapping("/members/{memberId}/point")
PATCH를 활용한 부분 💯

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/controller/admin/AdminPageController.java
> +@Controller
어드민 페이지 랜딩 부분이 여기 몰아지게 되었군요ㅎㅎ

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/controller/order/OrderController.java
> +            orderService.sendMessage(orderRequest, user, orderRequest.productId());
이 부분도 이제 한번 얘기해보면 좋을 것 같은데요, orderService는 주문에 관한 클래스인데요! sendMessage는 메시지 발송에 대한 것이라서, orderService 안에 있는 것이 바람직한가도 고민해보면 좋을 것 같아요!
즉, message 발송을 처리하는 별도의 messageService가 필요하지는 않을까 부분을 고민해보시면 좋을 것 같습니다!

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/controller/product/ProductController.java
> +    public ResponseEntity<PagingResponse<ProductResponse.Info>> getAllGiftByCategoryId(@RequestParam("category-id") Long categoryId,
category-id 형태로 대시를 구분자로 넣은 것 좋네요!

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/dto/order/OrderRequest.java
>              @NotNull
문자열의 경우에는 NotBlank를 보통 사용하는 것이 좋습니다!
```suggestion
            @NotBlank
```

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/dto/point/MemberPointRequest.java
> +            @NotNull
int 원시 타입에는 적용이 안되므로, Integer로 사용하던지 해야 할 것 같네요!

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(ProductNotFoundException.class)
예외 클래스를 지나치게 세분화하여 오히려 관리가 어려워진 것 같은데요! 이렇게까지 세분화를 하지는 않아도 되지 않을까 싶네요ㅎㅎ 만약 스펙 협의 부분이라면, 추상화를 해서 공통적으로 재활용하는 방법을 고민해봐야 할 것 같네요!

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/model/product/Product.java
> +public class Product {
네이밍 변경하시느라 고생 많으셨습니다ㅎㅎ
다만, API 명세만 통일하면 내부 구현은 통일하지 않아도 될 것 같은데요! 건님께서도 이렇게 바꾸는 것이 좋은 것 같아서 변경하신걸까요~?

2024-08-04 12:10 UTC, MangKyu commented on src/main/java/gift/model/user/User.java
> +    public void isAdmin(){
도메인을 표현하는 메서드 구현 👍

2024-08-05 02:11 UTC, gunGeongun commented on src/main/java/gift/controller/admin/AdminPageController.java
> +@Controller
넵 어드민페이지 관련된 메서드들은 AdmingPageController에 넣어줬습니다.

2024-08-05 02:20 UTC, gunGeongun commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(ProductNotFoundException.class)
저도 커스텀 exception이 너무 많아지는 것 같다고 느꼈었는데, 추상화를 적용해볼수도 있을 것 같습니다!

2024-08-05 02:21 UTC, gunGeongun commented on src/main/java/gift/model/product/Product.java
> +public class Product {
gift -> product 로 바꾼 것은 product라는 네이밍이 더 적절해보여서 바꾸는김에 전부 바꿔주었습니다.

2024-08-05 02:29 UTC, gunGeongun commented
test

2024-08-05 02:34 UTC, gunGeongun commented on src/main/java/gift/controller/order/OrderController.java
> +            orderService.sendMessage(orderRequest, user, orderRequest.productId());
처음에는 주문하기라는 기능에만 쓰는 느낌으로 orderService에 넣어줬었는데, 이젠 확장성을 고려해서 나중에 다른 service에서도 쓸 수 있게 따로 service를 만들어주는게 좋을 것 같습니다.

2024-08-05 03:11 UTC, MangKyu commented on src/main/java/gift/controller/order/OrderController.java
> +            orderService.sendMessage(orderRequest, user, orderRequest.productId());
넵넵! 당장 반영하지는 않아도 괜찮고, 시스템이 커지면서 반복적인 리팩토링의 필요성을 얘기드리고 싶었습니다!
이후에 메시지 발송이 확장된다면, 그때 별도의 메시지 발송 서비스로 분리하는 방식으로 디벨롭하면 괜찮을 것 같아요!

2024-08-05 03:28 UTC, gunGeongun commented
++deploy.sh 배포 스크립트를 원래 ssh에서만 사용하고있었는데 파일에 추가하였습니다! 
처음으로 프론트와 협업을 진행해보면서 API 명세를 협의하여 작성해보고 기능 추가에 대해 토의해보는 경험을 해볼 수 있었습니다.소통이 중요하다는 것을 그냥 이론적으로만 알고있었다면 이번 협업을 하며 소통의 중요성을 한번 더 깨달을 수 있었습니다.어느 부분은 어떻게 하면 좋을 것 같다, 이 부분은 이렇게해서 문제가 될 수 있을 것 같다라는 등의 개개인이 생각하는 것들을 자유롭게 이야기하며 다같이 어떠한 문제에 대해 생각해보고 결론을 도출해내는 과정에서 의견 조율이 안맞는 등의 힘든 부분도 있겠지만 타인과의 커뮤니케이션면에서 큰 성장을 할 수 있게 도와줬던 것 같습니다. 앞으로도 학교에서 팀프로젝트를 하던 해커톤을 나가던 누군가와의 협업은 필수로 하게될텐데 개발 기술뿐만 아니라 소통 능력을 어떻게 기를 것인가에 대해서도 고민해보면 좋을 것 같습니다.

2024-08-05 13:19 UTC, MangKyu approved these changes
안녕하세요! 6주차의 미션까지 고생 정말 많으셨습니다! 처음 리뷰를 보았던 것이 엊그제 같은데, 벌써 6주나 지났네요ㅎㅎ
최종 리뷰 요청까지 열심히 반영하고 달려주셔서 감사합니다 :bow:
어떻게 하면 마무리를 성공적으로 할 수 있을까 고민을 했는데, 최종적으로 프로젝트를 다시 보고, 피드백을 드릴 수 있는 부분을 드리면 좋을 것 같아서 시간 내어 정리해 보았어요!
이미 충분히 잘 개발해주셨는데 보다 좋은 개발자가 되시는 데 도움을 드리고 싶어서 작성한 것이니, 이를 학습 또는 개선의 방향 등으로 잡고 봐주시면 좋을 것 같습니다ㅎㅎ

- `@Autowired`의 사용
  - 스프링은 생성자가 1개인 경우, 생성자에 `@Autowired`를 붙이지 않아도 자동 주입을 지원해줍니다
  - `@Autowired`는 스프링 프레임워크가 제공하는 애노테이션이며, 이는 우리의 코드가 스프링이라는 프레임워크에 결합된다는 것을 의미하기도 합니다
  - 스프링은 POJO 기반의 애플리케이션을 지향하고자 하는 관점에서 시작된 프레임워크입니다
  - 따라서 불필요하게 `@Autowired`를 사용하지 않음으로써, 프레임워크로부터 까지도 순수하게 만들 수 있다면 더욱 바람직하다고 볼 수 있습니다
- Filter와 Interceptor
  - Filter는 서블릿 범위, Interceptor는 스프링 컨테이너 범위입니다
  - 인증되지 않은 사용자라면 스프링 컨테이너 내부에 침투하기도 전에 필터에서 먼저 거르는 것이 보다 안전할 수 있습니다
  - 따라서 필터와 인터셉터에 대한 차이를 이해하고, 그에 따른 선택을 하는 것이 필요합니다
  - 인터셉터라서 문제가 되는 것이 아니고, 인터셉터를 선택했다면 그에 따른 마땅한 이유가 있어야 함을 의미합니다
- DTO의 활용
  - Service 계층은 비즈니스 로직을 처리하는 계층입니다
  - 그런데 현재 구조 상으로는 클라이언트로부터의 입력과 출력에 대한 데이터가 Service 계층까지 활용되는 것을 볼 수 있습니다
  - 그렇다면 DTO를 격리시킬 것인지, 아니면 효율적인 개발을 위해 DTO의 침투를 허용할 것인지 등에 대해서도 고민해보시면 좋을 것 같습니다
- 연관 관계
  - 연관 관계는 객체 간의 관계를 맺어주어, 객체 간의 협력을 통해 변경에 유연한 개발을 할 수 있도록 도와줍니다
  - 하지만 이로 인해 N+1 문제와 같은 예상치 못한 동작이 생기기도 하고, 이로 인해 시스템 장애가 발생하기도 합니다
  - N+1과 같은 문제는 어떻게 해결할 수 있는지, 연관 관계의 장점과 단점은 무엇인지 한번 정리해보시면 좋을 것 같습니다
- 예측할 수 있는 네이밍
  - 우리는 다른 개발자들과 협업을 하며 개발을 해야 합니다
  - 그 과정에서 중요한 것 중 하나가 작성된 코드에 대한 믿음 그리고 예측 가능성입니다
  - 우리가 개발한 코드를 사용하는 다른 개발자가 세부 구현을 보지 않고도, 네이밍으로 동작을 예측할 수 있도록 작성하는 것이 좋은데, 이를 준수하면 협업이 쉬워집니다
  - ex) TokenUtil은 유틸 네이밍으로 인해 static 메서드로 구현될 것임이 예측되지만, Bean으로 등록되어 사용됨 
  - ex) User의 isDefaultLogin는 boolean을 반환할 것으로 기대되지만 내부적으로 예외를 발생시킴
- 테스트 코드
  - 우리는 개발을 하면서 수시로 리팩터링을 반복해야 코드를 유지보수하기 좋은 상태로 유지할 수 있습니다
  - 지속적인 리팩터링에서 안정성을 보장받을 수 있는 방법은 테스트(수동이든 자동이든) 밖에 없습니다
  - 테스트는 우리의 구현이 올바른지 검증해주는 훌륭한 도구인데, 현재의 테스트는 구현이 바뀌면서 함께 깨지게 됩니다
  - 따라서 어떻게 하면 코드가 변경되어도 테스트는 변경없이 우리의 코드가 안전함을 보장해줄 수 있을지 고민해보면 좋을 것 같습니다
  - 또한 이력서 등에는 구체화된 수치를 작성하는 것이 중요한데, 테스트 커버리지 등은 이러한 수치화를 위한 훌륭한 수단이 될 수 있습니다

마지막까지 정말 고생많으셨습니다! 앞으로도 좋은 일들만 가득하시길 응원합니다ㅎㅎ 화이팅하세요!

2024-08-05 13:20 UTC, merged