경북대 BE_김민주 6주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #139
Opened 2024-07-31 16:59 UTC by minju26

- `1단계 - API 명세` 
같은 팀 쿠키즈들과 협의한 api, response, request 관련 수정사항입니다!
- 아직 error에 대한 response는 협의하지 않아서, **성공 api에 대한 설명만 추가**하였습니다.
- ‼️ 키가 노출되지 않도록 카카오 로그인 과정을 아래와 같이 수정해보았는데, 멘토님의 피드백이 궁금합니다
```
client -[ api/members/kakao ] -> server - [ /oauth/authorize ] -> kakao server
```

2024-08-03 08:41 UTC, gongdongho12 requested changes
1단계 고생하셨습니다!

직렬화 부분에서 타 서비스의 json데이터를 사용하다 보니 snakeCase가 보이는데요
컨벤션 관점과 현재 사용하는 환경에 맞게 네이밍 방식은 공통으로 가져갈 수 있도록 노력 부탁드려요

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/constant/Message.java
> +    public static final String KAKAO_LOGIN_USER_MSG = "카카오 로그인 이용 회원입니다.";
이부분 주석으로 나눠져 있긴 하지만 SuccessMessage와 ErrorMessage로 객체를 분리해서 관리해보는건 어떠실까요?
이러면 메시지 구분이 확실히 되고 메시지 내용에 ERROR인지 SUCCESS인지 구분하게 지정하지 않아도 되니까요!

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/config/SwaggerConfig.java
> +                .addSecurityItem(securityRequirement);
엔드포인트를 이렇게 정의해 주셨는데 production 테스트가 가능하다는 장점이 있겠네요
나중에 profile로 구성해서 production test용 프로파일 실행한 경우에만 production 호출 가능하게 해보는 것도 좋을 것 같습니다

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +@RequestMapping("/api/products")
api path 구분 👍🏼

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +        return ResponseEntity.ok(productService.getOptions(productId));
컨트롤러 역할만 잘 분리해서 확실히 깔끔하네요 👍🏼

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/controller/WishListController.java
> +        return new ResponseEntity<>(wishListService.addWishProduct(new WishProduct(member.getId(), productId)), HttpStatus.CREATED);
minor) 객체를 생성하는 부분은 변수로 라인을 나눠도 괜찮을 것 같아요

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/controller/WishListController.java
> +    }
삭제가 잘 된건데 NO_CONTENT로 주지 않고 정상인 200으로 주지 않은 이유가 있을까요?

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/domain/Order.java
> +    private LocalDateTime orderDateTime;
주문 할 때 이 값이 생기는 거니까 JPA의 생성시간 자동화 기능으로 `@CreatedDate`으로 정리해볼 수 있지 않을까요?

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/dto/KakaoTokenInfo.java
> +}
다른 java 객체들은 전부 camel case인데 이부분만 snake case라 컨벤션에 어긋나 보이는데요
json 객체랑 실제 접근할 때에 대한 네이밍 규칙을 지정하면 이런 부분을 자연스럽게 해결 가능한데 한번 찾아보시면 어떨까요?

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/dto/KakaoTokenInfo.java
> +}
이렇게 처리되는 다른 부분도 확인해 주세요!

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/exception/ErrorCode.java
> +    KAKAO_LOGIN_USER(404, HttpStatus.BAD_REQUEST, KAKAO_LOGIN_USER_MSG);
에러 처리 enum 👍🏼

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/service/AuthService.java
> +    }
로그인 타입에 대한 조건 처리가 많은데요
이런 부분을 AOP로 어노테이션 지정해서
카카오 로그인이 가능한 메서드와 아닌 값으로 각각 구분해보면 어떨까요?

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/service/AuthService.java
> +    }
AOP가 과하면 간단하게 메서드로 만들어도 좋을 것 같습니다

2024-08-03 08:41 UTC, gongdongho12 commented on src/main/java/gift/service/KaKaoService.java
> +    private String sendMessageUrl;
전부 kakao 하위의 설정값을 가져오는 건데요
스프링에서 제공하는 `@ConfigurationProperites`를 사용해보시는 것도 좋을 것 같아요!

2024-08-03 08:41 UTC, gongdongho12 commented on src/test/java/gift/service/KaKaoServiceTest.java
> +        Assertions.assertThat(kakaoTokenInfo.refresh_token_expires_in()).isEqualTo(5184000);
카카오 동작에 대한 테스트 👍🏼

2024-08-03 08:41 UTC, gongdongho12 commented
Step 0 리베이스 이후 부탁드립니다

2024-08-03 15:44 UTC, minju26 commented on src/main/java/gift/constant/Message.java
> +    public static final String KAKAO_LOGIN_USER_MSG = "카카오 로그인 이용 회원입니다.";
넵! 구분해서 관리하도록 하겠습니다

2024-08-03 15:44 UTC, minju26 commented on src/main/java/gift/config/SwaggerConfig.java
> +                .addSecurityItem(securityRequirement);
네! 알겠습니다 :)

2024-08-03 15:45 UTC, minju26 commented on src/main/java/gift/controller/WishListController.java
> +        return new ResponseEntity<>(wishListService.addWishProduct(new WishProduct(member.getId(), productId)), HttpStatus.CREATED);
아하! 변수로 받고 넣는 방식으로 수정하도록 하겠습니다

2024-08-03 15:48 UTC, minju26 commented on src/main/java/gift/controller/WishListController.java
> +    }
**NO_CONTENT로 주지 않고 정상인 200으로 주지 않는다**는 것이 무슨 뜻인지 이해를 잘 못했습니다🥲
팀원들과 reponse에 대해 의논하다가 
삭제에 성공하고, response에 특별히 전달하고자 하는 내용(데이터)가 없는 경우에 NO_CONTENT를 보낸다는 내용을 보게 되어서 기존에 200을 반환하다가 NO_CONTENT로 변경하였습니다!

2024-08-03 15:49 UTC, minju26 commented on src/main/java/gift/domain/Order.java
> +    private LocalDateTime orderDateTime;
오호 그런것도 있군요! 반영하도록 하겠습니다

2024-08-03 15:49 UTC, minju26 commented on src/main/java/gift/dto/KakaoTokenInfo.java
> +}
넵! 네이밍 규칙 지정에 대해 찾아보고 수정해보도록 하겠습니다

2024-08-03 15:52 UTC, minju26 commented on src/main/java/gift/service/KaKaoService.java
> +    private String sendMessageUrl;
`@ConfigurationProperties`로 깔끔하게 정리하도록 하겠습니다!

2024-08-03 16:22 UTC, minju26 commented
> ### 질문
> * ‼️ 키가 노출되지 않도록 카카오 로그인 과정을 아래와 같이 수정해보았는데, 멘토님의 피드백이 궁금합니다
> 
> ```
> client -[ api/members/kakao ] -> server - [ /oauth/authorize ] -> kakao server
> ```
> 
> * Entity가 가지는 필드와 Response로 넘겨주어야 하는 정보의 종류가 동일한 경우, 그냥 Entity를 넘겨줘도 괜찮은지 아니면 내용이 똑같더라도 통일성을 위해 Dto를 만들어서 넘겨주어야 하는지 궁금합니다.
> 
> > 예를들어, Member에{ id, name}이 있고 요청하는 정보가 Member의 id와 name 인 경우,
> > 그냥 멤버 자체를 넘겨주기 vs MemberResponseDto {id, name} 를 만들어서 넘겨주기

pr 내용 중 질문에 대한 멘토님의 의견이 궁금합니다!

2024-08-04 06:56 UTC, gongdongho12 commented on src/main/java/gift/controller/WishListController.java
> +    }
아하 값이 없을때에 대한 컨벤션으로 지정하셨군요 👍🏼

2024-08-04 07:00 UTC, gongdongho12 commented
> ‼️ 키가 노출되지 않도록 카카오 로그인 과정을 아래와 같이 수정해보았는데, 멘토님의 피드백이 궁금합니다
client -[ api/members/kakao ] -> server - [ /oauth/authorize ] -> kakao server
Entity가 가지는 필드와 Response로 넘겨주어야 하는 정보의 종류가 동일한 경우, 그냥 Entity를 넘겨줘도 괜찮은지 아니면 내용이 똑같더라도 통일성을 위해 Dto를 만들어서 넘겨주어야 하는지 궁금합니다.
예를들어, Member에{ id, name}이 있고 요청하는 정보가 Member의 id와 name 인 경우,
그냥 멤버 자체를 넘겨주기 vs MemberResponseDto {id, name} 를 만들어서 넘겨주기

저는 필요한 값만 빼서 전달하는게 좋다고 생각합니다
실제로 카카오 로그인에서도 불필요한 대상은 필터링해서 보내주고 있거든요
ex) 프로필 사진을 보내지 않는다거나 등
그런 관점에서 허용한 데이터만 전달하는게 조금은 번거로울 수 있지만 합리적인 전달방법이라고 생각됩니다!

2024-08-07 14:23 UTC, gongdongho12 commented
@minju26 conflict 아직 남아있네요 😢

2024-08-07 14:26 UTC, minju26 commented
> @minju26 conflict 아직 남아있네요 😢

엇 step2가 머지되면서 생긴 것 같습니다..! 그냥 close 할까요?!

2024-08-07 14:28 UTC, gongdongho12 commented
@minju26 앗 제가 1 -> 2 -> 3 순서대로 안해서 그렇군요 😓 
2에 1 내용이 포함된 상태인지만 체크 부탁드려요

2024-08-07 14:40 UTC, minju26 commented
> @minju26 앗 제가 1 -> 2 -> 3 순서대로 안해서 그렇군요 😓 2에 1 내용이 포함된 상태인지만 체크 부탁드려요

괜찮습니다😊
2에 1내용 포함된 상태입니다! close 하겠습니다 :)

2024-08-07 14:40 UTC, closed without merging