경북대 BE_장우석 6주차 과제 (0단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #140
Opened 2024-07-31 17:16 UTC by us4c0d3

2024-07-31 17:31 UTC, sang5c requested changes
이전 단계 리뷰 확인하셨을까요? 🙂  
추가로, 테스트가 실패하니 확인해주세요~ 

<img width="438" alt="image" src="https://github.com/user-attachments/assets/38e90446-10c2-490f-aea3-eaf1bb274814">

2024-07-31 17:31 UTC, sang5c commented on src/main/java/gift/order/service/OrderService.java
> +    @Transactional(isolation = Isolation.READ_COMMITTED)
isolation level을 직접 제어하는 이유가 있을까요? 🤔

2024-07-31 17:31 UTC, sang5c commented on src/main/java/gift/product/option/dto/request/CreateOptionRequest.java
> +    @Max(value = 100_000_000 - 1)
🤔

2024-07-31 17:31 UTC, sang5c commented on src/main/java/gift/wish/entity/Wish.java
> +    }
메서드명과 내부 구현이 다르네요.

2024-07-31 17:31 UTC, sang5c commented on src/main/resources/application.properties
> +# 쿼리문 로그에 출력; 개발중 디버그용도 사용
<img width="744" alt="image" src="https://github.com/user-attachments/assets/ac27bef4-6a42-4401-8e23-a55cb5a79abe">
인코딩 설정이 UTF-8로 되어있는지 확인해주세요!

2024-07-31 17:44 UTC, us4c0d3 commented on src/main/java/gift/order/service/OrderService.java
> +    @Transactional(isolation = Isolation.READ_COMMITTED)
기본 격리 수준과 동일하므로 격리 수준 설정을 삭제하였습니다

2024-07-31 17:49 UTC, us4c0d3 reviewed
코드 수정했습니다!

2024-07-31 17:49 UTC, us4c0d3 commented on src/main/java/gift/order/service/OrderService.java
> +    @Transactional(isolation = Isolation.READ_COMMITTED)
기본 격리 수준과 동일하므로 격리 수준 설정을 삭제하였습니다

2024-07-31 17:49 UTC, us4c0d3 commented on src/main/java/gift/product/option/dto/request/CreateOptionRequest.java
> +    @Max(value = 100_000_000 - 1)
`99_999_999`로 수정하였습니다.

2024-07-31 17:49 UTC, us4c0d3 commented on src/main/java/gift/product/option/dto/request/UpdateOptionRequest.java
> +    Integer quantity
이 부분도 수정이 안된 것을 확인해 
```java
@Min(value = 1)
@Max(value = 99_999_999)
```
로 수정하였습니다.

2024-07-31 17:49 UTC, us4c0d3 commented on src/main/java/gift/wish/entity/Wish.java
> +    }
`isQuantityUnderZero`로 기능에 맞게 메서드명 수정했습니다.

2024-07-31 17:49 UTC, us4c0d3 commented on src/main/resources/application.properties
> +# 쿼리문 로그에 출력; 개발중 디버그용도 사용
이 부분은 매번 clone할 때마다 설정이 초기화되어 ide상에서 설정을 UTF-8로 변경했는데 왜 이렇게 push되었는지 모르겠습니다...

2024-08-01 12:30 UTC, sang5c commented on src/main/resources/application.properties
> +# 쿼리문 로그에 출력; 개발중 디버그용도 사용
어떤 버전을 사용하고 계신가요? 전역 설정 적용이 가능합니다  
https://www.jetbrains.com/help/idea/2024.1/settings-preferences-dialog.html?preferences&utm_source=product&utm_medium=link&utm_campaign=IU&utm_content=2024.1

2024-08-01 12:30 UTC, sang5c approved these changes
6주차 미션도 파이팅입니다~

2024-08-01 12:30 UTC, merged