경북대 BE_김동윤 6주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #141
Opened 2024-07-31 17:19 UTC by dong-yxxn

1단계를 하며 협업하며 api 문서 조율하고, 여기에 맞춰서 api 수정하는게  힘들었습니다. 배포도 제대로 할수있도록 하겠습니다.

2024-08-02 08:03 UTC, dong-yxxn commented
2단계

2024-08-04 13:05 UTC, MangKyu requested changes
6주동안 고생 많으셨어요 동윤님! 
이번 미션은 스펙 협의를 팀원들과 하는 부분이 상당히 중요한데요! 개발자라는 직군이 코딩만 하는 사람들이 아니라, 비즈니스 문제를 개발로 해결하는 사람들이다보니까요! 이를 위해 다른 사람들과 협업하는 자세와 이해가 상당히 중요한 것 같네요ㅎㅎ
그리고 이러한 협업에 유연하게 대처하려면 확장성있는 설계 역시 고려가 어느 정도는 필요하지 않을까 싶습니다!
몇 가지 변경 코멘트는 드렸는데, `properties` 파일에 서버 접속 주소가 노출된 부분을 제외하고는 강제하지 않을께요! `properties`의 서버 접속 주소만 필수로 고쳐주시고, 나머지는 선택적으로 수정 후에 다시 리뷰 요청 부탁드립니다~!

2024-08-04 13:05 UTC, MangKyu commented on deploy.sh
> +BUILD_PATH=$(find /home/ubuntu/repository/spring-gift-point/build/libs -type f -name "*.jar" | grep -v "plain" | head -n 1)
배포 스크립트 작성 💯

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/category/controller/CategoryController.java
> +@Tag(name = "카테고리 API")
API 문서화까지는 맞출 필요가 없을 것 같은데, 그래도 변경된 부분이 더 보기 좋은 것 같네요! 👍

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/category/service/CategoryService.java
>          category.setName(categoryDTO.name());
setter 보다는 생성자로 객체를 생성했으면 더 좋았을 것 같네요ㅎㅎ

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        model.addAttribute("product", new ProductRequest());
네이밍 변경하시느라 고생 많으셨습니다ㅎㅎ 다만, API 명세만 통일하면 내부 구현은 통일하지 않아도 될 것 같은데요! 이렇게 바꾸는 것이 좋은 것 같아서 변경하신 것인지 궁금하네요!

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/global/auth/config/WebConfig.java
> +            public void addCorsMappings(CorsRegistry registry) {
cors 설정 반영 👍

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/kakao/login/controller/KakaoLoginController.java
> +    @Value("${kakao.client-id}")
추후에 [ConfigurationProperties](https://mangkyu.tistory.com/191)에 대해서도 공부해보시고, 적용해보시면 좋을 것 같네요!

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/kakao/login/controller/KakaoLoginController.java
> +        Optional<User> userOptional = userService.findByEmail(loginRequest.email());
이렇게도 구현할 수 있을 것 같네요ㅎㅎ
```suggestion
        Boolean isLoginSuccess = userService.findByEmail(loginRequest.email())
                .filter(v -> v.isPasswordMatches(loginRequest.password()))
                .isPresent()
```

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/kakao/login/controller/KakaoLoginController.java
> +        String scheme = request.getScheme(); // http or https
해당 정보드를 property로 등록해놓고 관리하는 방식도 있을 것 같네요!

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/order/domain/Order.java
> +    public Order() {
```suggestion
    protected Order() {
```

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/product/domain/Product.java
> +    public void addOption(Option option) {
연관관계 관련 적용 👍

2024-08-04 13:05 UTC, MangKyu commented on src/test/java/gift/kakao/LoginTest.java
> -public class LoginTest {
테스트를 다 삭제하셨군요 😢  테스트는 우리의 코드에 대한 피드백을 해주는 소중한 동료입니다!
이번에 테스트로 인해 오히려 어려움을 겪으셨다면, 왜 테스트가 쉽게 깨졌는지 그리고 어떻게 하면 테스트를 유지할 수 있었을지 꼭 복기해보시면 좋을 것 같습니다ㅎㅎ

2024-08-04 13:05 UTC, MangKyu commented on src/main/resources/application.properties
> +kakao.redirect-uri=http://43.203.238.246:8080/api/members/kakao/redirect
서버 정보는 노출하지 않는 것이 좋을 것 같습니다...!!

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/order/controller/OrderController.java
> +        Long price = product.getPrice();
해당 부분은 객체에 핵심 도메인이 있는 것이 아니라, 데이터 중심의 절차적인 코드로 작성된 것 같네요!
어떻게 개선할 수 있을지 고민해보시면 좋을 것 같아요!

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/order/controller/OrderController.java
> +        @RequestParam(defaultValue = "0") int page,
default 활용 👍

2024-08-04 13:05 UTC, MangKyu commented on src/main/java/gift/product/controller/ProductController.java
> +        } catch (EntityNotFoundException e) {
예외 처리는 저희가 지정해둔 예외처리 클래스에서 했으면 더욱 좋았을 것 같습니다!

2024-08-04 13:15 UTC, merged