전남대 BE_김수랑 6주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #149
Opened 2024-07-31 18:31 UTC by rdme0

- README.md 에도 명세서가 있지만 http://localhost:8080/swagger-ui/index.html 로 더 자세한 명세서를 보실 수 있습니다

- 리팩터링 한 스케일이 큽니다.
   1. 저번 주차 피드백을 반영하였고, 주문 기능을 결국엔 4 계층으로 나누었습니다.
   2. 뷰를 제거하고, 모든 응답이 json이고 모든 Controller를 RestController로 리팩터링 하였습니다.
   3. 프론트엔드가 기능을 구현하기에는 너무나 많은 시간이 드는 기능들은 명세서에 표시 하지 않았습니다. 
   ex) 카카오 API 로그인 기능, 주문 히스토리 조회, 상품 관리자 기능 등등
   4. 응답코드를 다른 백엔드들과 통일하기 위하여 좀 더 단순하게 리팩터링 하였습니다.
   ex) 회원가입 이메일 중복 `409 CONFLICT` -> `400 BADREQUEST`
이 밖에도 여러 자잘자잘한 리팩터링들이 있습니다!

2024-08-03 18:43 UTC, Hongdonggeon requested changes
안녕하세요 수랑님
1단계 미션은 api 명세여서 크게 리뷰드릴 내용이 없네요!
궁금한게 api들 중`@hidden`처리 한 api들을 한 이유가 궁금합니다 (로그인 api들도 했더라고요) 
프론트가 구현하는데 오래걸릴 것 같아 api를 제공하지 않는다는 이유는 조금 부족한 것 같아요
코멘트 주세요!

2024-08-03 18:43 UTC, Hongdonggeon commented on src/main/java/gift/controller/CategoryController.java
> +    @Hidden
카테고리 등록, 수정, 삭제 api를 제공하지 않으면 카테고리 추가, 삭제 작업을 어떻게 할 수 있을까요?

2024-08-03 18:43 UTC, Hongdonggeon commented on src/main/java/gift/controller/KakaoAuthController.java
> +    public String loginOrRegister(@RequestParam String code) {
로그인 및 회원등록도 제공하지 않는 이유가 뭘까요? 
꼭 필요한 기능아닌가요?

2024-08-04 08:03 UTC, rdme0 commented
`@Hidden` 처리한 이유로는
첫 번째로 백엔드와 프론트엔드가 구현해낸 기능들이 차이가 있다는 것입니다.

백엔드가 구현해낸 기능들은 상품, 카테고리, 옵션, 위시리스트 CRUD와 주문하기, 일반 로그인, 소셜 로그인 이렇게 
선물하기 + 관리자 기능 + 기본/소셜로그인인데.

당시 프론트엔드가 구현해낸 기능들은 상품 조회, 옵션 조회, 위시리스트 CRUD, 일반 로그인 이렇게
선물하기 + 기본 로그인으로, 백엔드가 구현해낸 기능의 일부분 이였습니다.  

여기서 일주일 안에 프론트엔드가 백엔드가 구현하지 못한 기능을 일주일 안에 구현한다고 하기엔 현실적으로 불가능 하다고 느껴져서 저희 백엔드가 프론트엔드에게 맞추는 것으로 결정하였습니다.
제가 작성한 API 명세서는 저희 백엔드의 API 명세서와 똑같이 작성한 것인데, 저희 백엔드 API 명세서는 프론트엔드에게 백엔드 API를 어떻게 사용하는 것인지 설명하는, 즉 프론트엔드를 위한 명세서입니다. 그래서, 프론트엔드가 사용하지 않는 기능은 명세서에 표시하지 않았습니다. 다만, 만약에 카테고리나 옵션을 등록, 수정, 삭제를 하는 프론트엔드가 저희 백엔드 API를 사용하게 된다면 `@Hidden`을 없애고 명세서를 추가적으로 작성할 계획이였습니다.

두 번째로 백엔드끼리와도 구현해낸 기능들이 차이가 있다는 것입니다.  

저희 팀은 백엔드가 4명인데 이번주 스크럼을 하면서 저희 같은 백엔드끼리도 구현하지 않은 기능들이 있고, 요청을 받는 DTO와, 응답을 보내는 DTO, 엔티티의 필드 값, 각 엔티티간의 관계, 컨트롤러, 서비스의 로직, 검증 로직, 뷰의 구현 방식, 뷰에게 보내는 데이터의 개수 등등 모든 것이 다 다르다는 것을 알게 되었습니다. 모든 것을 맞추기엔 배가 산으로 갈 것 같았습니다 ㅠㅠ

그래서, 제가 `@Hidden`을 하지 않고, 모든 기능들을 서로 다른 백엔드 쿠키즈와 맞추기엔 걸리는 시간이 적어도 저희 팀 모두가 최소 2주 넘게 걸릴 것이라 생각하고 불가능하다고 생각이 들었습니다. 그래서, 프론트엔드가 사용하는 기능에 대한 선택과 집중을 해서, 프론트엔드가 사용하는 기능을 백엔드 끼리 요청, 응답 양식을 맞추는 방향으로 결정하게 되었습니다.  

그런 이유로 현재는 백엔드 각자가 카테고리와, 상품 옵션을 처음에 DB로 추가를 하고나서 프론트에게 배포를 하는 방식으로 구현하게 되었습니다.

2024-08-04 08:07 UTC, rdme0 commented on src/main/java/gift/controller/KakaoAuthController.java
> +    public String loginOrRegister(@RequestParam String code) {
아래에 말씀드린 이유로 인해서 현재는 일반 로그인만 명세서에 표시해놓았습니다!

2024-08-04 10:15 UTC, Hongdonggeon approved these changes
안녕하세요 수랑님
1단계 미션 구현하느라 수고많으셨습니다
1단계는 머지할게요!

2024-08-04 10:15 UTC, merged