전남대 BE_박준형 6주차 과제(step1)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #160
Opened 2024-08-01 03:11 UTC by cliant

### 코드를 작성하면서 어려웠던 점

- API명세를 팀단위로 맞추는 데에 우선 어려움을 겪었습니다.  큰 틀에서의 같은 기능을 하지만 요청이나 응답에서 서로 코드가 조금씩 달랐기 때문에 기준을 잡기 위해 서로 코드의  구현 상태보다는 FE 분들과의 협의를 통해 기준이 되는 API명세를 결정하고 거기에 맞춰 코드를 리팩토링 하는 방식을 결정하였습니다. 

### 코드 리뷰시 중점적으로 봐주셨으면 하는 부분

- 리팩토링할 양이 많다보니 entity별로 명세에 맞춰 Request와 Response를 다시 만들었습니다. 또한 단계별 과제이다보니 앞단계를 구현할 때 보이지 않았던 문제가 지금에 와서 보이기도 하였습니다. 이를 수정했지만 틀림없이 수정한 부분에도 문제가 있을 것이기 때문에 이에 대해 짚어주셨으면 합니다.

2024-08-02 02:00 UTC, dc-choi requested changes
안녕하세요. 준형님.

이번 과제에서는 API 명세에 대한 학습을 하는 과제였습니다.

코멘트 남겨주셨는데 해당 부분에 대한 답 먼저 드리도록 하겠습니다.

> 또한 단계별 과제이다보니 앞단계를 구현할 때 보이지 않았던 문제가 지금에 와서 보이기도 하였습니다. 이를 수정했지만 틀림없이 수정한 부분에도 문제가 있을 것이기 때문에 이에 대해 짚어주셨으면 합니다.

혹시 어떤 부분에서 문제가 있다고 판단하셨는지, 기능이 수정이 되는지 여부가 궁금합니다.

또한 준형님께 몇가지 질문을 드리려고 합니다! 확인 부탁드려요!

1. 노션으로 팀끼리 작업하신게 맞으신가요? 맞다면 매우 잘하신거 같습니다!
2. 기존에 작업하신 부분에서 서로 토론을 하게 되면서 어떤 부분이 달라지셨는지 궁금합니다!

2024-08-02 03:04 UTC, cliant commented
> 1. 노션으로 팀끼리 작업하신게 맞으신가요? 맞다면 매우 잘하신거 같습니다!

넵 !https://alive-tail-1fa.notion.site/API-778e7fee2b6c45f4bf19c06ac1e15461 이와 같이 API문서를 노션으로 작업하여 결정하였습니다.

> 2. 기존에 작업하신 부분에서 서로 토론을 하게 되면서 어떤 부분이 달라지셨는지 궁금합니다!

- 우선 제가 Request와 Response 객체를 많이 사용하지 않았어서 형식에 맞지 않는 경우가 있었습니다. 그래서 명세서를 바탕으로 모든 작업의 request, response 객체를 만들어주었습니다. 

- 예외에 대한 명세도 정하다 보니 제가 놓치고 예외처리를 안한 부분들이 보였습니다. 특히 생성 작업에서는 중복 검사를 하지만 수정 작업에서 중복검사를 하지 않았던 경우들이 많았습니다. 그래서 제가 놓친 부분들에 대해 예외처리를 할 수 있었습니다.

2024-08-02 08:16 UTC, cliant commented
이번 주 API명세 맞춰짐에 따라 리팩토링 하다보니 진행이 늦어져 과제 제출을 위해 step1이 merge되지 않은채 step2를 진행하였습니다.. 죄송합니다.

2024-08-03 11:59 UTC, dc-choi requested changes
안녕하세요. 준형님.

배포 관련되어서는 어떤 문제인지 확인하였습니다.

22 port에 대한 접근 허용을 해줘야 하는 것으로 보입니다.

그리고 혹시 배포 스크립트도 확인할 수 있을까요?

2024-08-04 02:37 UTC, cliant commented
ssh접속이 안되어 git repository를 clone 해올 수 없는 상황이어서 배포 스크립트도 업로드 못했었습니다. 원인은 모르겠으나 다시 재부팅을 해보니 접속이 되어 이후 배포링크를 통해 접속이 되는 것을 확인했습니다! 배포링크에 접속시 관리자 페이지가 연결되도록 하였습니다.

2024-08-04 13:02 UTC, dc-choi requested changes
배포 사항 수정하시느라 고생하셨습니다!

혹시 배포 스크립트를 한번 확인해볼 수 있을까요?

2024-08-04 13:13 UTC, cliant commented
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-point/commit/7180efe44bb0d94485321414211c5db3c7985006 이 커밋에 있습니다!

2024-08-04 14:17 UTC, dc-choi approved these changes
네 확인하였습니다!

다음 step 과제 진행해주시면 될 거 같습니다!

2024-08-04 14:17 UTC, merged