경북대 BE_안재민 6주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #181
Opened 2024-08-01 08:12 UTC by dkswoals

6주차 1단계 요구사항 구현 후 리뷰 요청 드립니다!
변경된 Api 명세로 프로젝트를 변경하다 보니 기존 프로젝트에서 변경되어야 할 것이 많아서
전반적인 퀄리티가 많이 떨어진 것 같습니다..
## 과제 진행 중 궁금한 점
- 이번에 타임리프로 관리자 페이지를 구현하면서 사용자에게 특정 폼을 입력 받을 시
불변 객체에 대한 바인딩이 될 때도 있고 안될 때도 있었습니다
(getter만으로 바인딩 하려 해도 일관적으로 통하진 않았습니다 ㅠㅠ)
그래서 입력 폼 객체는 가변 객체로 구현 하였는데 이런 방식이 괜찮은지 궁금합니다!

2024-08-02 03:45 UTC, leaf-upper requested changes
👍 안녕하세요 재민님~
1단계 구현 고생많으셨습니다. FE분과 협업하면서 많은 API명세가 변경된것 같은데요~
그와 동시에 도메인쪽도 많이 변경이 된것 같아요. 
API명세는 바뀌더라도 도메인쪽 로직 수정은 최대한 변경이 일어나지 않게 코드를 작성해주시면 더 좋은 코드가 될것 같습니다.
몇가지 코멘트를 드렸는데 확인해주시면 어프로브드릴게요~ 고생하셨습니다 👍

2024-08-02 03:45 UTC, leaf-upper commented on src/main/java/gift/interceptor/AuthInterceptor.java
> +            throw new JwtException(ErrorCode.ACCESS_DENIED.getMessage());
👍 👍 권한체크를 해주는 애너테이션을 만드셨네요

2024-08-02 03:45 UTC, leaf-upper commented on src/main/java/gift/repository/OptionRepository.java
> +public interface OptionRepository extends JpaRepository<Option,Long> {
OptionRepository가 다시 생겨났네요~
ItemService와 ItemRepository를 통해서 로직을 작성해보는건 어떨까요?

2024-08-02 03:45 UTC, leaf-upper commented on src/main/java/gift/service/OrderService.java
> +    private final ItemRepository itemRepository;
ItemRepository가 아니라, ItemService를 사용해서 로직을 작성해보면 더 좋을것 같아요.

2024-08-02 03:45 UTC, leaf-upper commented on src/main/java/gift/model/dto/OrderDTO.java
> +    public OrderDTO(Long id, Long optionId, Long quantity,
주문을할때 optionId뿐만아니라, itemId도 받으면 좋을것 같아요~

2024-08-02 03:45 UTC, leaf-upper commented on src/main/java/gift/model/entity/Order.java
> -    private Long itemId;
itemId가 사라진 이유가 있을까요?

2024-08-02 03:50 UTC, dkswoals commented on src/main/java/gift/repository/OptionRepository.java
> +public interface OptionRepository extends JpaRepository<Option,Long> {
팀 내 대부분의 백엔드 팀원들은 optionRepository와 service가 구현되어 있어
api 요청에서 optionId 만으로 대부분의 요청 처리가 가능하였기에
제가 수정하였습니다..

2024-08-02 03:52 UTC, dkswoals commented on src/main/java/gift/service/OrderService.java
> +    private final ItemRepository itemRepository;
반영하겠습니다!

2024-08-02 03:59 UTC, dkswoals commented on src/main/java/gift/model/dto/OrderDTO.java
> +    public OrderDTO(Long id, Long optionId, Long quantity,
위와 유사한 이유와 이미 팀 내 Api 명세가 확정이 되어 수정을 위해서는 팀원 전체의 수정이 필요하지만
과제 제출 일이 금일까지기에 수정이 조금 힘들 것 같습니다 ㅠㅠ
참고하여 다음 프로젝트 때 주문 데이터에는 더욱 구체적인 정보들을 담도록 하겠습니다..!

2024-08-02 05:20 UTC, leaf-upper commented on src/main/java/gift/repository/OptionRepository.java
> +public interface OptionRepository extends JpaRepository<Option,Long> {
OptionId로만 쿼리를 작성해야한다면 아래처럼 작성할 수 있을까요?
select * from products p join options o on p.id = o.product_id where o.id = {optionId}

2024-08-02 07:01 UTC, dkswoals commented on src/main/java/gift/repository/OptionRepository.java
> +public interface OptionRepository extends JpaRepository<Option,Long> {
팀 회의로 Api 명세 수정 후 반영 하였습니다!!

2024-08-02 07:01 UTC, dkswoals commented on src/main/java/gift/model/dto/OrderDTO.java
> +    public OrderDTO(Long id, Long optionId, Long quantity,
반영하였습니다!

2024-08-02 07:04 UTC, dkswoals commented on src/main/java/gift/model/entity/Order.java
> -    private Long itemId;
처음엔 주문 기록을 optionId로만 구성하려 했는데
이후 팀 회의로 다시 itemId가 포함되도록 수정하였습니다!

2024-08-02 07:06 UTC, dkswoals commented
피드백을 반영하면서 
팀 내 주문 요청 API 명세에 추가된 Point 기능(3단계)까지 함께 구현한 후
리뷰요청 드립니다!
2단계는 빌드 스크립트이기에 1단계 머지 이후 바로 구현하겠습니다!

2024-08-04 05:19 UTC, leaf-upper approved these changes
👍 👍 6주차 고생하셨습니다. 재민님~
몇가지 코멘트를 남겨드렸는데요~ 현재에서는 크게 중요하지 않을것 같아서. 어프로브 드리겠습니다.

2024-08-04 05:19 UTC, leaf-upper commented on src/main/java/gift/service/OrderService.java
> +        user.increasingPoint(accumulatePoint);
포인트와 관련된 작업을 할때는 Lock을 설정해주시면 좋을것 같아요.
추가로 포인트 적립 및 소진 내역을 별도 테이블로 관리해주시면 이후에 유저 포인트 관리에 용이할것 같습니다~!

2024-08-04 05:19 UTC, merged

2024-08-04 08:38 UTC, dkswoals commented on src/main/java/gift/service/OrderService.java
> +        user.increasingPoint(accumulatePoint);
동시성 이슈가 발생 가능한 영역을 고려하면서 로직을 구성해야 하는군요,,!
알려주셔서 감사합니다!
6주차도 고생 많으셨습니다😀