전남대 BE_서지우 6주차 과제(step1)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #188
Opened 2024-08-01 09:44 UTC by seojiu

팀 api 명세에 맞추어 전반적으로 수정했습니다.
https://www.notion.so/API-c08cf7e645d849bc8d949146bbf5486c

2024-08-02 09:56 UTC, pkeugine requested changes
안녕하세요 지우님,
api 통일하시느라 고생 많으셨습니다.
그런데 이전부터 대화했던 git 내용을 한 번 적용해보시면 좋을 것 같아서
우선 request changes 드려요.
이 부분 적용한 뒤에 이어 리뷰해보도록 하겠습니다.
파이팅입니다!

2024-08-02 09:56 UTC, pkeugine commented on README.md
> +# spring-gift-point
지우님, 0단계에 머지된 커밋은 이번 PR 에서 제외해주시면 감사하겠습니다.
[이전에도 리뷰로 남겼던 내용](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-order/pull/279#discussion_r1694261367)이라, 이번엔 한 번 해보시면 좋을 것 같아요.

2024-08-02 12:54 UTC, seojiu commented on README.md
> +# spring-gift-point
rebase 했는데 제대로 된 건지 모르겠습니다😭
아직까지 git 다루는게 익숙해지지 않네요

2024-08-04 09:35 UTC, pkeugine approved these changes
안녕하세요 지우님,
api 명세 통일이다보니 대부분의 변경이 dto 관련이네요!
잘 진행해주신 것 같아서 이 step 은 바로 머지하도록 하겠습니다.
고생하셨습니다!

2024-08-04 09:35 UTC, merged

2024-08-04 09:35 UTC, pkeugine commented on README.md
> +# spring-gift-point
이 기회에 git 관련 경험을 해보는거죠 👍