경북대 BE 박한솔 6주차 과제 (1,2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #197
Opened 2024-08-01 12:52 UTC by pjhcsols

2024-08-02 13:24 UTC, lsm7179 requested changes
한솔님 과제 수고하셨습니다.
요구사항에 배포 스크립트 작성도 있는데 이부분이 누락된거 같아요.
다시 추가 후 리뷰 요청해주세요.

2024-08-02 13:24 UTC, lsm7179 commented on src/main/java/gift/config/jwt/SecurityConfig.java
> +        //configuration.setAllowedOriginPatterns(Arrays.asList("http://localhost:8080", "http://*.example.com"));
불필요한 주석은 삭제해주세요.

2024-08-02 13:24 UTC, lsm7179 commented on src/main/java/gift/controller/admin/AdminProductController.java
> +        return "product";  // Thymeleaf 템플릿 이름
`// Thymeleaf 템플릿 이름` 이 주석이 꼭 필요한가요?

2024-08-02 13:24 UTC, lsm7179 commented on src/main/java/gift/controller/user/UserController.java
> +        }
`exceptionHandler`를 이용해도 좋을거 같네요~

2024-08-02 13:24 UTC, lsm7179 commented on src/main/java/gift/service/user/UserService.java
> +/*
이런 불필요한 주석은 pr 만들기 전에 한번 확인해서 정리해주세요.

2024-08-02 15:31 UTC, pjhcsols commented on src/main/java/gift/service/user/UserService.java
> +/*
확인하였습니다.

2024-08-02 15:32 UTC, pjhcsols commented on src/main/java/gift/controller/admin/AdminProductController.java
> +        return "product";  // Thymeleaf 템플릿 이름
구분을 위해 달아놓은 주석이였는데 제거하였습니다!!

2024-08-02 15:41 UTC, pjhcsols commented on src/main/java/gift/controller/user/UserController.java
> +        }
GlobalExceptionHandler로 중앙 예외처리를 하였습니다.

2024-08-03 02:01 UTC, lsm7179 approved these changes
한솔님 과제 수고하셨습니다~!

2024-08-03 02:01 UTC, lsm7179 commented on src/main/resources/deploy.sh
> +  kill -15 $CURRENT_PID
`kill -9`와 차이점이 있는데 각각의 차이점을 알고 가면 좋을거 같네요~!

2024-08-03 02:01 UTC, merged