경북대 BE_김민주 6주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #209
Opened 2024-08-01 14:48 UTC by minju26

- `2단계-배포하기` 과제 제출합니다!
- Repository 관련 테스트를 모두 주석처리 하였는데, 프론트와 협업 중 데이터 조율이 필요해서 일단 주석처리 했습니다.
- 2단계 미션에 배포 스크립트 작성이 있어서 `script/deploy.sh` 올려두었습니다.

2024-08-03 09:16 UTC, gongdongho12 requested changes
CORS이외에 배포나 Shell스크립트는 빠진 것 같습니다
1단계 내용 여기에 반영 부탁드리구

주석으로 놔두기보다는 사용하지 않을 내용은 지워주시면 클린 코드 관점에서 도움이 될 것 같습니다!

고생하셨습니다

2024-08-03 09:16 UTC, gongdongho12 commented on build.gradle
> +    testImplementation 'com.squareup.okhttp3:mockwebserver:4.9.3'
오 mockwebserver 시도해보시는군요 👍🏼

2024-08-03 09:16 UTC, gongdongho12 commented on src/main/java/gift/config/WebConfig.java
> +    }
CORS 설정에 쿠키는 30분으로 설정해주셨군요!
이부분은 FE와 싱크된 내용이죠?

2024-08-03 09:16 UTC, gongdongho12 commented on src/main/java/gift/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(exception.getErrorCode().getStatus())
에러코드의 상태를 커스텀 Exception으로 공통화 하셨군요 👍🏼

2024-08-03 15:56 UTC, minju26 commented on src/main/java/gift/config/WebConfig.java
> +    }
넵! 그리고 요구사항에도 있던 내용이라 저렇게 반영했습니다

2024-08-03 15:59 UTC, minju26 commented
> CORS이외에 배포나 Shell스크립트는 빠진 것 같습니다 1단계 내용 여기에 반영 부탁드리구
> 
> 주석으로 놔두기보다는 사용하지 않을 내용은 지워주시면 클린 코드 관점에서 도움이 될 것 같습니다!
> 
> 고생하셨습니다

배포는 배포 주소를 올려야 하는걸까요..?!
`http://13.124.137.243:8080` 배포 된 상태이고, 프론트와의 연결도 확인했습니다!
그리고 스크립트는 pr 내용에도 있듯이, `script/deploy.sh` 에 올려두었습니다 :)

pr내용중 질문에 대한 멘토님의 조언을 듣고싶습니다 :)

2024-08-03 16:30 UTC, minju26 commented on src/main/java/gift/script/deploy.sh
> +#!/bin/bash
여기가 스크립트입니다!

2024-08-04 06:50 UTC, gongdongho12 reviewed
앗 제가 질문에 대한 답변을 깜빡 했군요

> GET /redirectUrl?code= 에서는 클라이언트로 바로 이동할 수가 없어서 redirectView를 이용해서
클라이언트가 로그인 성공 후 이동하고 싶은 경로로 이동 시키려 하는데, 토큰을 쿼리 파라미터로 밖에 보낼 수가 없었습니다.

이부분 이동은 어떤 방식으로 옮기신 걸까요? GET만 되는 방식으로 redirect라고 하셔서 

> 현재 팀이 FE 2명, BE 4명으로 구성되어 있어서 요청하는 클라이언트가 2개인 상태입니다. 1번 질문에서와 같이 클라이언트가 로그인 성공 후 이동하고 싶은 경로로 이동 시키려면 두 프론트 주소 중에 어느 주소인지 알아야 하는데, 요청 받은 주소를 알 수 있는 방법이 있는지 궁금합니다. 보통 FE와 BE가 1:1로 협업하다가 FE가 둘이 되니 생긴 이슈인 것 같습니다.
여러 방법을 시도하다가, 현재는 카카오 로그인 요청 시 자신들의 주소를 (body, 쿼리 파라미터 등으로) 보내주자는 이야기가 나온 상태입니다.

FE가 둘이라는게 프론트 클이언트가 둘이라는 거죠?
같이 하나의 FE를 만드는게 아니라 두개의 FE를 만드는 과정일까요?
이런 경우에는 아까 말씀주신 내용처럼 진행하는 방법이 있고, BE 서버를 두개 둬서 각각 1:1로 연결하는게 좋을 것 같습니다
BE는 하나로 가는데 FE가 둘인 이유가 신기하네요...

2024-08-04 06:50 UTC, gongdongho12 commented on src/main/java/gift/script/deploy.sh
> +#!/bin/bash
아하 내용 확인했습니다 👍🏼

2024-08-07 09:07 UTC, minju26 commented
@gongdongho12 
본 pr에 1단계, 2단계에 피드백에 대한 수정했습니다.
곧 3단계에 대한 수정사항도 3단계 pr에 올리도록 하겠습니다.
감사합니다!😊

### 수정사항
-  SuccessMessage와 ErrorMessage로 객체 분리
- 객체 생성 부분 변수로 라인 분리
- 주문 시간에 대해 JPA의 생성시간 자동화 기능(`@CreatedDate`) 사용
- snake case -> camel case 네이밍 규칙 통일 (`@JsonProperty`)
- 로그인 타입 처리에 대한 메서드 생성
- 중복된 설정값 `@ConfigurationProperites` 사용
- 주석처리 했던 RepositoryTest 작동하도록 수정

2024-08-07 11:03 UTC, gongdongho12 approved these changes
고생하셨습니다
3단계에서 반영해주세요!

2024-08-07 11:03 UTC, merged