충남대 BE_박서현 6주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #214
Opened 2024-08-01 15:56 UTC by sseooh

2024-08-03 05:50 UTC, jjongwa requested changes
마지막 과제 고생 많으셨어요.! 협업 과정이 익숙하지 않았을텐데 어떠셨는지 궁금하네요..ㅎㅎ

1단계의 요구사항에 비해 전체적으로 코드의 변경사항이 많아진 것 같은데요, (특히 서비스 부분)
어떠한 과정에서 이렇게 많은 변경사항이 일어나게 되었는지, 해당 작업이 1단계의 요구사항인 API 명세를 맞추기 위해 발생한 불가피한 작업이었는지 궁금합니다.!

팀원들과 api 명세, 엔드포인트를 맞추기 위해선 어떤 변화가 있었어야 했는지 각 패키지 별로 섦명 부탁드려요! (controller, domain, dto, service)

해당 질문과 리뷰에 대한 답변 후 다시 요청주시면 1단계는 바로 머지하도록 하겠습니다,!

2024-08-03 05:50 UTC, jjongwa commented on src/main/java/gift/domain/Wish.java
> +
현재 구성에서는 사용하지 않는 것 같은데, 새롭게 추가한 이유가 있을까요?

2024-08-03 05:50 UTC, jjongwa commented on src/main/java/gift/domain/OrderItem.java
orderItem을 삭제한 이유는 무엇인가요?
더해서, domain 패키지 내부에 존재하는 엔티티들에 변경이 일어난 이유는 협업 과정에서 필요했는지, 아니면 본인의 독자적인 리팩토링 과정인지 궁금합니다.!

2024-08-03 05:50 UTC, jjongwa commented on src/main/java/gift/dto/OrderRequest.java
> +    }
이런 간단한 dto에서는 setter를 쓰지 않는 걸 추천드립니다~!
(지금 사용하지 있지도 않은 것 같습니다만..)

저번에도 질문 드렸던 것 같은데, 서현님이 생각하는 dto의 목적은 무엇인지, 그러한 관점에서 setter는 어떤 역할을 할 수 있는지 정리해 볼까요?

2024-08-03 05:50 UTC, jjongwa commented on src/main/java/gift/dto/ProductDTO.java
(OptionDto도 마찬가지로) ProductResponse가 아닌 Dto가 붙은 이유는 무엇인가요?

2024-08-04 00:19 UTC, sseooh commented on src/main/java/gift/domain/Wish.java
> +
이전에 구성했던 Wish에서는 createdDate가 없었는데 이번에 프론트와 협업하며 createdDate 추가하게 되었습니다!
getter를 사용하고 있지 않은 것을 확인하여 삭제했습니다.

2024-08-04 00:21 UTC, sseooh commented on src/main/java/gift/domain/OrderItem.java
domain 패키지 내부에 존재하는 엔티티들과 관련한 변경은 모두 협업 과정에서 필요하다고 판단하여 변경한 사항입니다..!

2024-08-04 00:36 UTC, sseooh commented on src/main/java/gift/dto/ProductDTO.java
Option과 Product에서는 Response와 Request의 구분이 딱히 필요하지 않은 것 같아서 Dto로 작성했습니다..!

2024-08-04 00:52 UTC, sseooh commented on src/main/java/gift/dto/OrderRequest.java
> +    }
dto는 엔티티와 다르게 비즈니스 로직이 없고 단순하게 데이터를 이동시키는 역할을 합니다! 따라서 dto에서는 setter의 사용이 비교적 자유롭다고 하여 만들어놨습니다...! 하지만 다시 확인해보니 말씀하신대로 사용하고 있지 않아 제거했습니다..

추가적으로, dto를 사용할 때 @RequesetBody로 데이터가 넘어오면 내부적으로 메서드 처리를 해주기 때문에 setter가 없어도 값이 자동으로 채워지게 된다고 하네요!!

2024-08-04 14:37 UTC, jjongwa commented on src/main/java/gift/domain/OrderItem.java
협업 과정에서 왜 엔티티 구조의 변경이 필요했는지 궁금하네요.! api 명세를 통일한다는 건 결국 내부 구현은 상관 없이 request, response와 같은 엔드포인트만 맞추면 될 것 같은데, 이전의 상태에서는 원하는 응답을 내려줄 수 없는 구조였나요?

2024-08-04 14:40 UTC, jjongwa commented on src/main/java/gift/dto/OrderRequest.java
> +    }
> dto에서는 setter의 사용이 비교적 자유롭다고 하여

여기서 setter의 사용이 자유롭다는 뜻은 어떤 의미일까요? 로직 중간에 해당 dto의 내부 필드 값이 바뀌어도 괜찮다는 걸까요? 단순하게 데이터를 이동시키는 역할을 하는 객체가 자신이 가진 데이터를 언제든지 마음대로 변경할 수 있는 구조여도 될까요?

그냥 그렇다더라 하고 맹목적으로 쓰기 보단 왜 그러한지 이유를 한 번 생각해 보고 사용하는 습관을 기르는게 좋을 것 같습니다! 
제가 봤을 땐 setter 사용이 자유롭다는 해당 내용의 의미를 잘못 이해하고 있는 것 같네요.

2024-08-04 14:43 UTC, jjongwa commented on src/main/java/gift/dto/ProductDTO.java
왜 구분히 필요하지 않은지 이유를 적어주면 좋을 것 같아요~!

지금 보았을 땐 응답으로만 사용하고 있어서 Resposne를 붙여주는 게 좋아 보이는데요.!

2024-08-04 14:43 UTC, jjongwa approved these changes
코멘트 확인해 주세요~!

2024-08-04 14:43 UTC, merged

2024-08-05 01:15 UTC, sseooh commented on src/main/java/gift/domain/OrderItem.java
원하는 응답을 내려줄 수 없는 구조는 아니었지만, 이전의 엔티티 구조는 불필요하게 복잡한 구조라고 생각되어 변경하게 되었습니다..! 이전에는 OrderItem에서 각각의 주문 상품을 담고 있고, Orders에서 사용자가 주문한 상품의 리스트를 갖는 구조였는데, 상품의 리스트를 굳이 저장되어 있을 필요가 없을 것 같다고 느껴졌습니다! 따라서 각각의 주문 상품만 저장한 후, 전체 주문 리스트가 필요한 상황에서는 getOrders로 리스트를 가져오도록 변경했습니다.

2024-08-05 01:16 UTC, sseooh commented on src/main/java/gift/dto/ProductDTO.java
현재 로직에서는 Response만 dto를 사용하고 있어서 Request와 Response를 구분해서 이름을 지을 필요가 없을 것 같다고 생각했습니다! 하지만 반대로 생각하면 멘토님 말씀대로 Response로만 사용하고 있기 때문에 Response를 붙여주는게 맞겠네요..!