경북대 BE_장우석 6주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #219
Opened 2024-08-01 18:28 UTC by us4c0d3

## 구현

* CORSconfig를 추가하였고, 테스트 코드 및 실제 FE 페이지와 연결하여 정상적으로 요청을 처리하는 것을 확인했습니다.
* 테스트 중 JpaRepository가 categoryId를 정상적으로 읽지 못하는 문제를 발견했습니다.
  * JpaRepository가 제공하는 기능은 실제 DB 필드명을 기반으로 쿼리문을 보내기 때문에 `findAllByCategoryId`가 아닌 `findAllByCategory_Id`를 사용했어야 했습니다.
* 배포 쉘 스크립트를 과제의 예제를 참고하여 작성했습니다. 이 코드는 EC2에 저장했고, 코드 변경이 생기면 직접 실행해야됩니다. 만약 자동화를 한다고 했을 때, github actions를 이용해 branch 트리거(pr, push 등) 필요할 것이라고 생각되는데 어느 브랜치를 트리거로 만들어야될 지 모르겠습니다. 목요일 강의에서 제이슨님도 CI/CD는 꼭 할 필요 없다고 하셔서 일단 넘어갔습니다.

```bash
#!/bin/sh

# Set Variable
REPOSITORY_PATH=/home/ubuntu/repository/spring-gift-point
BUILD_PATH=$(ls $REPOSITORY_PATH/build/libs/*.jar)
DEPLOY_PATH=/home/ubuntu/deploy/
JAR_NAME=$(basename $BUILD_PATH)

# kill process
CURRENT_PID = $(pgrep -f $JAR_NAME)

if [ -z $CURRENT_PID ]
then
        sleep 1
else
        kill -15 $CURRENT_PID
        sleep 5
fi

# build
REPOSITORY_PATH=/home/ubuntu/repository/spring-gift-point/
cd $REPOSITORY_PATH
./gradlew bootJar

# deploy
cp $BUILD_PATH $DEPLOY_PATH
cd $DEPLOY_PATH

DEPLOY_JAR=$DEPLOY_PATH$JAR_NAME
nohup java -jar $DEPLOY_JAR &
```

## 문제점

현재 배포 페이지에 접속을 하면 메인페이지를 관리자 페이지로 매핑해뒀습니다. 그래서 메인페이지 접속은 잘 되나 상품관리페이지에 500에러와 함께 접속이 되지 않습니다. 스프링 로그에서는 페이지 html을 불러오는 과정에서 타임리프 파싱에 에러가 발생한다고 되어있으나 로컬에서는 정상적으로 동작해 어떤 부분이 문제인지 잘 모르겠습니다.

---

## 협업을 하며

FE와의 소통을 하며 제가 개발하는 로직 및 데이터가 프론트 입장에서 불편할 수 있겠구나라고 다시 생각하는 계기가 되었습니다. FE 개발자는 특히 서비스 사용자 입장에서 생각한다고 느껴지는데 그러다보니 응답 데이터가 어떤게 더 필요하고 어떤게 오히려 필요없는지를 많이 소통한 것 같습니다.

그리고 하나의 기능 요구사항을 보면서도 각자의 해석이 달랐습니다. 예를 들어 3단계 포인트 기능에 대한 회의를 진행할 때, 팀 5명 중 2명은 포인트가 현금 개념이라고 생각하였고 나머지 3명은 적립금 개념으로 생각하였습니다. 이러한 부분을 생각했을 때 회의와 의사소통이 굉장히 중요하다고 느꼈습니다.

2024-08-03 06:29 UTC, sang5c requested changes
관리 페이지에서 발생하는 에러는 저한테 에러 로그 보내주시면 확인해보겠습니다.  

어떤 이유로 기존에 제공된 힌트에서 일부 명령어들이 달라졌을까요?  
배포 스크립트도 포함해서 PR진행해주세요~

2024-08-03 06:29 UTC, sang5c commented on README.md
> +## 2단계(배포하기) 요구사항
README에 요구사항을 그대로 붙여넣기 하지 마시고, 자신의 방식으로 요구 사항을 정리해주세요!  
기존에 작성된 미션들에 대한 요구사항도 정리해주세요 :)

2024-08-03 14:29 UTC, us4c0d3 reviewed
리드미 요구사항에서 제공된 코드 및 이미지를 삭제하고, 당시 단계에서의 실제 개발 스펙에 맞게 코드, Request/Response 등 다시 정리했습니다!

thymeleaf 에러의 경우 해결했습니다.
원인은 ViewController에서 ProductResponse를 model로 전달하는데, API 명세 통일 작업에서 ProductResponse의 categoryName 필드가 categoryId 필드로 변경되었는데 HTML 문서에서는 변경을 하지 않아 필드 정보를 불러올 수 없던 문제였습니다.
오히려 로컬에서는 왜 실행이 됐는지 모르겠습니다😅

배포 쉘 스크립트는 기존 pr 버전에서 일부 변경이 생겼습니다.
우선 힌트 코드와 달라진 이유는 코드에 코멘트 남기겠습니다.

추가로 가능하면 서비스 서버가 종료되는 시간을 최소화하기 위해 서버가 켜져있는 상태에서 빌드 후 최신 서버로 대체하는 식으로 해야된다고 생각합니다. 그러나 aws 프리티어의 한계로 백그라운드에 서버가 켜져있는 상태에서 빌드할 경우 EC2 인스턴스가 자주 죽어버려 부득이하게 kill process부터 우선 실행 후 빌드하였습니다.

2024-08-03 14:29 UTC, us4c0d3 commented on deploy/deploy.sh
> +JAR_NAME=$(basename $BUILD_PATH)
코드 순서가 일부 달라졌습니다. 이후 사용을 편하게 하기 위해 PATH 등의 변수 설정을 가장 먼저 하도록 했습니다.

2024-08-03 14:29 UTC, us4c0d3 commented on deploy/deploy.sh
> +fi
힌트 코드의 프로세스 종료 과정에서는 아래의 명령어를 사용했습니다.
```sh
$ pgrep -f $JAR_NAME
```
이 경우 인스턴스에서 로그아웃했다가 다시 접속했을 때 PID를 정상적으로 읽지 못하는 경우가 종종 있었습니다. 어차피 배포를 8080포트에서 하기 때문에 `lsof -i:8080`을 이용하였습니다. `-t` 옵션은 이 중 PID 만을 반환합니다.

2024-08-03 14:29 UTC, us4c0d3 commented on deploy/deploy.sh
> +./gradlew bootJar
제공된 코드에서는 빌드과정이 없어 코드 pull 후 바로 스크립트만 실행하여 빌드 후 배포까지 실행하도록 하였습니다.

2024-08-04 17:19 UTC, sang5c approved these changes
마지막 3단계까지 파이팅입니다!

2024-08-04 17:19 UTC, merged