부산대 BE_박수빈 6주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #230
Opened 2024-08-02 03:33 UTC by kuma4188

AWS를 이용해서 배포를 해보았습니다.
원래는 localhost를 이용해서 제 컴퓨터에서만 접속이 가능한데 ,
배포를 했더니 어디서든 접속이 가능했습니다.

# 신기해서 바로 호주에 있는 친구에게 주소를 알려주고 접속해보라고 했는데 , 잘된다고 해서 신기+뿌듯했던것 같습니다.

2024-08-02 03:46 UTC, yoo-jaein requested changes
step2 배포하기까지 고생 많으셨습니다!
코멘트 하나 달았습니다 :)

2024-08-02 03:46 UTC, yoo-jaein commented on README.md
> +- http://3.38.99.249:8080/api/products/list
혹시 지금은 주소가 바뀐걸까요? 접근이 잘 안되어서요..!

2024-08-02 05:01 UTC, kuma4188 commented on README.md
> +- http://3.38.99.249:8080/api/products/list
![image](https://github.com/user-attachments/assets/7c4e9c98-062c-4f12-b29e-1ecee02c8a0f)

제가 실행시킬떄는 git-bash를 이용해서 ssh 접속후 jar파일을 실행키면 저 주소로 접속이 되고 ,
실행 시키지 않으면 주소로 접속이 되지 않습니다. 원래 이게 맞나요?

그렇다면 항상 실행시켜두고 있어야 하는지 궁금합니다.

2024-08-02 14:57 UTC, yoo-jaein commented on README.md
> +- http://3.38.99.249:8080/api/products/list
네 jar 파일을 실행해야 앱이 시작되고 접속이 가능합니다.
과제에 항상 실행되어야 한다는 요구사항은 없지만,
일반적으로 배포하면 앱을 종료하거나 배포에 문제가 없는 이상 쭉 서비스가 제공되어야 합니다.

2024-08-02 15:56 UTC, kuma4188 commented on README.md
> +- http://3.38.99.249:8080/api/products/list
넵 그럼 앱을 계속 켜두도록 하겠습니다!

2024-08-03 05:33 UTC, yoo-jaein approved these changes
step2는 머지하겠습니다!

2024-08-03 05:33 UTC, merged