충남대 BE_박서현 6주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #232
Opened 2024-08-02 04:07 UTC by sseooh

2024-08-03 05:51 UTC, jjongwa requested changes
팀원과 정한 API 명세에 대한 설명(또는 링크), 배포한 서버 주소와 swagger 링크 첨부해서 다시 리뷰 요청해 주세요.!

2024-08-04 01:06 UTC, sseooh commented
> 팀원과 정한 API 명세에 대한 설명(또는 링크), 배포한 서버 주소와 swagger 링크 첨부해서 다시 리뷰 요청해 주세요.!
http://43.201.116.78:8080/swagger-ui/index.html -> swagger 링크
https://www.notion.so/Day-27-824da5a529d340e7886b1ccc55bae4fc -> API 명세 정리
입니다!!

2024-08-04 15:09 UTC, jjongwa requested changes
2단계는 딱히 리뷰할게 없어 보이네요.!
1단게에서 질문 드린 부분에 대한 답과 confilct 해결 후 다시 요청 주시면 바로 머지하겠습니다.!

2024-08-04 15:09 UTC, jjongwa commented on src/main/java/gift/config/WebConfig.java
>      }
각각 어떤 설정들인지 설명 부탁드려요!

allowedOrigins에 3개의 도메인을 넣은 이유,
allowedHeaders가 어디에 사용되는지, 현재의 "*" 설정은 어디까지 커버가 되는지

2024-08-05 01:24 UTC, sseooh commented on src/main/java/gift/config/WebConfig.java
>      }
CORS와 관련된 설정들입니다!

allowedOrigins -> CORS를 허용한 도메인 지정
- localhost:3000 -> 프론트 팀원이 지정 (혹시 몰라서..)
- localhost:8080 -> 로컬 서버
-  43.201.116.78:8080 -> 배포 서버 주소

allowedMethods -> CORS 요청에 대해 허용할 HTTP 메서드

allowedHeaders -> CORS 요청에서 허용한 HTTP 헤더 (*를 이용해서 모든 종류의 헤더를 허용하도록)

allowCredentials -> 자격 증명을 포함한 요청을 허용할지 결정 (인증이 필요한 요청을 처리하기 위함)

2024-08-05 12:32 UTC, jjongwa approved these changes
👍 👍 👍

2024-08-05 12:32 UTC, merged