전남대 BE_김보민 6주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #239
Opened 2024-08-02 05:50 UTC by KBM05haruin30

# 1단계
지금까지 각자 코드를 작성해왔었습니다. 그러다 보니 API 명세서를 작성하기 위해 이야기를 할 때도 시간이 걸렸었습니다. 팀원들과 이야기 하다 보니 제가 과제를 수행하면서 빠진 부분이 있었고, 요청과 응답을 지정하다 보니 DTO를 만들어서 해야겠다는 생각에 시간이 많이 걸렸습니다. 그리고 Controller로 작성을 했고 Form을 사용했었는데 코드를 수정하면서 RestController로 수정하고 API 명세에 나와있는 대로 응답을 위해 컨트롤러, 서비스를 수정했습니다. 코드 하나를 수정하면 다른 부분에서도 수정이 필요하여 시간이 많이 걸렸습니다. 
전체적으로 많이 수정되다 보니 초기에 코드를 잘 작성해야겠다는 생각을 많이 했습니다.
추가로 코드들이 바뀌다 보니 테스트 코드를 수정해야 합니다. 지금은 협업을 위해서 일시적으로 테스트 코드들을 주석 처리 해두었습니다.

2024-08-04 08:47 UTC, Hongdonggeon requested changes
안녕하세요 보민님
미션 잘 구현해주셨습니다! 
간단한 코멘트 남겨놓았습니다
시간 날때 테스트 코드도 같이 고쳐주는게 좋을 것 같아요
api 가 변경되고 메서드가 변경하게 되면 테스트코드가 실패하게 되는게 당연한거고, 테스트코드를 성공하게 만들면서 api를 더 검증할 수 있게 되는거니 수정하시는게 좋을 것 같습니다!

2024-08-04 08:47 UTC, Hongdonggeon commented on src/main/java/gift/controller/OptionController.java
> +            List<OptionResponseDTO> options = optionService.findALlByProductId(productId);
메서드명 신경써주세용

2024-08-04 08:47 UTC, Hongdonggeon commented on src/main/java/gift/service/OrderService.java
> +        removeFromWishlistByOptionId(option.getId());
해당 메서드를 requires_new로 트랜잭션 격리레벨을 변경했지만 적용 안되고 있을거예요! 
removeFromWishListNyOPtionId 메서드가 타 클래스에 있어야 requires_new 가 적용될거예요 
이유에 대해 간략하게 설명드리자면,
`@transactional`이 sping 프록시 기반으로 동작이 되는데요 
같은 클래스에 있기 때문에 프록시 객체가 호출되지 않고 실제 객체가 호출되기 때문이예요

아래와 같은 클래스 구조로 예시를 들어볼게요
- A 컨트롤러
- @Transactional 이 붙은 A서비스 클래스의 a 메서드 
A 컨트롤러에서 a 메서드 호출하게 되면 
A 컨트롤러 -> a 프록시 객체 메서드 호출 -> a 실객체 메서드 호출
위와 같이 동작하거든요! 한번 찾아보시면 도움될거예요

근데 여기서 A 서비스 클래스에 b메서드 (`@Transactional` requries_new) 를 추가하고 a메서드에서 b 메서드를 호출한다고 해볼게요 
그러면 아래와 같이 동작하게 되면서 새로운 트랜잭션이 열리지 않게 됩니다!
A 컨트롤러 -> a 프록시 객체 메서드 호출 -> a 실객체 메서드 호출 -> b 실객체 메서드 호출

2024-08-04 10:48 UTC, KBM05haruin30 commented on src/main/java/gift/controller/OptionController.java
> +            List<OptionResponseDTO> options = optionService.findALlByProductId(productId);
넵 알겠습니다! listOptions 보다는 더 자세히 알기 위해 getOptionsByProductId로 수정하는 것이 더 좋다고 생각합니다. 이와 마찬가지로 다른 메서드들도 메서드명을 보고 기능을 알 수 있도록 수정하겠습니다!

2024-08-04 10:50 UTC, KBM05haruin30 commented on src/main/java/gift/service/OrderService.java
> +        removeFromWishlistByOptionId(option.getId());
감사합니다! 한 번 더 찾아보고 수정하도록 하겠습니다!

2024-08-04 11:54 UTC, KBM05haruin30 commented on src/main/java/gift/controller/OptionController.java
> +            List<OptionResponseDTO> options = optionService.findALlByProductId(productId);
넵 알겠습니다! listOptions 보다는 더 이해하기 쉽게 getAllOptions로 수정하는 것이 더 좋다고 생각합니다. 이와 마찬가지로 다른 메서드들도 메서드명을 보고 기능을 알 수 있도록 수정하겠습니다!

2024-08-04 12:49 UTC, KBM05haruin30 commented on src/main/java/gift/service/OrderService.java
> +        removeFromWishlistByOptionId(option.getId());
멘토님, wishlistService의 `removeWishlistByOptionId` 메서드를 사용하려고 `removeFromWishlistByOptionId`를 새로 만들었었습니다. 다른 클래스에 있어야 requires_new가 적용되므로 `removeFromWishlistByOptionId` 메서드를 지우고 WishlistService안의 `removeWishlistByOptionId` 메서드에 requires_new를 적용시켰습니다. 따로 새로운 클래스를 만들 필요 없이 이렇게 하는 것이 더 좋을 것 같아 했는데 맞게 했는지 궁금합니다.

2024-08-05 14:49 UTC, Hongdonggeon commented on src/main/java/gift/service/OrderService.java
> +        removeFromWishlistByOptionId(option.getId());
네네 잘 하신 것 같아요! 따로 만들어줄 필요없이 wishLIstService에 있는게 적합해보여요

2024-08-05 14:50 UTC, Hongdonggeon approved these changes
안녕하세요 보민님
리뷰 반영하신거 잘 확인했어요!
수고하셨습니다!
머지할게요~

2024-08-05 14:50 UTC, merged