docs: README.md 미션 내용 추가
kakao-tech-campus-2nd-step2/spring-gift-point pull request #246
Opened 2024-08-02 06:28 UTC by pnuece

2024-08-03 23:32 UTC, pnuece commented
### 1단계 - API 명세
* [API 명세서](https://fuchsia-tabletop-6fc.notion.site/API-438e773c1c0d475da1e87b4ef4ef42d8?pvs=74)
  팀 내 API 명세 통일 시 제가 작성한 명세를 기준으로 통일하여 2가지 변경만 발생하였습니다.
  1. [POST] /api/members/register (회원 가입)
  요청: (동일)
  응답: 가입된 회원 ID 및 EMAIL 반환 => 인증 토큰 반환
  2. [POST] /api/products (상품 생성)
  요청: 생성할 상품 정보와 카테고리만 지정 => 옵션도 상품과 함께 생하도록 정보 추가 (상품에는 반드시 1개 이상의 옵션이 존재해야 한다는 제약조건 반영)
  응답: (동일)

2024-08-03 23:38 UTC, pnuece commented
### 2단계 - 배포하기
* [배포 주소: https://pnuece.pnu.app](https://pnuece.pnu.app)
기존 보유중인 Azure 리소스에 Docker를 활용해 배포하였으며, 도메인 및 HTTPS 적용까지 8/30(화)에 완료하여 FE 팀원에게 전달하였습니다.

2024-08-03 23:50 UTC, pnuece commented
### 3단계 - 포인트
* [API 명세서](https://fuchsia-tabletop-6fc.notion.site/API-438e773c1c0d475da1e87b4ef4ef42d8?pvs=74)
포인트 기능 추가를 위해 관리자 API 1개 추가, 기존 API 1개 명세 변경 진행하였습니다.
* 포인트 기능 정의
상품 구매 시 5% 포인트 적립, 포인트는 구매 시 제한 없이 활용 가능
* 관리자 API 추가
  1. [PUT] /api/members/{memberId}/point (회원 포인트 변경)
  요청: 변경할 포인트 (+, -) 모두 가능
  응답: (성공) 200 / (보유한 포인트 보다 차감 포인트가 큰 경우) 400
* 기존 API 명세 변경
  1. [POST] /api/members/{memberId}/point (주문하기)
  요청: 사용할 포인트 값 추가
  응답: (성공) 동일 / (보유한 포인트 보다 차감 포인트가 큰 경우) 400

2024-08-07 15:18 UTC, yoo-jaein requested changes
6주 동안 고생 많으셨습니다!! :)
리뷰 코멘트 확인 부탁드려요

2024-08-07 15:18 UTC, yoo-jaein commented on README.md
> +작성한 API 문서를 기반으로 팀 내에서 지금까지 만든 API를 검토하고 통일하여 변경 사항을 반영한다.
API 명세 잘 작성해주셨습니다!
참고로 실무에서는 API 문서 관리를 위해 swagger 또는 Spring rest docs를 많이 사용합니다.
특히 swagger는 설정하는 것도 간단하니 한번 찾아보시면 좋을 것 같아요~

2024-08-07 15:18 UTC, yoo-jaein commented on README.md
> +지금까지 만든 선물하기 서비스를 배포하고 클라이언트와 연동할 수 있어야 한다.
배포된 서버 확인했습니다!
배포 고생 많으셨습니다.

2024-08-07 15:18 UTC, yoo-jaein commented on README.md
> +### 미션 요구 사항
포인트에 대한 로직이 아직 없는 것 같아요 확인해주세요!

2024-08-08 07:12 UTC, pnuece commented on README.md
> +### 미션 요구 사항
커밋만 하고 푸시를 안해서 방금 진행했습니다..

2024-08-08 07:12 UTC, pnuece commented on README.md
> +지금까지 만든 선물하기 서비스를 배포하고 클라이언트와 연동할 수 있어야 한다.
감사합니다 :)

2024-08-08 07:13 UTC, pnuece commented on README.md
> +작성한 API 문서를 기반으로 팀 내에서 지금까지 만든 API를 검토하고 통일하여 변경 사항을 반영한다.
swagger는 적용해보았고, rest docs의 경우 아직 테스트 코드를 아직 제대로 작성하지 않아 추후 적용해보겠습니다

2024-08-08 09:50 UTC, deactivated-user approved these changes
리뷰 반영된 것 확인했습니다!
추가 코멘트는 참고해주세요.
과제 완주하시느라 고생 많으셨습니다 :)

2024-08-08 09:50 UTC, yoo-jaein commented on src/main/java/gift/service/OrderService.java
> +        member.subPoint(orderRequest.point());
주문에 포인트 로직이 들어가면서 코드가 복잡해지고 있는데 별도의 포인트 서비스 클래스를 만드는 것도 괜찮을 것 같아요.

2024-08-08 09:50 UTC, yoo-jaein commented on src/main/java/gift/service/OrderService.java
> +        member.addPoint((long)(option.getProduct().getPrice() * 0.05));
0.05는 비즈니스에서 중요한 값이니 상수로 선언해두는 것이 좋습니다!

2024-08-08 09:50 UTC, yoo-jaein commented on src/main/java/gift/service/OrderService.java
> +            KakaoMessageTemplate message = new KakaoMessageTemplate("text", "상품 구매가 완료되었습니다",
객체 사용 👍

2024-08-08 09:50 UTC, merged