경북대 BE_이지호 6주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #254
Opened 2024-08-02 06:47 UTC by GitJIHO

카카오 로그인 후 프론트에 jwt토큰을 보내는 방식을 진행하고 수정하여 구현했습니다.
위시리스트에서의 상품별 원하는 수를 의미하던 number 필드를 팀원들과 협의하에 삭제하였습니다. 관련 로직 구현에 공을 쓴 기억이 있어 아쉽지만 나중에 다시 추가할 상황을 대비하여 주석처리 하였습니다.

포인트관련하여 팀원들과 합의한 결과 모든 구매는 포인트로만 할 수 있고, 포인트를 사용하면 모든 주문에 대하여 5프로의 할인을 자동 적용하는 방식의 규칙을 만들었습니다.
또한, 현금영수증은 원하면 입력할 수 있도록 프론트에서 구현하는 방식을 선정하였습니다.
기존 카카오 엑세스 토큰이 속성에 들어있던 방식이 유저가 여러명일 때 대응하지 못하여 USER 엔티티에 엑세스 토큰 필드를 추가하여 유저별 엑세스 토큰을 db에 저장하도록 하였습니다.

어드민 페이지에서는 유저별 포인트를 확인할 수 있고 포인트를 수정하기 위해서는 비밀번호를 입력하도록 하였는데 비밀번호는 일단 카카오 유저를 서버에 회원가입 시킬 때 사용했던 번호를 공용으로 사용하도록 하였습니다.

CORS 오류 관련하여 여러 방법을 시도해보다 현재 방법이 문제가 없이 작동하여 해당 방식으로 진행하였습니다.

모각코 시간에 주로 API 명세를 통일하기 위한 회의를 자주 진행하였고, 통일된 명세를 바탕으로 프론트와 협업하여 수정사항을 보완해나갔습니다.

프론트에서 서버를 https로 열고 현재 제 서버는 http로 구현되어 프로토콜이 다른 문제가 있어 크롬에서 직접 프론트 서버의 보안 연결을 해제하는 방식으로 테스트를 진행하였습니다. 제 서버를 https로 열거나 프론트에서 http로 배포하는 방식 중에 하나를 고민중입니다.

현재 상품, 카테고리 확인, 위시리스트 CRUD, 주문 및 나에게 카카오메시지 전송까지 구현이 되었고 이외의 오류 해결중에 있습니다!

특히 주문 관련하여 여러 종류의 옵션을 다중 선택하는 경우 현재는 주문 생성 api를 옵션 종류별로 여러번 호출하는 방식으로 프론트에서 구현하였는데 백엔드 api를 추가하여 한번에 보내는 방식을 선정할지 해당 방식을 유지할지 팀원들과 회의 및 고민중에 있습니다.

2024-08-03 07:56 UTC, sang5c requested changes
리뷰 확인하고 수정해주세요!  
작성해주신 PR 본문에 따르면, 완성되지 않은 것으로 보이는데 완성되면 다시 리뷰 요청을 진행해주세요~

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/controller/KakaoUserController.java
> +        String jwtToken = tokenService.generateToken(userEmail);
JWT는 Json Web Token입니다.  
JWT Token이라고 표기하면 Json Web Token Token이 됩니다.

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/controller/UserController.java
> +    @GetMapping("/points")
포인트는 별도의 컨트롤러가 없어도 될까요?  
컨트롤러는 어떤 기준으로 나뉘고 있나요?

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/service/UserService.java
> +        return user.getPoint();
파라미터로 받은 User에 대해 getter 호출 후 반환이 목적인데 서비스를 거쳐야만 하는 이유는 무엇인가요?

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/controller/UserController.java
> +    @PostMapping("/points/{point}")
이 URI가 모호하네요. 다른 API와 비교했을때 어떤지, 명확하게 작성되었을지 팀원 분들과 다시 상의해보세요!  
URI는 리소스를 나타내야 합니다.

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/controller/WishController.java
> +//    @PutMapping("/{wishId}")
주석은 관리되지 않을 가능성이 매우 높습니다.

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/dto/UserPointRequest.java
> +public class UserPointRequest {
사용되지 않는 클래스입니다.

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/dto/UserPointResponse.java
> +    Integer point
Integer 타입이 되는게 맞을까요?

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/dto/WishRequest.java
> +//    @Schema(description = "Quantity of the product", example = "5")
주석은 관리되지 않을 가능성이 매우 높습니다.

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/dto/WishResponseForPage.java
> +    Long wishId,
Request, Response에서 Wrapper class 사용이 꼭 필요한지 전체적으로 점검해주세요.

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/entity/User.java
> +    protected User() {
default 생성자 내에 초기화 값이 존재하는 이유는 무엇인가요?  
이 생성자는 언제 사용되나요?

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/entity/User.java
> +//    public void subtractWishNumber(Integer number, Product product) {
주석은 관리되지 않을 가능성이 매우 높습니다.

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/entity/Wish.java
> +//    @NotNull
주석은 관리되지 않을 가능성이 매우 높습니다.

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/repository/WishRepository.java
> +//    @Modifying
주석은 관리되지 않을 가능성이 매우 높습니다.

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/service/UserService.java
> +        if (!kakaoProperties.getDefaultPassword().equals(password)) {
프로퍼티를 통해 비밀번호를 설정하고 제어하는 이유가 무엇인가요?  
고정된 비밀번호를 두고, 관리하는 방식 말고 다른 방법으로는 구현할 수 없을까요?

2024-08-03 07:56 UTC, sang5c commented on src/main/java/gift/service/WishService.java
> +//    public void updateNumber(Long userId, Long wishId, int number) {
주석은 관리되지 않을 가능성이 매우 높습니다.

2024-08-03 07:56 UTC, sang5c commented on src/test/java/gift/repository/WishRepositoryTest.java
> +//    @Test
주석은 관리되지 않을 가능성이 매우 높습니다.

2024-08-03 16:06 UTC, GitJIHO commented on src/main/java/gift/controller/UserController.java
> +    @GetMapping("/points")
point에 별도의 컨트롤러를 두었습니다!

기존에는 어드민 페이지를 제외하고 컨트롤러가 필요한 서비스단에 1:1 매핑을 시켰습니다.

2024-08-03 16:11 UTC, GitJIHO commented on src/main/java/gift/service/UserService.java
> +        return user.getPoint();
생각해보니 도메인 값을 조정하는게 아닌 단순한 getter이기 때문에 서비스단이 필요 없을 것 같네요,,! 삭제했습니다!

2024-08-03 16:12 UTC, GitJIHO commented on src/main/java/gift/controller/UserController.java
> +    @PostMapping("/points/{point}")
앗 해당 메서드는 유저 포인트 어드민 페이지를 만들기 전 임시로 추가한 내용인데 삭제를 까먹었습니다. 삭제했습니다!

2024-08-03 16:13 UTC, GitJIHO commented on src/main/java/gift/dto/UserPointRequest.java
> +public class UserPointRequest {
포인트 관련 DTO request를 일단 만들고 생각했는데 관련 로직이 어드민 페이지에서 실행되도록 구현해서 사용하지 않았네요. 삭제했습니다!

2024-08-03 16:16 UTC, GitJIHO commented on src/main/java/gift/dto/UserPointResponse.java
> +    Integer point
null이 될 이유가 없기 때문에 int가 맞을 것 같습니다..!

2024-08-03 16:24 UTC, GitJIHO commented on src/main/java/gift/dto/WishResponseForPage.java
> +    Long wishId,
NotNull 제약조건이 없는 경우 Wrapper class를 사용하지 않는 방향으로 수정해봤습니다!

2024-08-03 17:20 UTC, GitJIHO commented on src/main/java/gift/entity/User.java
> +    protected User() {
습관적으로 추가했는데 찾아보니 JPA를 위한 기본 생성자였음을 알게 되었습니다. 초기화 값을 제거했습니다!

2024-08-04 15:48 UTC, GitJIHO commented on src/main/java/gift/service/UserService.java
> +        if (!kakaoProperties.getDefaultPassword().equals(password)) {
관리자 페이지이기 때문에 유저별로 다른 비밀번호를 두기보다는 관리자만 알 수 있는 고정된 비밀번호를 사용하는 방식을 택하였습니다.

다른 방법을 생각해보았을 때는 어드민페이지에 로그인 기능을 추가하여 유저 필드에 관리 등급을 두는 방식으로 관리자를 구별하는 방식을 둘 수 있을 것 같습니다..!

혹시 다른 좋은 방법이 있을까요?!

2024-08-04 15:49 UTC, GitJIHO commented
백엔드 구현은 완료하였고 프론트 작업 디테일한 부분 마무리 중이라 끝나면 배포 링크와 함께 pr 재요청 드리도록 하겠습니다!!

2024-08-05 18:13 UTC, sang5c approved these changes
완주 축하드리고 고생하셨습니다:)

2024-08-05 18:13 UTC, sang5c commented on src/test/java/gift/repository/WishRepositoryTest.java
> +//    @Test
안지워진 주석이 있네요~

2024-08-05 18:13 UTC, sang5c commented on src/main/java/gift/service/UserService.java
> +        if (!kakaoProperties.getDefaultPassword().equals(password)) {
말씀하신 방법이나, 관리자 계정은 어드민에서만 사용되기에 관리자 계정을 분리해서 따로 받는 방법도 있겠네요!

2024-08-05 18:13 UTC, merged