충남대 BE_이택 6주차 과제 step2
kakao-tech-campus-2nd-step2/spring-gift-point pull request #255
Opened 2024-08-02 06:51 UTC by LeeTaek2T

2024-08-03 05:18 UTC, LeeTaek2T commented
로컬에서는 테스트 및 kakaoService(api명세서에 따라 현재는 사용하지 않습니다)가 잘 돌아가는데 서버에서는 Bean오류 및 테스트 오류가 나 삭제를 하였습니다. 먼저 원인을 알아보겠습니다..!

2024-08-04 10:52 UTC, ksy90101 requested changes
테스트 코드가 왜 주석이 되었을까요?
일단 2단계는 간단하니 3단계에서 피드백 수정해주시면 될거 같습니다~

2024-08-04 10:52 UTC, ksy90101 commented on src/main/java/gift/WebConfig.java
> +      .allowedOriginPatterns("*") //추가한 부분
필요없는 주석은 제거하면 좋을거 같습니다.

2024-08-04 10:52 UTC, ksy90101 commented on src/test/java/gift/Controller/MemberControllerTest.java
> +//package gift.Controller;
왜 테스트 코드가 모두 주석이 되었나요?

2024-08-04 10:52 UTC, ksy90101 approved these changes
👍

2024-08-04 10:52 UTC, merged

2024-08-05 06:53 UTC, LeeTaek2T commented on src/test/java/gift/Controller/MemberControllerTest.java
> +//package gift.Controller;
배포할 때 문제가 생겼어서 잠깐 주석처리를 했었습니다.
주석처리 해제 하겠습니다!

2024-08-05 06:53 UTC, LeeTaek2T commented on src/main/java/gift/WebConfig.java
> +      .allowedOriginPatterns("*") //추가한 부분
네!