경북대 BE_김민주 6주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #266
Opened 2024-08-02 07:21 UTC by minju26

- `3단계 - 포인트` 과제 제출합니다!

2024-08-04 07:31 UTC, gongdongho12 requested changes
저도 벌써 마지막 PR이라니 너무 시간이 빠르게 지나갔네요 😢 
전체적으로 이런 레벨의 프로젝트를 작업하실 수 있도록 성장하신 부분이 정말 대단하신 것 같습니다!

PR에서 첨언드리면
- README.md 에 업데이트 사항이 빠진 것 같습니다!
- 포인트는 업데이트 기준값에 따른 업데이트가 아니라 값이 단순히 한두명 업데이트는 문제없이 처리할 수 있을 건데요
같은사람이 여러 풀에서 업데이트 되면 값이 오류가 발생할 가능성이 높습니다
- 관련해서 멀티스레드로 한 유저에대한 포인트 사용 로직 테스트 추가하고 검증해보시면 좋을 것 같습니다!

2024-08-04 07:31 UTC, gongdongho12 commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +//}
테스트 주석처리 한 이유가 있을까요?
만약 로직 변경으로 동작을 안한다면 동작을 같이 맞춰주는게 맞습니다!

2024-08-04 07:31 UTC, gongdongho12 commented on src/test/java/gift/service/OrderServiceTest.java
> +    }
주문 테스트 잘 작성해 주셨는데요
재고 1개고 스레드 2개에서 동시에 주문하는 경우 하나가 exception 나는 방식으로 테스트가 추가되면 좋을 것 같습니다!

2024-08-04 07:31 UTC, gongdongho12 commented on src/main/java/gift/domain/Member.java
> +    private Integer point;
멤버에 포인트 넣어준 부분은 좋은데요!
포인트 어떻게 적립되었는지 히스토리를 관리하는게 좋지 않을까요?

2024-08-04 07:31 UTC, gongdongho12 commented on src/main/java/gift/domain/Member.java
> +    private Integer point;
웹 두개에서 포인트가 잘못 업데이트 되었을 가능성이 있는데요

이부분도 테스트 추가해서 확인해보시면 포인트 수치가 정상적이지 않을 것 같아요!

2024-08-04 07:31 UTC, gongdongho12 commented on src/main/java/gift/service/OrderService.java
> +        member.savePoint(pointToSave(option.getProduct(), orderRequest.quantity()));
주문이 취소되면 이 포인트는 복구될 수 있을까요?

2024-08-06 04:29 UTC, minju26 commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +//}
미리 넣어둔 data.sql의 데이터에 맞춰서 짜둔건데 프론트와 협업하면서 data.sql이 잠시 변경되어서 빠른 배포를 위해 주석처리 했습니다!

2024-08-07 09:08 UTC, minju26 commented on src/test/java/gift/repository/MemberRepositoryTest.java
> +//}
2단계 pr에서 동작하도록 수정하여 올렸습니다

2024-08-08 07:09 UTC, minju26 commented
@gongdongho12 
피드백 반영했습니다!

### 수정사항
- 포인트 어떻게 저장되었는지 정보 저장
- 동시 주문시 재고 부족에 대한 테스트
- README 업데이트
- 주문 취소 경우에 대한 데이터 복구 테스트

### 질문‼️ 
주문 취소 경우에 대하여, `order`메서드에 `@Transactional`을 붙였습니다.
`@Transactional`이 붙은 메서드에서는 예외가 발생하면 트랜잭션 전체가 롤백되는걸로 알고있는데,
포인트와 수량에 대해 테스트를 해보니 `order`메서드 내에서 수량 차감`option.subtract()`과 포인트 차감`member.deductPoint()`의 순서에 따라 테스트 결과가 달라졌습니다.
예를 들어 [수량 차감] -> [포인트 차감] 순으로 진행하도록 했을 때,
 [포인트 차감]에서 에러가 발생한 경우 **[수량 차감] 에서 차감 된 수량은 롤백 되지 않고 그대로** 남아있었습니다.
여러 방법으로 수정해보았으나 해결하지 못해서 질문 남김니다..!🥹

2024-08-12 04:29 UTC, closed without merging