전남대 BE_박진화 6주차 과제(Step1)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #278
Opened 2024-08-02 08:11 UTC by Jinhwa-Park

잘 부탁드립니다..

2024-08-04 11:50 UTC, pkeugine requested changes
안녕하세요 진화님,
몇 가지 리뷰 남겨보았으니 한 번 확인부탁드려요.
충돌 해결이 잘 안된 것 같아 일단 request changes 보냅니다.
PR 올리고 리뷰 요청하기 전에 이런 부분은 한 번 확인해주시면 좋을 것 같아요.

2024-08-04 11:50 UTC, pkeugine commented on src/main/java/gift/controller/OptionController.java
> +        }
GlobalExceptionHandler 를 사용하지 않고 이렇게 예외처리를 하는 이유가 궁금해요.

2024-08-04 11:50 UTC, pkeugine commented on src/test/java/gift/service/KakaoServiceTest.java
> +>>>>>>> e3b9ef38d18104514aa1d0951ff1a098ff9a093f
git 충돌 해결이 잘 안된 것 같아요.

2024-08-04 11:50 UTC, pkeugine commented on src/test/java/gift/service/OrderServiceTest.java
> +>>>>>>> e3b9ef38d18104514aa1d0951ff1a098ff9a093f
여기도 잘 된것 같지가 않네요

2024-08-04 11:50 UTC, pkeugine commented on src/main/resources/schema.sql
> +/*CREATE TABLE IF NOT EXISTS member (
schema 파일을 주석처리하신 이유가 궁금해요.

2024-08-04 11:50 UTC, pkeugine commented on src/main/resources/data.sql
> +-- INSERT INTO wish (member_id, product_id, quantity) VALUES (1, 1, 1);
불필요한 부분은 제거해도 괜찮을 것 같아요.

2024-08-04 12:04 UTC, Jinhwa-Park commented on src/main/java/gift/controller/OptionController.java
> +        }
API 통일 하느라 너무 정신이 없는데 자꾸 에러가 나서 후딱 치우려고 새로 적은거라서 handler를 안썼어요

2024-08-04 12:05 UTC, Jinhwa-Park commented on src/test/java/gift/service/KakaoServiceTest.java
> +>>>>>>> e3b9ef38d18104514aa1d0951ff1a098ff9a093f
이것도 배포준비하면서 Test 코드를 잘 못들여다봤나봐요. 배포가 너무 어렵더라구요..

2024-08-04 12:06 UTC, Jinhwa-Park commented on src/main/resources/schema.sql
> +/*CREATE TABLE IF NOT EXISTS member (
API 통일하면서 DB 오류가 계속 나서 H2 콘솔 들어가서 테이블을 봤더니 Schema 파일이 존재해서 문제가 된 것 같더라구요. 그래서 확인 차 주석처리 했었습니다!

2024-08-04 12:06 UTC, Jinhwa-Park commented on src/main/resources/data.sql
> +-- INSERT INTO wish (member_id, product_id, quantity) VALUES (1, 1, 1);
넵 알겠습니다.

2024-08-07 12:03 UTC, pkeugine approved these changes
이만 머지하겠습니다.

2024-08-07 12:03 UTC, merged