강원대 BE_박지희 6주차 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #293
Opened 2024-08-02 08:42 UTC by peacefullyquietly

2024-08-04 12:15 UTC, jaymarystella requested changes
안녕하세요
배포 스크립트만 확인부탁드릴게요~

2024-08-04 12:15 UTC, jaymarystella commented on README.md
> +
> 인스턴스 내에 쉘 스크립트 작성 후 배포 자동화도 해두었습니다!

인스턴스에 넣어두시면 제가 스크립트를 확인할 수가 없습니다. 그리고 남겨주신 ip로 접근이 안되는데 서버가 내려간듯합니다.

2024-08-04 13:06 UTC, peacefullyquietly commented
<img width="432" alt="스크린샷 2024-08-04 오후 9 44 17" src="https://github.com/user-attachments/assets/9d64e92f-7550-4012-a7f8-888cf99fcc37">
<img width="710" alt="스크린샷 2024-08-04 오후 9 59 05" src="https://github.com/user-attachments/assets/67e3960f-8ccb-481f-b736-06b4403365c7">


이렇게 추가해두었습니다! 혹시,, 깃 파일에 넣어야 하는건가요?

2024-08-05 15:24 UTC, jaymarystella commented
> 이렇게 추가해두었습니다! 혹시,, 깃 파일에 넣어야 하는건가요?

그건아닌데 미션이 배포스크립트 작성이라 딱히 궁금증이 없으시면 괜찮습니다

2024-08-05 15:24 UTC, jaymarystella approved these changes
안녕하세요
2단계까지 고생많으셨습니다. 마지막 단계에서뵐게요

2024-08-05 15:29 UTC, merged