경북대 BE_김동현 6주차 과제 (2-3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #302
Opened 2024-08-02 08:52 UTC by donghyuun

제출합니다. 3단계는 완성되었고, 배포 파일이 아직 완성 안되었는데 완성 후 PR 요청드리겠습니다!

2024-08-04 13:55 UTC, MangKyu approved these changes
안녕하세요 동현님! 먼저 리뷰가 조금 늦어서 죄송합니다!
이번 미션은 스펙 협의를 팀원들과 하는 부분이 상당히 중요한데요, API 스펙에 대해 협의하면서 어떠한 변경들이 생겼고, 어떠한 부분들을 새롭게 느끼셨는지 궁금하네요! 개발자라는 직군이 코딩만 하는 사람들이 아니라, 비즈니스 문제를 개발로 해결하는 사람들이다보니까요! 이를 위해 다른 사람들과 협업하는 자세와 이해가 상당히 중요한 것 같네요ㅎㅎ

변경하면 좋을 것 같은 부분들 코멘트 드렸으니, 한번 확인 부탁드리겠습니다! 🙏

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/category/Category.java
> +    private String color;
스펙 맞춘 부분 👍

2024-08-04 13:55 UTC, MangKyu commented on .github/workflows/deploy.yml
> +name: Deploy Spring Boot Application
github-actions 적용까지 훌륭하십니다 💯

2024-08-04 13:55 UTC, MangKyu commented on .github/workflows/deploy.yml
> +    runs-on: ubuntu-latest
일반적으로 고정된 os 버전을 활용합니다! 그래야 os 버전업의 변경과 그에 따른 적합성을 확인하여 영향을 피할 수 있어서요ㅎㅎ

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/category/CategoryRestController.java
> +    @Operation(summary = "카테고리 목록 조회")
문서화도 스펙으로 통일하기로 결정한 것인가요~?

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/category/CategoryRestController.java
> +    public ResponseEntity createCategories(
전반적으로 네이밍 포함하여 변경하시느라 고생 많으셨습니다ㅎㅎ 
다만, API 명세만 통일하면 내부 구현은 통일하지 않아도 될 것 같은데요! 이렇게 바꾸는 것이 좋은 것 같아서 변경하신 것인지 궁금하네요!

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/member/Member.java
> +    public void chargePoint(int point) {
메서드 네이밍 직관적이게 잘 작성하신 것 같네요! 💯

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/option/Option.java
> +    protected Option() {
protected 변경 👍

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/option/dto/request/OptionRequest.java
> +public record OptionRequest(
DTO 빼신 부분은 왜 이렇게 결정하게 되셨는지 궁금하네요ㅎㅎ

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/option/OptionService.java
> +        if (quantity <= 0) {
해당 부분은 비즈니스 정책으로 볼 수도 있고, 입력 데이터 정책으로도 볼 수 있을 것 같아요!
이러한 부분은 일반적으로 차감하는 값이 1보다 작음을 기대하기 어려우므로, 입력 데이터로 검증해서 Valid로 처리해도 좋을 것 같네요!

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/order/OrderRestController.java
> +    public ResponseEntity order(
```suggestion
    public ResponseEntity<Void> order(
```

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/order/ReceiptType.java
> +public enum ReceiptType {
오 추가 기능도 생겼군요ㅎㅎ

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/order/dto/request/OrderRequest.java
> +    Boolean hasCashReceipt,
여기도 null 검사가 필요할 것 같네요! Boolean이라 null이 들어갈 수 있을 것 같아요ㅎㅎ

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/point/PointRestController.java
> +    @PostMapping("/api/points")
POST로 충전을 기대하기는 어려워서요ㅎㅎ 다음과 같이 path 정하는 것도 괜찮았을 것 같네요! 
```suggestion
    @PostMapping("/api/points/charge")
```

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/product/Product.java
> +    public ProductResponse toProductResponse() {
domain은 비즈니스 정책을 담당하는 클래스인데, 계층 간의 변환을 담당하는 DTO를 참조하게 되어 버렸네요 😢 DTO에서 domain을 알도록 하면 어떨까요~?

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/product/dto/request/ProductRequest.java
> +    @NotBlank(message = "이름이 입력되지 않았습니다")
에러 메시지까지 꼼꼼한 작성 💯

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/wish/WishRestController.java
> +        @Parameter(description = "로그인 유저 정보") @Login LoginInfo loginInfo
LoginInfo 부분은 중복되는 것 같은데, 줄일 수 있는 방법이 없을지 찾아보면 좋을 것 같네요!

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/domain/wish/WishService.java
> +        if (!wishRepository.existsById(wishId)) {
API가 일관성 있도록, 존재하지 않을 경우에 에러를 던지지 않고 무시하면 더욱 좋습니다ㅎㅎ

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/global/config/WebConfig.java
> +            public void addCorsMappings(CorsRegistry registry) {
cors 설정 💯

2024-08-04 13:55 UTC, MangKyu commented on src/main/java/gift/global/exception/user/MemberNotFoundException.java
> +public class MemberNotFoundException extends RuntimeException {
Member로 일관성 있게 반영 👍

2024-08-04 13:55 UTC, MangKyu requested changes
Request Changes로 변경해둡니다!

2024-08-05 15:58 UTC, MangKyu approved these changes
안녕하세요! 6주차의 미션까지 고생 정말 많으셨습니다! 처음 리뷰를 보았던 것이 엊그제 같은데, 벌써 6주나 지났네요ㅎㅎ 최종 리뷰 요청까지 열심히 반영하고 달려주셔서 감사합니다 :bow:
마지막으로 어떻게 조금 더 많은 도움을 드릴 수 있을까 고민을 했는데, 최종적으로 프로젝트를 다시 보고 피드백을 드릴 수 있는 부분을 드리면 좋을 것 같아서 시간 내어 정리해 보았어요!
이미 충분히 잘 개발해주셨는데 보다 좋은 개발자가 되시는 데 도움을 드리고 싶어서 작성한 것이니, 이를 학습 또는 개선의 방향 등으로 잡고 봐주시면 좋을 것 같습니다ㅎㅎ

- Optional의 활용
    - 프로젝트 많은 부분에서 Optional을 활용해주고 계시는데, Optional이 개발된 의도는 무엇이고 올바르게 활용하고 있는지 공부해보시면 좋을 것 같습니다
    - Optional의 isPresent는 대표적인 안티 패턴으로 여겨지는데, 해당 부분이 활용되는 곳이 보이네요
    - 다만 전반적으로는 잘 적용해주셔서 이미 잘 알고 계시는 것 같다고 생각은 하지만 혹시 몰라 다시 한번 적습니다
- `@Autowired`의 사용
    - 스프링은 생성자가 1개인 경우, 생성자에 `@Autowired`를 붙이지 않아도 자동 주입을 지원해줍니다
    - `@Autowired`는 스프링 프레임워크가 제공하는 애노테이션이며, 이는 우리의 코드가 스프링이라는 프레임워크에 결합된다는 것을 의미하기도 합니다
    - 스프링은 POJO 기반의 애플리케이션을 지향하고자 하는 관점에서 시작된 프레임워크입니다
    - 따라서 불필요하게 `@Autowired`를 사용하지 않음으로써, 프레임워크로부터 까지도 순수하게 만들 수 있다면 더욱 바람직하다고 볼 수 있습니다
- 트랜잭션
    - `CategoryService`에서 `createCategories` 시에 중간에 예외가 발생하면 원자성이 깨질 수 있습니다
    - 이를 위해 `@Transactional`을 활용하여 하나의 작업으로 묶어주는 과정이 필요합니다
    - 트랜잭션에 대해서 공부하여 원자성있는 처리 방법에 대해 고민해보시면 좋을 것 같습니다
- DTO의 활용
    - Service 계층은 비즈니스 로직을 처리하는 계층입니다
    - 그런데 현재 구조 상으로는 클라이언트로부터의 입력과 출력에 대한 데이터가 Service 계층까지 활용되는 것을 볼 수 있습니다
    - 그렇다면 DTO를 격리시킬 것인지, 아니면 효율적인 개발을 위해 DTO의 침투를 허용할 것인지 등에 대해서도 고민해보시면 좋을 것 같습니다
- Filter와 Interceptor
    - Filter는 서블릿 범위, Interceptor는 스프링 컨테이너 범위입니다
    - 인증되지 않은 사용자라면 스프링 컨테이너 내부에 침투하기도 전에 필터에서 먼저 거르는 것이 보다 안전할 수 있습니다
    - 따라서 필터와 인터셉터에 대한 차이를 이해하고, 그에 따른 선택을 하는 것이 필요합니다
    - 여기서도 마찬가지로 인터셉터라서 문제가 되는 것이 아니고, 인터셉터를 선택했다면 그에 따른 마땅한 이유가 있어야 함을 의미합니다
    - 또한 HTTP Status 중에서 Forbidden과 Unauthorized에 대해서도 살펴보시면 좋을 것 같네요
- 연관 관계
    - 연관 관계는 객체 간의 관계를 맺어주어, 객체 간의 협력을 통해 변경에 유연한 개발을 할 수 있도록 도와줍니다
    - 하지만 이로 인해 N+1 문제와 같은 예상치 못한 동작이 생기기도 하고, 이로 인해 시스템 장애가 발생하기도 합니다
    - N+1과 같은 문제는 어떻게 해결할 수 있는지, 연관 관계의 장점과 단점은 무엇인지 한번 정리해보시면 좋을 것 같습니다
- 테스트 코드
    - 우리는 개발을 하면서 수시로 리팩터링을 반복해야 코드를 유지보수하기 좋은 상태로 유지할 수 있습니다
    - 지속적인 리팩터링에서 안정성을 보장받을 수 있는 방법은 테스트(수동이든 자동이든) 밖에 없습니다
    - 테스트는 우리의 구현이 올바른지 검증해주는 훌륭한 도구인데, 현재의 테스트는 구현이 바뀌면서 함께 깨지게 됩니다
    - 따라서 어떻게 하면 코드가 변경되어도 테스트는 변경없이 우리의 코드가 안전함을 보장해줄 수 있을지 고민해보면 좋을 것 같습니다
    - 또한 이력서 등에는 구체화된 수치를 작성하는 것이 중요한데, 테스트 커버리지 등은 이러한 수치화를 위한 훌륭한 수단이 될 수 있습니다

리뷰 요청드린 부분이 있는데, 시간이 늦어져서 바로 머지하도록 하겠습니다!
마지막까지 정말 고생많으셨습니다! 앞으로도 좋은 일들만 가득하시길 응원합니다ㅎㅎ 화이팅하세요!

2024-08-05 15:58 UTC, merged

2024-08-07 13:09 UTC, donghyuun commented on .github/workflows/deploy.yml
> +    runs-on: ubuntu-latest
참고하겠습니다 ㅎㅎ 조언 감사합니다!

2024-08-07 13:10 UTC, donghyuun commented on src/main/java/gift/domain/category/CategoryRestController.java
> +    @Operation(summary = "카테고리 목록 조회")
넵 문서화도 프론트엔드와 얘기하여 명세서 파일의 설명을 그대로 사용하기로 했습니다!

2024-08-07 13:14 UTC, donghyuun commented on src/main/java/gift/domain/category/CategoryRestController.java
> +    public ResponseEntity createCategories(
넵 API 응답을 통일하면서, 설명 메시지를 포함하지 않고, 필요한 경우 데이터"만" 넘겨주는 방식을 사용하게 되었는데요,
성공의 경우, 대부분 200 코드를 사용하기 때문에 굳이 HttpStatus 를 넘겨주어 응답을 생성하는 커스텀 메서드를 사용할 필요가 없다고 생각했습니다.
그래서 간단하게 구현하였습니다!, 나중에 응답의 구성이 복잡해지면 그때 커스텀 메서드를 사용하면 좋을 것 같습니다!

2024-08-07 13:14 UTC, donghyuun commented on src/main/java/gift/domain/member/Member.java
> +    public void chargePoint(int point) {
감사합니다!!

2024-08-07 13:17 UTC, donghyuun commented on src/main/java/gift/domain/option/dto/request/OptionRequest.java
> +public record OptionRequest(
Request, Response 라는 단어의 의미가 비즈니스 객체와는 다른, "데이터 전달을 위한 타입"이라는 것을 설명한다고 생각했습니다.
컨트롤러와 클라이언트간의 상호작용이 Request,Response 니까요.. 그래서 DTO 문구가 필요 없다고 생각하여 빼게 되었고, 빼니 글자 수가 줄어 사용하기 편한 것 같습니다!

2024-08-07 13:20 UTC, donghyuun commented on src/main/java/gift/domain/option/OptionService.java
> +        if (quantity <= 0) {
아 이 부분은 이미 입력 데이터 검증에서 @Valid 로 처리되고 있는데요!, 제가 불필요하게 넣은 것 같습니다ㅎㅎ..
비즈니스 로직에서는 비즈니스 정책에 대해서 검사하는게 좋을 것 같네요!

2024-08-07 13:23 UTC, donghyuun commented on src/main/java/gift/domain/order/OrderRestController.java
> +    public ResponseEntity order(
아하 찾아보니 단순 ResponseEntity 형식으로 반환할 경우 본문 타입을 특정하지 않고 반환할 수 있는 경우에도 사용한다고 하네요..
명시적으로 Void 를 표기하는게 좋은 것 같습니다. 감사합니다!!

2024-08-07 13:23 UTC, donghyuun commented on src/main/java/gift/domain/order/dto/request/OrderRequest.java
> +    Boolean hasCashReceipt,
수정하겠습니다!!

2024-08-07 13:25 UTC, donghyuun commented on src/main/java/gift/domain/point/PointRestController.java
> +    @PostMapping("/api/points")
생각해보니 POST 가 충전의 의미와는 먼 것 같습니다. 프론트엔드와 협의해보겠습니다. 말씀 감사합니다 ㅎㅎ

2024-08-07 13:28 UTC, donghyuun commented on src/main/java/gift/domain/wish/WishRestController.java
> +        @Parameter(description = "로그인 유저 정보") @Login LoginInfo loginInfo
이 부분은 당연하게 중복될 수 밖에 없다고 생각했었는데, 고민해봐야 할 사안인 것 같습니다. 말씀 감사합니다!!

2024-08-07 13:32 UTC, donghyuun commented on src/main/java/gift/domain/wish/WishService.java
> +        if (!wishRepository.existsById(wishId)) {
답변 감사합니다!!
저는, 클라이언트가 항상 유효한 wishId 에 대해 요청을 보내야 하는게 맞다고 생각해서, 그렇지 않은 경우에 대해서는
비정상적인 요청이라고 생각되어 에러를 발생시키게 되었는데, 이 부분도 고민해보겠습니다!!

2024-08-07 13:35 UTC, donghyuun commented on src/main/java/gift/domain/product/Product.java
> +    public ProductResponse toProductResponse() {
저는 dto -> entity, entity -> dto 변환 메서드가 각 주체(dto, entity) 에 구현되어 있는 것이 편하다고 생각했는데, 엔티티가 dto 를 참조하는 부분에 대해 올바른지 다시 생각해봐야 할 것 같습니다. 감사합니다!!

2024-08-07 13:49 UTC, donghyuun commented
안녕하세요 멘토님 조금 늦게 마지막 인사 드리게 되었습니다!
사실 멘토님께 리뷰를 받기 전, 이미 멘토님의 블로그를 자주 참고하고 있었습니다 ㅎㅎ

해당 블로그의 관리자가 멘토님이라는 것을 멘토님이 블로그 주소를 공유해주셔서 처음 알게되었습니다.
특히 멘토님이 작성하신 Spring 예외 처리 방법을 읽고, 출처를 명시하여 제 블로그에 정리했던게 기억이 나네요!

이렇게 봴 줄은 생각도 못했습니다 ㅎㅎ.

공부를 하며 모르는 것을 많이 여쭤보았는데, 이 과정에서 MangKyu 멘토님께서 항상 정성을 다해
리뷰해주신다는 것을 느낄 수 있었습니다. 현업에 계심에도 시간을 내주셔서 제 코드를 살펴봐주셨던 것이 저에겐
정말 많은 도움이 되었습니다.

지금까지 기능에만 집중하여 구현을 하다가, 카테캠을 통해 어떻게 하면 기능과 정제된 코드, 두 마리의 토끼를 잡을 수 있을지에 
대해 많이 생각하고 공부할 수 있었습니다.

현재 카테캠 말고도 다른 프로젝트를 진행하고 있는데, 이 프로젝트에도 멘토님의 조언과, 카테캠에서 배운 많은 것들을 적용할 수 있었습니다.

올 한해 가장 많이 성장했던 6주가 아니었나 싶습니다.

step3 를 진행하기 전에 멘토님께서 말씀하신 부분, 마지막 코멘트 내용, 반영하지 못한 부분들(트랜젝션 등)에 대해 공부를 한 후 
step3 에 더 성장한 모습으로 임하려 합니다.

다시 한번 MangKyu 님께 정말 감사하다는 말을 전하고 싶습니다.
항상 행복하시길 바라겠습니다. 멘토님도 화이팅입니다! 감사합니다!!!!!!!

2024-08-07 13:55 UTC, MangKyu commented on src/main/java/gift/domain/option/dto/request/OptionRequest.java
> +public record OptionRequest(
저도 비슷하게 생각하고, 실무에서 DTO라는 키워드를 네이밍에 넣지 않고 있습니다ㅎㅎ 좋은 판단인 것 같아요!

2024-08-07 13:56 UTC, MangKyu commented
그 동안 너무 고생 많으셨습니다! 앞으로도 지금처럼 열심히 하셔서 훌륭한 개발자가 되시기를 응원합니다:)