전남대 BE_박민규 6주차 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #309
Opened 2024-08-02 09:04 UTC by ps9319

2024-08-03 13:18 UTC, dc-choi requested changes
안녕하세요 민규님!

CORS에 대한 처리도 같이 잘 처리된거 같네요!

혹시 배포된 주소를 확인할 수 있을까요?

2024-08-03 13:55 UTC, ps9319 commented
> 혹시 배포된 주소를 확인할 수 있을까요?

넵!! http://13.211.28.153:8080 입니다

2024-08-04 10:56 UTC, dc-choi requested changes
민규님! 지금 확인하고 있는데 서버 접근이 안되네요 확인 부탁드려요!

2024-08-04 11:00 UTC, ps9319 commented
> 민규님! 지금 확인하고 있는데 서버 접근이 안되네요 확인 부탁드려요!

client_loop: send disconnect: Broken pipe 라고 하면서 서버가 꺼졌었네요... 왜 자꾸 꺼지는지 모르겠지만 다시 켰습니다!!

2024-08-04 13:05 UTC, dc-choi approved these changes
넵 정상동작하는거 확인했습니다!

다음 step으로 넘어가주시면 됩니다!

2024-08-04 13:05 UTC, merged