강원대 BE_안승환 6주차 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #311
Opened 2024-08-02 09:27 UTC by Awhn

2024-08-05 15:29 UTC, jaymarystella requested changes
안녕하세요 
올려주신 배포스크립트 동작이 제대로 되는거맞나요?
배포를 하셨으니 어떠한 경로로 됐을거긴한데 뭔가 이상한거같아서 확인만 부탁드립니다.

2024-08-05 15:29 UTC, jaymarystella commented on deploy.sh
> +BUILD_PATH = $(ls /repository/spring-gift-point/build/*.jar)
빌드를 따로 해서 올려주시는과정은 수동으로 진행하시는건가요?

2024-08-05 15:29 UTC, jaymarystella commented on deploy.sh
> +CURRENT_PID = $(pgep -f $JAR_NAME)
pgrep의 오타인거같아서 동작을 안할것같습니다.

2024-08-05 15:29 UTC, jaymarystella commented on deploy.sh
> +DEPLOY_JAR = $DEPLOY_PATH$JAR_NAME
JAR_NAME이 안보이는거같네요

2024-08-05 15:50 UTC, Awhn commented on deploy.sh
> +BUILD_PATH = $(ls /repository/spring-gift-point/build/*.jar)
넵 빌드는 수동으로 진행하였습니다.

2024-08-05 15:55 UTC, Awhn commented
넵, 풀 리퀘스트에 올라간 스크립트는 클론 코딩 시간에 주어진 스크립트를 옮겨쓴 것으로 잘못 올라갔습니다. AWS에서 카테캠 리포를 가져와 수행하면서 따로 스크립트를 작성하였습니다. 수정한 코드를 옮겨와 다시 커밋하였습니다.

2024-08-07 00:22 UTC, jaymarystella approved these changes
고생많으셨습니다. 다음단계에서 뵐게요~

2024-08-07 00:23 UTC, merged