경북대 BE_김은선 6주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #316
Opened 2024-08-02 11:10 UTC by eunsoni

안녕하세요 멘토님

1단계 리뷰요청 드립니다~!

1단계에서 프론트엔드분들과 함께 api path와 response, request 데이터를 결정하였습니다.
그래서 프로젝트 전체적으로 변경 사항이 많습니다.

* 변경사항
1. 추가된 컨트롤러(파일이름을 ~NewController로 설정)들이 회의결과 새로 생성된 api입니다. 기존 컨트롤러를 삭제하지 않은 이유는 백엔드와 프론트엔드 과제 내용(구현하는 기능이나 페이지)이 달라서 기존 컨트롤러를 바꿨을 때 이번 협업에 해당되지 않는 기능(ex 상품 수정 등)도 많기 때문입니다
2. 서비스에 각종 메서드 추가 : 새로 생긴 컨트롤러는 회의 결과에 따라서 데이터 종류와 형식이 다르기 때문에 추가했습니다.
3. response, request 추가 : 프론트엔드와 데이터를 주고 받을 때 사용합니다.
4. Swagger UI에서 이번 협업 과제에 사용되는 컨트롤러는 @Tag 어노테이션에서 name 속성에 '[협업]' 이라고 표기해두었습니다.
5. 3단계 진행 전 기본적인 point 엔터티, 레포지토리, 서비스 추가(백엔드에서 배포하면 프론트엔드분들이 통합되는지 확인해본다고 하셔서 오늘까지 point 구현을 마치기로 해서 3단계를 미리 진행하게 되었습니다)
![스크린샷 2024-08-02 200725](https://github.com/user-attachments/assets/e3491026-32f4-4674-9dfa-71eefd873ef9)

2024-08-03 06:35 UTC, gongdongho12 reviewed
@eunsoni 한번 rebase 적용해주세요!

2024-08-03 07:23 UTC, eunsoni commented
@gongdongho12
기존에 로컬에 원격계정을 fetch 해놔서
git checkout main
git reset --hard upstream/eunsoni
순서대로 진행했는데
카카오/eunsoni에 0단계가 merge 되기 전의 프로젝트(원격계정을 fetch해놨던 시점에 초기 프로젝트 = 카카오/main에 있는 프로젝트)가 main(로컬)에 불러와졌습니다

0단계 merge된 버전으로 reset되어야하는데 어떤 부분에서 잘못한 것인지 잘 모르겠습니다..ㅜ 

![스크린샷 2024-08-03 155141](https://github.com/user-attachments/assets/d94edc08-cb50-41fa-95a6-346518b6fa12)
![image](https://github.com/user-attachments/assets/e977541f-701a-4be3-b3ea-a86cb500a5f4)

2024-08-03 07:46 UTC, gongdongho12 requested changes
1단계 작업 고생하셨습니다
리뷰 드린 내용중에 중복된 부분은 추가로 언급드리지는 않았는데 찾아서 업데이트 해 주세요!

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/controller/MemberNewController.java
> +public class MemberNewController {
현재 엔드포인트를 정리해서 보면
MemberController는 `/member`
MemberRestController `/member`
MemberNewController `/api/members`

인 것이자나요

결국 RestController와 RequestPath는같은데 같이 구분 해 주는게 좋지 않을까요?
그리고 신규 API를 제공해야 되서 Path를 나누는 경우에 같은 Path 보다는 `api/v2/members` 정도로 나눠 보면 좋을 것 같습니다

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/controller/MemberNewController.java
> +public class MemberNewController {
API는 스웨거에서 보는 방식인데 각각 구분을 정확하게 하는게 좋아서 구분의 기본 단위인 Path로 정리해보면 좋을 것 같습니다

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/controller/MemberRestController.java
> +        }
현재 Swagger로 API 문서를 만들고 있자나요
그러면 타입이 Map인 경우 값이 정상적으로 노출되지 않게 되요
차라리 타입을 이런식으로 다르게 리턴하고 싶다면, ControllerAdvice에서 에러에 대한 부분만 포함해서 리턴하는게 좋지 않을까요?

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/controller/OptionController.java
> +}
아무 기능이 없는데 컨트롤러는 왜 만들어진걸까요?
만약 사용 안하는 API 라면 지우는게 좋을 것 같습니다

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/controller/OptionNewController.java
> +        return ResponseEntity.ok(optionService. getOptionsByProductId(productId));
IDE에 Auto Formatting이 되어있어야 할 것 같습니다
메서드 호출 사이에 공백이 들어있네요

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/controller/OrderNewController.java
> +    }
`@Transaction`을 여기에 달아두기 보다는 서비스 내부에 달아두는게 좋은데요
처리를 서비스에서 하는 기능인데 만약 저 기능을 다른곳에서 쓰더라도 트랜잭션은 동일한 레벨에서 작용해야 하니까요!
물론 다른 동작과 저 기능이 Controller에서 순서대로 무결성 있도록 작동해야 한다면 컨트롤러에 대한 역할이 아니라 Service의 역할이 되므로 이 부분도 결국 서비스 내에 `@Transaction`적용이 되겠죠?

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    private OptionService optionService;
혹시 두개만 final인 이유가 궁금합니다
이런 부분도 컨벤션으로 공통적으로 가져가는게 좋아요!

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/entity/Option.java
> +        }
생성자 내부에 Validation을 넣기 보다는 별도 Validator 어노테이션이나 메서드를 만들어서 사용하는게 좋지 않을까요?

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/filter/JwtTokenFilter.java
> +        System.out.println("at resolveToken mathod : " + bearerToken);
Sysout으로 출력하면 나중에 로그 레벨이나 필터링 하기 어려운데요
Logger객체를 사용해서 정리해보면 어떨까요? 스프링에서 기본적으로 제공하는게 있을거에요

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/handler/GlobalExceptionHandler.java
> +    }
http에 보면 html만 받을지, json도 받을지 정리할 수 있는데요
이 부분은 html만 적용하는 부분이라 한번 체크해보시면 좋을 것 같습니다

2024-08-03 07:46 UTC, gongdongho12 commented on src/main/java/gift/service/KakaoService.java
> +                return new TokenResponse(accessToken, refreshToken);
이런 부분도 TokenResponse의 생성자를 response로 받으면 깔끔하게 처리 가능하지 않을까요?

2024-08-03 07:46 UTC, gongdongho12 commented on src/test/java/gift/RestTemplateTest.java
> +    }
이부분은 테스트가 미완성된 것 같은데요
어떤 내역을 테스트 한 걸까요?

2024-08-03 07:47 UTC, gongdongho12 commented
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/f0e167a4-d429-41c2-87b3-b059e5eca0b4">
아직 안된 것 같아요!
지금 eunsoni 브랜치에 업데이트 되어야 할 내용이 반영되지 못한 느낌입니다

2024-08-03 07:51 UTC, eunsoni commented
> <img alt="image" width="1303" src="https://private-user-images.githubusercontent.com/1717874/354802977-f0e167a4-d429-41c2-87b3-b059e5eca0b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NzE1NjUsIm5iZiI6MTcyMjY3MTI2NSwicGF0aCI6Ii8xNzE3ODc0LzM1NDgwMjk3Ny1mMGUxNjdhNC1kNDI5LTQxYzItODdiMy1iMDU5ZTVlY2EwYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMDc0NzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODc1OGQzNTU0ZDZmZTVhNjJiNTU1Y2NmMDA2OTViODk5ODk1ZDQxNjMzZmRhMzA0ZGYwNGExM2VmNWE2YzJkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.REQf0WIH4DX_FD_AWSpPxMEjfdKXo_wv-qORZBaaF5E"> 아직 안된 것 같아요! 지금 eunsoni 브랜치에 업데이트 되어야 할 내용이 반영되지 못한 느낌입니다

맞습니다 충돌 해결 중에 있어요!!

2024-08-03 09:06 UTC, gongdongho12 approved these changes
토요일이기두 하고, 리뷰 내용은 3단계 PR에서 확인하겠습니다!

2024-08-03 09:10 UTC, merged

2024-08-04 06:59 UTC, eunsoni commented on src/main/java/gift/controller/MemberNewController.java
> +public class MemberNewController {
기존 서비스는 
/api/members/v2/
/members/v2/
/view/v2/members

새로 협업한 서비스는 프론트엔드와 정한 /api/members/
이렇게 변경했습니다

2024-08-04 07:16 UTC, eunsoni commented on src/main/java/gift/controller/OptionController.java
> +}
지웠습니다!

2024-08-04 07:25 UTC, eunsoni commented on src/main/java/gift/controller/OptionNewController.java
> +        return ResponseEntity.ok(optionService. getOptionsByProductId(productId));
File > Settings > Tools > Actions on Save Reformat code
로 설정해두었습니다!

2024-08-04 07:26 UTC, eunsoni commented on src/main/java/gift/controller/OrderNewController.java
> +    }
넵 서비스 내부에 @Transaction 달도록 할게요!!

2024-08-04 07:38 UTC, eunsoni commented on src/main/java/gift/controller/ProductController.java
> +    private OptionService optionService;
넵 통일해놓았습니다!

2024-08-04 08:35 UTC, eunsoni commented on src/main/java/gift/service/KakaoService.java
> +                return new TokenResponse(accessToken, refreshToken);
이 부분은 json 타입을 string 객체로 새로 정의해서 생성자에 파라미터로 주고 있는데
직접 생성자에 파라미터로 주는 방식으로 변경하였습니다

2024-08-04 08:44 UTC, eunsoni commented on src/test/java/gift/RestTemplateTest.java
> +    }
앗 이부분은 제이슨님 라이브코딩강의 때 그대로 따라하면서 공부했던 부분이라서 삭제하도록 하겠습니다

2024-08-04 08:52 UTC, eunsoni commented on src/main/java/gift/entity/Option.java
> +        }
이 부분은 option데이터 디비 저장 테스트에서 서로 다른 메세지로 validation 위반한 경우들을 세분화하면 좋을 것 같다고 해주셔서 추가한 내용입니다!
다시 테스트에서 메세지로 세분화해서 검사하는 부분을 삭제하는 것이 좋을까요?

.hasMessageContaining("Quantity must be greater than 0");
.hasMessageContaining("Quantity must be less than or equal to 100,000,000");
.hasMessageContaining("Unique index or primary key violation");

2024-08-04 09:01 UTC, gongdongho12 commented on src/main/java/gift/entity/Option.java
> +        }
그러면 생성자에 그대로 넣기 보다는 메서드로 처리하는게 좋지 않을까요?

2024-08-04 10:14 UTC, eunsoni commented on src/main/java/gift/entity/Option.java
> +        }
오 그렇군요 처리해두었습니다!!

2024-08-04 11:17 UTC, eunsoni commented on src/main/java/gift/filter/JwtTokenFilter.java
> +        System.out.println("at resolveToken mathod : " + bearerToken);
log 레벨 설정하고 sysout 대신 로그 적용해두었습니다!

2024-08-04 11:40 UTC, eunsoni commented on src/main/java/gift/handler/GlobalExceptionHandler.java
> +    }
JSON 응답을 처리하는 예외 핸들러 추가했습니다!!

2024-08-04 14:36 UTC, eunsoni commented on src/main/java/gift/controller/MemberRestController.java
> +        }
LoginResponse를 추가해서 이것을 반환하도록 설정하고 로그인이 유효하지 않은 경우는 프론트에서 처리하였습니다!