충남대 BE_이은경 6주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #318
Opened 2024-08-02 12:14 UTC by pkyung

## 과제 진행 사항
### 포인트 
- [x] member 필드에 point 추가, 필요한 메서드 추가
- [x] point api cr 생성
- [x] 관리자 페이지에서 포인트 생성 및 조회 가능

- 주문 과정에서 usedPoint 필드를 추가하여 주문 시에 멤버가 갖고 있는 포인트를 차감합니다. 
- 포인트 충전은 관리자 페이지에서 진행합니다.

2024-08-04 10:50 UTC, ksy90101 requested changes
마지막이네요 👍 
세세한 부분에 대한 리뷰를 남겼으니 한번 확인해주세요~

2024-08-04 10:50 UTC, ksy90101 commented on src/main/java/gift/controller/PointController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
포인트를 변경하는것 같은데 POST가 맞을가요?

2024-08-04 10:50 UTC, ksy90101 commented on src/main/java/gift/dto/OrderRequest.java
> +        int usedPoint
여기도 validate가 필요할거 같습니다.

2024-08-04 10:50 UTC, ksy90101 commented on src/main/java/gift/dto/PointRequest.java
> +        int point
여기도 validate가 필요할거 같습니다.

2024-08-04 10:50 UTC, ksy90101 commented on src/main/java/gift/service/PointService.java
> +    public int pointCharge(PointRequest request, Member member) {
여기서는 DTO로 하지 않은 이유가 무엇인가요?

2024-08-04 10:55 UTC, pkyung commented on src/main/java/gift/controller/PointController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
put으로 변경하겠습니다.

2024-08-04 10:57 UTC, ksy90101 commented on src/main/java/gift/controller/PointController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
아울러 과연 points가 REST API의 관점에서 리소스인가를 고민해보면 좋을거 같습니다.

member의 상태이니 member가 리소스이고, 그에 대한 상태가 될거 같은데.

members/point와 같은 URL은 고민해보셨을까요?

2024-08-04 10:57 UTC, pkyung commented on src/main/java/gift/dto/OrderRequest.java
> +        int usedPoint
네 추가하겠습니다.

2024-08-04 10:59 UTC, pkyung commented on src/main/java/gift/service/PointService.java
> +    public int pointCharge(PointRequest request, Member member) {
controller에서 반환을 하지 않아서 그렇게 했는데 생각해보니 void로 해도 될 것 같습니다!

2024-08-04 14:19 UTC, pkyung commented on src/main/java/gift/controller/PointController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
저 또한 포인트가 멤버의 필드로 들어가기에 url이 멘토님께서 말씀하신 것처럼 /api/members/points가 되어야하지 않을까 라는 생각을 했었습니다. PointService에서도 memberRepository만 가져오기에 memberService에서 담당할 수 있지 않나? 라는 의문도 들었습니다. 
팀원들과 api 명세를 하는 과정에서 이렇게 정해졌던 것 같습니다. 잘 못 생각했던 것 같습니다.

2024-08-05 02:09 UTC, ksy90101 commented on src/main/java/gift/controller/PointController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
정답이 존재하진 않으니깐요~
팀원들과 소통이 되었다면 괜찮을거 같습니다~

2024-08-05 02:12 UTC, ksy90101 requested changes
마지막 피드백이 될거 같네요~
간단한 피드백을 남겼으니 확인해주세요!

2024-08-05 02:12 UTC, ksy90101 commented on src/main/java/gift/model/Member.java
> +    public void chargePoint(int usingPoint) {
여기서 usingPoint가 음수가 들어오면 어떻게 될까요?

2024-08-05 02:12 UTC, ksy90101 commented on src/main/java/gift/model/Member.java
> +    private int point;
마지막으로 한번 Point를 VO로 만들어 보면 어떨까요?

2024-08-05 02:12 UTC, ksy90101 commented on src/main/resources/static/js/point.js
> +            'Authorization': `Bearer ${token}`
여기도 Content-Type이 있어야 하지 않을까요?

2024-08-05 02:12 UTC, ksy90101 commented on src/main/resources/static/js/point.js
> +    }).then(response => {
한번 fetch하는걸 공통 로직으로 만들어보면 어떨까요?
중복 코드들이 존재하는거 같아요.

2024-08-05 02:12 UTC, ksy90101 commented on src/main/java/gift/dto/PointRequest.java
> +public record PointRequest(
디폴트 값을 지정해봐도 좋을거 같긴 하네요.

2024-08-05 02:12 UTC, ksy90101 commented on src/main/java/gift/controller/PointController.java
> +        return ResponseEntity.status(HttpStatus.OK).build();
내려줄 데이터가 없을땐 204 no_content를 많이 사용합니다.

2024-08-06 01:35 UTC, pkyung commented on src/main/java/gift/model/Member.java
> +    public void chargePoint(int usingPoint) {
이 메서드를 사용하는 부분에서 validation을 설정하긴했으나 여기서도 처리하도록 수정하겠습니다.

2024-08-06 01:39 UTC, pkyung commented on src/main/resources/static/js/point.js
> +            'Authorization': `Bearer ${token}`
네 추가하겠습니다.

2024-08-06 01:40 UTC, pkyung commented on src/main/java/gift/controller/PointController.java
> +        return ResponseEntity.status(HttpStatus.OK).build();
네 수정하겠습니다!

2024-08-06 01:45 UTC, pkyung commented on src/main/java/gift/model/Member.java
> +    private int point;
네 만들어보겠습니다.

2024-08-06 02:53 UTC, pkyung commented on src/main/java/gift/controller/PointController.java
> +        return ResponseEntity.status(HttpStatus.OK).build();
넵 확인했습니다.

2024-08-06 02:53 UTC, pkyung commented on src/main/java/gift/model/Member.java
> +    private int point;
네 만들어보겠습니다.

2024-08-06 03:09 UTC, pkyung commented on src/main/java/gift/dto/PointRequest.java
> +public record PointRequest(
네 지정해보겠습니다.

2024-08-06 03:09 UTC, pkyung commented on src/main/resources/static/js/point.js
> +    }).then(response => {
도전해봤는데 쉽지 않았습니다...

2024-08-06 03:22 UTC, ksy90101 approved these changes
차후 VO에 대해서 좀더 고민해보시면 좋을거 같습니다~
그동안 고생 많으셨어요!

2024-08-06 03:22 UTC, ksy90101 commented on src/main/java/gift/model/Point.java
> +    private int value;
왜 point_value가 되었는지... ㅎㅎㅎ

2024-08-06 03:22 UTC, ksy90101 commented on src/main/java/gift/model/Point.java
> +    private int value;
VO는 불변을 유지하는편이라서 final을 쓰는게 좋을거 같아요.

2024-08-06 03:22 UTC, ksy90101 commented on src/main/java/gift/model/Point.java
> +        this.value += usingPoint;
새로운 VO인 new Point를 쓰는게 더 좋을거 같습니다.

2024-08-06 03:22 UTC, merged