강원대 BE_김병수 6주차 과제 (step2)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #323
Opened 2024-08-02 23:19 UTC by GamJaDo

2024-08-04 12:13 UTC, jaymarystella requested changes
안녕하세요
2단계는 배포미션인데 스크립트가 diff에 없는것같네요
이 부분만 확인주시면 될것같습니다

2024-08-04 12:13 UTC, jaymarystella commented on src/main/java/gift/config/WebConfig.java
> +                .allowCredentials(true);
ip바 바뀌게 되거나 다수의 서버를 운용할때 어떤문제가 생길까요?

2024-08-04 12:13 UTC, jaymarystella commented on src/main/java/gift/adminController/ProductAdminController.java
> +    @PostMapping("/delete/{productId}")
예전 미션의 내용이지만 delete, edit 네이밍은 mapping에 포함이 되어있으므로 생략하시는게 좋습니다.

2024-08-05 03:17 UTC, GamJaDo commented on src/main/java/gift/adminController/ProductAdminController.java
> +    @PostMapping("/delete/{productId}")
html에서 form은 get과 post만 지원해서 URL로 구분하려고 했던 의도였습니다...
```htmlc

````
찾아보니 form 밑에 이런 식으로 숨겨서 보내고
put, delete 메서드를 form에 사용할 수 있도록 `HiddenHttpMethodFilter`를 등록하면 됐었습니다.

2024-08-05 03:18 UTC, GamJaDo commented on src/main/java/gift/config/WebConfig.java
> +                .allowCredentials(true);
- ip 주소가 바뀌면 allowedOrigins에 적혀있는 주소를 다시 수동적으로 변경해야 할 것입니다.
- 다수의 서버를 운영한다 해도 저기에 여러 ip 주소를 수동적으로 추가 해야 해서 번거로울 것 같습니다.

- 그러한 점들을 해결하려면 ip 주소 사용 대신 도메인 주소를 사용합니다.
- 그리고 도메인 주소가 변경되더라도 직접 코드를 열어 수정하는 것 단 환경변수설정해서 관리하는데  옳을 것 같습니다.
- 다수의 서버 같은 경우는 여기서 코드로의 해결보다는 다른 외부적인 게이트웨이를 사용해야 할 것 같습니다.

2024-08-05 15:31 UTC, jaymarystella approved these changes
고생많으셨습니다
다음단계 진행해주세요~

2024-08-05 15:31 UTC, merged