충남대 BE_김해경 6주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #326
Opened 2024-08-03 08:23 UTC by HaegyeongKim01

과제 제출합니다!

2024-08-05 01:21 UTC, Hyeon9mak requested changes
안녕하세요 해경님! 마지막 단계 잘 진행해주셨어요.
마무리 의미로 간단하게 테스트 코드 하나만 추가해주시면 좋을거 같아요 😄

2024-08-05 01:21 UTC, Hyeon9mak commented on src/main/java/gift/vo/Member.java
> +
비즈니스 로직을 Member 객체 내부에 잘 심어주셨네요 👍

2024-08-05 01:21 UTC, Hyeon9mak commented on src/main/java/gift/vo/Member.java
> +
관련한 테스트 코드도 생기면 더 좋겠는데요? 🤔

2024-08-05 17:17 UTC, HaegyeongKim01 commented on src/main/java/gift/vo/Member.java
> +
넵 추가했습니다! 감사합니당

2024-08-06 01:18 UTC, Hyeon9mak approved these changes
안녕하세요 해경님! 6주간 고생 많으셨어요.
그간 남겨드린 코멘트들이 도움이 되셨길 바라면서
마지막 미션 approve 하겠습니다! 👍

2024-08-06 01:18 UTC, merged