경북대 BE_김은선 6주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #327
Opened 2024-08-03 08:46 UTC by eunsoni

과제 제출을 위한 pr입니다..!
1단계 피드백 반영하면서 계속 업데이트할 예정입니다.
* 2단계 진행 사항
쉘스크립트 작성 완료(추후 코드 사진 업데이트 예정)

2024-08-03 09:09 UTC, gongdongho12 requested changes
1단계 머지후에 완료되면 태그주세요!

2024-08-03 09:09 UTC, gongdongho12 commented on README.md
> +* 서버와 클라이언트의 Origin이 달라 요청을 처리할 수 없는 경우를 해결 : CORS 설정
배포스크립트와
CORS 설정은 빠진 것 같아요!

2024-08-03 09:09 UTC, gongdongho12 commented on README.md
> +* 서버와 클라이언트의 Origin이 달라 요청을 처리할 수 없는 경우를 해결 : CORS 설정
이부분 반영되면 태그주세요!

2024-08-04 15:06 UTC, eunsoni commented on README.md
> +* 서버와 클라이언트의 Origin이 달라 요청을 처리할 수 없는 경우를 해결 : CORS 설정
@gongdongho12 
넵 반영하였습니다!

2024-08-04 15:11 UTC, gongdongho12 requested changes
2단계 확인했습니다
배포에 사용될 쉘스크립트 업데이트 부탁드려요!

2024-08-04 15:11 UTC, gongdongho12 commented on src/main/java/gift/config/CorsConfig.java
> +        };
CORS 확인했습니다!
AllowHeader를 *로 쓰면 보안에 취약할 수 있는데, 직접 반영한 Authorize 헤더랑 content/type 정도만 허용하면 어떨까요?

2024-08-04 15:11 UTC, gongdongho12 commented on src/main/java/gift/controller/MemberRestController.java
> +        if ("admin@kakao.com".equals(email) && "admin".equals(password)) {
이 부분은 추후 별도로 가면 좋겠네요!

2024-08-04 15:28 UTC, eunsoni commented on src/main/java/gift/config/CorsConfig.java
> +        };
넵 변경해두었어요!

2024-08-04 15:30 UTC, eunsoni commented
> 2단계 확인했습니다 배포에 사용될 쉘스크립트 업데이트 부탁드려요!

쉘스크립트는 https://github.com/kakao-tech-campus-2nd-step2/spring-gift-point/pull/327#issue-2446247678 여기 사진 파일 올려두었습니다!

2024-08-04 15:58 UTC, gongdongho12 commented
@eunsoni 저거도 PR에 반영해주세요

2024-08-04 16:02 UTC, eunsoni commented
@gongdongho12 
pr에 반영하는 게 혹시 .sh 파일을 프로젝트에 업데이트 하고 commit 하라는 말씀이실까요?

2024-08-04 16:04 UTC, gongdongho12 commented
넵넵

2024-08-04 16:12 UTC, eunsoni commented
아아 프로젝트에 추가해놓고 쓰는 거군요...ㅎㅎㅎ
script폴더에 deploy.sh 푸시했습니다!

2024-08-05 03:53 UTC, gongdongho12 approved these changes
3주차에 리뷰 내용 반영해주세요!

2024-08-05 03:53 UTC, merged

2024-08-05 04:01 UTC, eunsoni commented
@gongdongho12 
멘토님 기존에 피드백 주신 내용은 업데이트 한 것 같습니다!
3주차에 반영할 2주차 추가 피드백은 아직 안 올라온 것이 맞을까요?

2024-08-05 04:31 UTC, gongdongho12 commented
앗 2주차는 저게 끝입니다

2024-08-05 04:31 UTC, gongdongho12 commented
앗 2주차는 저게 끝입니다