경북대 BE_정성훈 6주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #330
Opened 2024-08-03 09:58 UTC by zzoe2346

2024-08-04 18:19 UTC, sang5c requested changes
생각해볼 부분에 리뷰 남겼습니다.  
리뷰 확인하시고 수정해주세요~

2024-08-04 18:19 UTC, sang5c commented on src/main/java/gift/service/MemberService.java
> +    public Long findMemberIdByKakaoEmail(String email) {
이름은 find인데 저장을 수행하면 메서드를 사용하는 사람이 사이드 이펙트를 인지하기 어렵습니다.  
추가로
- 파라미터는 카카오 이메일이 아니어도 되는 것으로 보이는데 메서드명에 Kakao가 꼭 들어가야 할지
- `findMemberIdByKakaoEmail`가 올바른 이름인지 확인해주세요.

2024-08-04 18:19 UTC, sang5c commented on src/main/java/gift/entity/Point.java
> +        int discountedPrice = (int) (0.95 * totalPrice);
외부에서 discountedPrice를 계산해서 파라미터로 전달하는 것과, 내부에서 계산하는 것은 어떤 차이가 있을까요?  
추가로, 외부에서 메서드 선언만 보고 유추하기로는 전달한 price만큼 balance가 감소하는 것으로 보입니다.

2024-08-04 18:19 UTC, sang5c commented on src/main/java/gift/entity/Point.java
> +    public Point() {
default 생성자를 public으로 열고, 내부에 초기화 코드를 넣는 방식은 개인적으로 지양하는 편입니다.  
entity에서 default 생성자는 JPA에서 사용될 수 있도록 만들어 두는 편이기에, 실제로 코드가 사용되는지 알 수 없어 혼란을 주고, 의도를 명확히 나타내지 못합니다.  

default 생성자는 protected로 변경하고, balance를 받아 생성하는 생성자를 만들면 어떨까요?

2024-08-04 18:19 UTC, sang5c commented on src/main/java/gift/interceptor/AuthInterceptor.java
> +    private String validateAndExtractToken(HttpServletRequest request, HttpServletResponse response) {
이름은 validate인데 내부에서 response 변경과, 값 반환이 이루어지네요.

2024-08-04 18:19 UTC, sang5c commented on src/main/java/gift/interceptor/AuthInterceptor.java
> +    private boolean isRequestMethodOption(HttpServletRequest request, HttpServletResponse response) {
isXxx는 단순히 값을 비교 후 true/false 반환을 수행할 것으로 추측됩니다.  
값 변경이 이루어지는 부분이 숨어있고 이름이 역할을 나타내주지 못하네요!

2024-08-04 18:19 UTC, sang5c commented on src/main/java/gift/interceptor/AuthInterceptor.java
> +        request.setAttribute("memberId", tokenService.getMemberId(token));
interceptor에서 값을 넣고 argument resolver에서 값을 꺼내 사용하면 코드 추적이 어렵습니다.  
interceptor와 resolver는 어떤 이유로 분리된 상태로 로직을 수행하나요?

2024-08-04 18:19 UTC, sang5c commented on src/main/java/gift/service/OrderService.java
> +        OrderResponse orderResponse = saveOrder(orderRequest);
orderResponse가 사용되는 시점은 38번 라인이네요. 사용되는 쪽에 가까이 있으면 읽기 편할 것 같습니다.

2024-08-04 18:19 UTC, sang5c commented on src/main/java/gift/service/MemberService.java
> +        memberRepository.getReferenceById(memberId)
어떤 이유로 getReferenceById를 사용하셨고, findById와는 어떤 차이가 있을까요?

2024-08-04 18:19 UTC, sang5c commented on src/test/java/gift/entity/PointTest.java
> +}
end of line 경고가 발생하네요~

2024-08-04 18:19 UTC, sang5c commented on src/test/java/gift/controller/api/PointControllerTest.java
> +}
여기도 eol입니다.

2024-08-05 02:28 UTC, zzoe2346 commented on src/test/java/gift/entity/PointTest.java
> +}
경고 해소하겠습니다!

2024-08-05 02:28 UTC, zzoe2346 commented on src/test/java/gift/controller/api/PointControllerTest.java
> +}
마찬가지로 경고 해소하겠습니다!

2024-08-05 02:46 UTC, zzoe2346 commented on src/main/java/gift/service/MemberService.java
> +    public Long findMemberIdByKakaoEmail(String email) {
`findOrSaveMemberAndGetMemberIdByEmail`  이 메스드 내부에서 동작하는 키워드들이 꼭 들어가도록 이름을 만들어 보았습니다. 제 개인적인 느낌으로는 전 보다는 딱 보고 뭔일이 일어나는지 알도록 만들어진거 같은데... 너무 조잡한것은 아닌가 싶기도 하고 ㅜ

2024-08-05 02:50 UTC, zzoe2346 commented on src/main/java/gift/entity/Point.java
> +        int discountedPrice = (int) (0.95 * totalPrice);
아! 멘토님 말씀처럼 외부만 보면 그런 오해가 생길수 있을것 같습니다. 개선 해보겠습니다.

2024-08-05 03:26 UTC, zzoe2346 commented on src/main/java/gift/entity/Point.java
> +    public Point() {
default 생성자에 함부로 임의의 초기화 코드를 지양하는 이유를 너무 상세히알려주셔서 감사드립니다!!! 

의도 전달에 있어서도 따로 생성자를 만들어주는게 훨씬 좋은거 같습니다. 

단지 무의식적으로 또한 단순히 JPA가 default생성자를 요구한다만 생각하고 있었는데 그런 디테일까지 고려할 수 있는게 놀라운것 같습니다.

2024-08-05 05:46 UTC, zzoe2346 commented on src/main/java/gift/interceptor/AuthInterceptor.java
> +    private boolean isRequestMethodOption(HttpServletRequest request, HttpServletResponse response) {
추측한 내용이 맞도록 수정하겠습니다

2024-08-05 05:48 UTC, zzoe2346 commented on src/main/java/gift/interceptor/AuthInterceptor.java
> +    private String validateAndExtractToken(HttpServletRequest request, HttpServletResponse response) {
개선해보겠습니다

2024-08-05 05:50 UTC, zzoe2346 commented on src/main/java/gift/service/OrderService.java
> +        OrderResponse orderResponse = saveOrder(orderRequest);
넵 멘토님 개선해보겠습니다.

2024-08-05 06:11 UTC, zzoe2346 commented on src/main/java/gift/service/MemberService.java
> +        memberRepository.getReferenceById(memberId)
바로 엔티티가 반환되는 메서드가 있네? 하는 정도로 주의 하지 않고 사용한거 같습니다. 찾아보니
`findById` 는 데이터베이스에 실제로 조회 쿼리를 실행하고, `Optional` 형태로 반환합니다.
`getReferenceById` 데이터베이스 조회를 즉시 수행하지 않고, 해당 엔티티의 프록시 객체를 반환합니다. lazy loading과 같은거 같습니다. 

현재 코드에서는 `getReferenceById`할 이유가 없어 보입니다. 무조건 데이터베이스를 통해 조회를 해야하기 때문 입니다. 또한, `getReferenceById`를 쓰면 데이터베이스에 엔티티가 없는 경우 `EntityNotFoundException`를 발생하게 되는데 이것보다 제가 직접 만들어 놓은 `MemberNotFoundException`으로 예외를 던지도록 하는것이 더 유지보수관점에서 좋을거 같습니다. `findById`를 사용하도록 변경하겠습니다.

2024-08-05 07:56 UTC, zzoe2346 commented on src/main/java/gift/interceptor/AuthInterceptor.java
> +        request.setAttribute("memberId", tokenService.getMemberId(token));
적절한 역할과 책임을 부여한것인가?.... 으로 고민해보앗습니다. 제 생각에는

**Intercepter**: 컨트롤러 가기전에 오는 요청들의 인가 관련 헤더를 검사 하는역할. 헤더가 유효한 형식인지, 헤더의 값(토큰)이 유효한 토큰인지만 확인하는 역할.

**HandlerMethodArgumentResolver**:  컨트롤러로 오는 요청에 있는 값을 꺼내서 컨트롤러에서 에너테이션을 활용하여 깔끔한 코드를 활용하게 하기위한 역할.  

로 생각해 보니 인터셉터에서 멤버 id를 요청에 set 시키는것이 어색해 보였습니다. 그래서 MemberIdArgumentResolver에서 TokenService를 활용해 헤더값을 추출하여 토큰의 memberId를 직접 추출해 @MemberId 를 변수에 붙였을때 memberId를 반환하도록 수정 해보았습니다.

그런데 이러니 WishTest에서 테스트가 실패하였는데 여태껏 MemberIdArgumentResolver에서...

2024-08-05 17:44 UTC, sang5c approved these changes
고생 많으셨습니다 :)  

마지막 리뷰 남겼으니 확인해주세요!

2024-08-05 17:44 UTC, sang5c commented on src/main/java/gift/service/MemberService.java
> +    public Long findOrSaveMemberAndGetMemberIdByEmail(String email) {
ByEmail은 파라미터로 충분히 나타내고 있습니다.

2024-08-05 17:44 UTC, sang5c commented on src/main/java/gift/service/MemberService.java
> +    public Long findOrSaveMemberAndGetMemberIdByEmail(String email) {
메서드명에 세 개의 동사가 포함되어 있습니다. (find, save, get)  
메서드가 너무 많은 일을 하거나 너무 구체적인 이름을 지었다고 느껴집니다.

2024-08-05 17:44 UTC, sang5c commented on src/main/java/gift/entity/Point.java
> +    public void subtractBalance(int discountedPrice) {
할인이 되었는지 안되었는지는 이 메서드 내에서는 알 수 없습니다. discountedPrice 변수명이 어색하네요.

2024-08-05 17:45 UTC, merged