충남대 BE_이택 6주차 과제 Step3
kakao-tech-campus-2nd-step2/spring-gift-point pull request #332
Opened 2024-08-03 11:21 UTC by LeeTaek2T

2024-08-05 07:22 UTC, ksy90101 requested changes
간단한 피드백을 남겼습니다~ 확인해주세요~

2024-08-05 07:22 UTC, ksy90101 commented on src/main/java/gift/Controller/PointController.java
> +  }
과연 Point를 리소스로 볼수 있을까요?
상태가 아닐까 생각이 드는데요.

그렇다면 member의상태라고 생각이 들고.

상태는 생성하는게 아니라 수정하는게 아닐까 생각이 듭니다.

2024-08-05 07:22 UTC, ksy90101 commented on src/main/java/gift/DTO/Member.java
> +  public void addPoint(int point) {
인자로 들어오는 point가 음수면 어떻게 되나요?

2024-08-05 07:22 UTC, ksy90101 commented on src/main/java/gift/DTO/Member.java
> +      throw new IllegalAccessException();
예외 메시지를 작성해주세요!

2024-08-05 07:22 UTC, ksy90101 commented on src/main/java/gift/DTO/Member.java
> +  private int point;
point를 VO로 만들어 보면 어떨까요?

2024-08-05 07:22 UTC, ksy90101 commented on src/main/java/gift/DTO/Orders.java
> +    this.usedPoint = usedPoint;
Member의 point를 VO로 만든다면 여기도 같은 재사용이 될거 같네요.

2024-08-05 07:22 UTC, ksy90101 commented on src/main/java/gift/ResponseDto/RequestPointDto.java
> +public class RequestPointDto {
record로 만들어도 되지 않을까요?

2024-08-05 07:22 UTC, ksy90101 commented on src/main/java/gift/ResponseDto/ResponsePointDto.java
> +public class ResponsePointDto {
여기도 record

2024-08-05 08:16 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Member.java
> +      throw new IllegalAccessException();
네! 알겠습니다

2024-08-05 08:40 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Member.java
> +  private int point;
저는 VO를 비슷한 것을 모은 하나의 패키지라고 생각합니다.
member의 email과 password는 단 한가지 역할을 가지고 있고 VO로 가지지 않는 것처럼 point도 해당 멤버가 가지고 있는 point자체를 의미하고 다른 것들은 가지지 않아 변수로 만들었습니다.
혹시 VO로 만들라고 하시는 이유가 있을까요?

2024-08-05 08:40 UTC, LeeTaek2T commented on src/main/java/gift/ResponseDto/RequestPointDto.java
> +public class RequestPointDto {
네! record로 만드는게 훨씬 좋은것 같습니다!

2024-08-05 08:40 UTC, LeeTaek2T commented on src/main/java/gift/ResponseDto/ResponsePointDto.java
> +public class ResponsePointDto {
네! 반영하겠습니다

2024-08-05 08:41 UTC, ksy90101 commented on src/main/java/gift/DTO/Member.java
> +  private int point;
1. 재사용성
2. 불변 유지
3. 타입 명시
가 있습니다.

2024-08-05 15:34 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Member.java
> +  public void addPoint(int point) {
프론트엔드와 확실히 정하지 않아 음수가 들어올 수도 있으니 이에 대한 처리를 해주겠습니다

2024-08-05 15:38 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Orders.java
> +    this.usedPoint = usedPoint;
네! 반영하겠습니다

2024-08-05 15:38 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Member.java
> +  private int point;
VO에 대해 찾아보고 적용하였습니다!

2024-08-05 15:39 UTC, LeeTaek2T commented on src/main/java/gift/Controller/PointController.java
> +  }
음... 멘토님이 말씀하신게 맞는 것 같습니다. 
created보다는 ok가 적절한 것 같습니다

2024-08-05 15:42 UTC, LeeTaek2T commented
끝까지 코드 리뷰해주셔서 감사합니다!

2024-08-06 03:16 UTC, ksy90101 commented on src/main/java/gift/Controller/PointController.java
> +  }
제가 생각한건 PUT으로 봐야 하지 않을까? 라는 생각이 들었구요.
member의 상태이니
members/point가 더 어울리는거 아닐까 생각이 들어서요 ㅎㅎ

2024-08-06 03:18 UTC, ksy90101 requested changes
마지막 리뷰가 될거 같네요~
간단한 리뷰 좀더 남겼으니 확인해주세요!

2024-08-06 03:18 UTC, ksy90101 commented on src/main/java/gift/Controller/PointController.java
> +    return ResponseEntity.ok().build();
내려줄 데이터가 없다면 no_conent를 사용하는게 더 좋을거 같습니다.

2024-08-06 03:18 UTC, ksy90101 commented on src/main/java/gift/Controller/PointController.java
> +    @LoginUser MemberDto memberDto) throws IllegalAccessException {
unchackedExcpetion인데 throws를 해야할 이유가 있나요?

2024-08-06 03:18 UTC, ksy90101 commented on src/main/java/gift/DTO/Member.java
> +    return new PointVo(this.pointVo.getPoint() + pointVo.getPoint());
이 역할을 여기서 하는게 맞을가요?
Point스스로 해야하지 않을가요?

2024-08-06 03:18 UTC, ksy90101 commented on src/main/java/gift/DTO/Member.java
> +  private PointVo pointVo;
VO라는 단어를 붙이진 않습니다.
Point라고만 하는게 일반적이에요 ㅎㅎ

2024-08-06 03:18 UTC, ksy90101 commented on src/main/java/gift/Service/OrderService.java
>    }
잘못 머지된거 같아요.

2024-08-06 08:55 UTC, LeeTaek2T commented on src/main/java/gift/Controller/PointController.java
> +    return ResponseEntity.ok().build();
네! 알겠습니다

2024-08-06 08:59 UTC, LeeTaek2T commented on src/main/java/gift/Controller/PointController.java
> +    @LoginUser MemberDto memberDto) throws IllegalAccessException {
추가할려는 포인트가 0원 보다 작을 경우 예외처리를 해주기 위해 throw를 해주었습니다!(따라서 checkedException이라고 생각했습니다)

2024-08-06 09:02 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Member.java
> +    return new PointVo(this.pointVo.getPoint() + pointVo.getPoint());
멘토님이 얘기해주신게 맞는 것 같습니다.
반영하겠습니다!

2024-08-06 09:03 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Member.java
> +  private PointVo pointVo;
그러면 만약 Point에 대한 VO, Entity, DTO, DAO를 모두 쓴다고 할 때 VO와 Entity클래스의 이름은 어떻게 정하나요?

2024-08-06 09:04 UTC, LeeTaek2T commented on src/main/java/gift/Service/OrderService.java
>    }
네! 수정하겠습니다!!

2024-08-06 13:22 UTC, ksy90101 approved these changes
그동안 고생 많으셨어요~ 이만 마무리할게요~

2024-08-06 13:22 UTC, merged