충남대 BE_정현서 6주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #344
Opened 2024-08-03 17:44 UTC by hynseoj

안녕하세요 멘토님
3단계 과제 제출합니다.

3단계 과제 설명이 약간 모호하게 느껴져서 포인트가 적립되고 사용하는 식인지 **포인트를 충전해서 구매는 포인트로만 가능하게** 하는 식인지 팀원들과 고민하다가 후자로 결정했습니다.

할인 정책도 service 계층에서 고정된 정책을 사용하게 할 것인지, 좀 더 유연하게 API 사용자가 정책을 선택 혹은 수정할 수 있게 할 것인지 고민하다가 일단 기본 정책은 **5만 원 이상 주문 시 총 금액의 10% 할인**으로 결정했습니다.

포인트 도메인을 크게(확장성 있게) 가져가면 controller와 엔티티 자체를 분리하는 것이 좋을 것 같지만 지금은 사용자가 가진 변경 가능한 속성 중에 하나로 보고 간단하게 구현했습니다!

---
이번이 마지막 PR이 되겠네요!
저 혼자 아무리 찾아보고 생각해봤자 해결되지 않는 고민들이 있는데 멘토님의 조언이 많은 도움이 되었던 것 같습니다.
그동안 감사했습니다. 정말정말 유익했습니다!!

2024-08-04 10:59 UTC, ksy90101 requested changes
마지막까지 꼼꼼하게 코드를 작성해주셨네요 👍 
간단한 피드백을 남겼으니 확인해주세요~

2024-08-04 10:59 UTC, ksy90101 commented on src/main/java/gift/domain/member/entity/Member.java
> +    private int point;
```suggestion
    @ColumnDefault("0")
    private int point = 0;
```
객체 관점에서도 default를 이렇게 지정할수도 있을거 같아요.

2024-08-04 10:59 UTC, ksy90101 commented on src/main/java/gift/domain/member/entity/Member.java
> +    public void rechargePoint(int amount) {
여기 amount도 음수가 들어올수도 있기 떄문에 validate가 필요할거 같긴 하네요.

2024-08-04 10:59 UTC, ksy90101 commented on src/main/java/gift/domain/member/entity/Member.java
> +    private int point;
음수에 대한 validate가 필요해보여요.

2024-08-04 10:59 UTC, ksy90101 commented on src/main/java/gift/domain/order/entity/Order.java
>      }
setter보다 의미있는 단어를 쓰는게 좋을거 같긴합니다.

2024-08-04 10:59 UTC, ksy90101 commented on src/main/java/gift/domain/order/entity/Order.java
> +    private int finalPrice;
이 두가지의 차이가 무엇인가요?

2024-08-04 10:59 UTC, ksy90101 commented on src/main/java/gift/domain/order/entity/Order.java
> +    private int originalPrice;
price가 계속 쓰인다면 VO를 만들어두고 재사용을 해보는것도 방법일거 같네요.

2024-08-04 10:59 UTC, ksy90101 commented on src/main/java/gift/domain/order/service/OrderService.java
> +    public MultipleOrderResponse createMultipleAndSendMessage(MultipleOrderRequest orderRequest, Member member) {
Multiple과 one의 중복로직이 보이는데, 중복로직을 한번 해결해보면 어떨까요?

2024-08-04 13:15 UTC, hynseoj commented on src/main/java/gift/domain/member/entity/Member.java
> +    private int point;
기본값이라 별도로 지정하지 않았는데 명시해주는 것도 직관적으로 인식하는 데 도움이 될 것 같습니다!

2024-08-04 13:17 UTC, hynseoj commented on src/main/java/gift/domain/order/entity/Order.java
> +    private int finalPrice;
원가와 할인 등이 적용된 실제 구매 가격입니다!

2024-08-04 13:30 UTC, hynseoj commented on src/main/java/gift/domain/order/entity/Order.java
> +    private int originalPrice;
좋은 방법인 것 같습니다! 적용해보겠습니다

2024-08-04 13:30 UTC, hynseoj commented on src/main/java/gift/domain/order/service/OrderService.java
> +    public MultipleOrderResponse createMultipleAndSendMessage(MultipleOrderRequest orderRequest, Member member) {
넵!!

2024-08-04 14:03 UTC, hynseoj commented on src/main/java/gift/domain/order/entity/Order.java
> +    private int finalPrice;
명세에는 두 가지를 전달하기로 정했는데, 생각해보니까 저장은 구매 가격만 해도 될 것 같다는 생각이 들어서 그렇게 수정하겠습니다!

2024-08-04 16:37 UTC, hynseoj commented
VO가 실제로 어떤 식으로 활용되는지 온전히 이해하지 못한 느낌이 있어서 지금 적절하게 사용하고 있는 건지 잘 모르겠습니다😂
얼핏 살펴본 바로는 여러가지 장점이 있어 보여서 더 찾아보고, 적용해봐야겠다는 생각이 듭니다...!
지금 만든 price는 product에도 적용될 수 있을 것 같습니다!

2024-08-05 01:10 UTC, ksy90101 requested changes
마지막 리뷰가 될거 같네요~
간단한 피드백 좀더 남겼으니 확인해주세요!

2024-08-05 01:10 UTC, ksy90101 commented on src/main/java/gift/domain/member/entity/Member.java
> +        }
이부분은 메서드로 빼면 중복로직 제거가 가능할거같네요.

2024-08-05 01:10 UTC, ksy90101 commented on src/main/java/gift/domain/order/dto/MultipleOrderResponse.java
> +            order.getOrderItems().stream().map(OrderItemResponse::from).toList(),
한줄의 점 하나로 작성하면 가독성이 더 높아집니다.
아울러 이런 값은 변수로 해두면 더 가독성이 높아지는거 같아요.

2024-08-05 01:10 UTC, ksy90101 commented on src/main/java/gift/domain/order/entity/Price.java
> +public class Price {
생각해보면 VO도 record로 가능하지 않을까요?

2024-08-05 01:10 UTC, ksy90101 commented on src/main/java/gift/domain/order/service/OrderService.java
> +        };
sendMessageToMe의 실패는 실제 messageService에서 판단해야 하지 않을까요?

2024-08-05 01:10 UTC, ksy90101 commented on src/main/java/gift/domain/order/entity/Price.java
> +    private int value;
VO는 불변 유지가 좋을거 같아요.
final을 붙여서 불변을 유지하면 어떨까요?

2024-08-05 01:10 UTC, ksy90101 commented on src/main/java/gift/domain/order/entity/Price.java
> +    }
이렇게 되면 multiplier에 소수가 들어오면 계산된 뒤에 뒤에 값이 버림이 되는지 반올림이 되는지 올림이 되는지요?

2024-08-05 05:56 UTC, hynseoj commented on src/main/java/gift/domain/order/service/OrderService.java
> +        };
맞습니다! 수정하겠습니다

2024-08-05 05:57 UTC, hynseoj commented on src/main/java/gift/domain/order/entity/Price.java
> +    private int value;
넵! final로 하고 record로 변경하겠습니다

2024-08-05 06:00 UTC, hynseoj commented on src/main/java/gift/domain/order/entity/Price.java
> +    }
아하... 제가 딱 떨어지는 케이스만 생각했는데 1원 대의 금액이 있다고 했을 때는 올림 처리가 필요할 것 같습니다.
수정하겠습니다!

2024-08-05 06:48 UTC, ksy90101 approved these changes
그동안 고생 많으셨어요~ 👍

2024-08-05 06:49 UTC, merged