강원대 BE_김송목 6주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #348
Opened 2024-08-03 20:42 UTC by kimsongmok

Point기능 구현 후, 다른 엔드포인트를 고쳤습니다.
저희 조는 상품 가격의 10퍼센트를 포인트로 적립하는 방식을 택했습니다!
https://kanguk-room.notion.site/API-33621e15b1e144f58cc81ee50fa85946

2024-08-05 13:02 UTC, jaymarystella requested changes
안녕하세요
마지막 단계네요. 몇가지 코멘트 남겼는데 확인후 의견 및 반영부탁드리겠습니다

2024-08-05 13:02 UTC, jaymarystella commented on src/main/java/gift/config/SwaggerConfig.java
> +import io.swagger.v3.oas.models.Components;
> 포인트 차감 방법 등 나머지 기능에 대해서는 팀과 논의하여 정책을 결정하고 구현한다.
> e.g.
> 5만 원 이상 주문 시 총 금액의 10%가 할인된다.
> 현금 영수증을 받으려면 휴대전화 번호를 입력해야 한다.

요구사항 정의하신내용은 readme에라도 있으면 좋을것같습니다

2024-08-05 13:02 UTC, jaymarystella commented on src/main/java/gift/model/Member.java
> +  private int points;
회원모델 자체에서 포인트를 가지고 있는 구조로 만드신 이유가 궁금합니다

2024-08-05 13:02 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +    Order order = new Order(productOption, member, orderDto.getQuantity(), orderDto.getMessage(), LocalDateTime.now(), pointsUsed, pointsEarned);
로직들의 흐름을 정리해보시고 도메인에게 부여할 수 있는 기능들이 어떤것들이 있는지 확인해보시면 좋을것같습니다.

2024-08-05 13:02 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +                    order.getMember().getPoints(),
메서드로 추출하면 더 좋을것같네요

2024-08-05 14:57 UTC, kimsongmok commented on src/main/java/gift/model/Member.java
> +  private int points;
포인트 클래스를 또 나누어 구현할 수 있었지만, 멤버 객체 자체가 어차피 포인트를 가지고 있다면, 회원 모델 자체에서 포인트를 가지고 있어도 괜찮다고 보았습니다..! 혹시 포인트를 따로 나누어 구현하는게 더 효율적이고 좋은 방법일까요??

2024-08-05 15:10 UTC, kimsongmok commented on src/main/java/gift/service/OrderService.java
> +                    order.getMember().getPoints(),
네! 메서드로 추출해 다시 작성해보았습니다

2024-08-05 15:10 UTC, kimsongmok commented on src/main/java/gift/service/OrderService.java
> +    Order order = new Order(productOption, member, orderDto.getQuantity(), orderDto.getMessage(), LocalDateTime.now(), pointsUsed, pointsEarned);
포인트에 관한 로직을 도메인에게 부여했습니다.

2024-08-07 00:20 UTC, jaymarystella commented on src/main/java/gift/model/Member.java
> +  private int points;
좋고 나쁜건 아닌데 설계의도가 궁금했었습니다. 넵 알겠습니다~

2024-08-07 00:21 UTC, jaymarystella approved these changes
고생많으셨습니다. 추후 레벨도 화이팅입니다!

2024-08-07 00:21 UTC, merged