경북대BE 박한솔 6주차 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #359
Opened 2024-08-04 08:38 UTC by pjhcsols

2024-08-05 10:22 UTC, lsm7179 requested changes
한솔님 과제 수고하셨습니다.
간단한 피드백 남겼는데 한번 확인해주세요~

2024-08-05 10:22 UTC, lsm7179 commented on src/main/java/gift/controller/kakao/KakaoController.java
> +        //System.out.println(redirectUrl);
주석은 삭제해주세요~

2024-08-05 10:22 UTC, lsm7179 commented on src/main/java/gift/controller/order/OrderController.java
> +    @GetMapping("/getAll")
restapi를 따라서 url을 만들어주시면 좋을거 같네요.

2024-08-05 10:22 UTC, lsm7179 commented on src/main/java/gift/domain/point/Point.java
> +    }
charge와 add의 차이점이 있나요?

2024-08-05 10:22 UTC, lsm7179 commented on src/main/java/gift/service/kakao/KakaoService.java
> +        Long pointsToEarn = (long) (remainingCashAmount * 0.05);
`0.05`는 언제든 바뀔수있습니다. 프로퍼티화 하거나 db를 이용하여 수정될수있게 하면 좋을거 같아요.

2024-08-05 10:22 UTC, lsm7179 commented on src/main/java/gift/service/order/OrderService.java
> +        Order order = new Order(user, productOption, orderRequest.getQuantity(), orderRequest.getMessage(), LocalDateTime.now(), remainingCashAmount, pointsToUse);
이부분이 kakaoOrderService와 중복되어 사용되고 있는데 중복된 코드를 정리하면 좋을거 같아요.

2024-08-05 10:22 UTC, lsm7179 commented on src/main/java/gift/service/point/PointService.java
> +    @Autowired
`@Autowired` 는 생략 가능합니다.

2024-08-05 10:22 UTC, lsm7179 commented on src/main/java/gift/domain/point/Point.java
> +    public void charge(Long amount) {
비즈니스 로직을 테스트코드로 검증하면 좋을거 같습니다.
또한 amount가 null이거나 음수일때 validate도 필요해보이네요.

2024-08-05 10:34 UTC, pjhcsols commented on src/main/java/gift/service/order/OrderService.java
> +        Order order = new Order(user, productOption, orderRequest.getQuantity(), orderRequest.getMessage(), LocalDateTime.now(), remainingCashAmount, pointsToUse);
기존 사용자와 카카오 사용자를 서비스 로직 단에서 나눠서 사용할려고 분리를 하였는데 생각을 여쭙고싶습니다 로직을 합챠서 카카오 사용자가 아닐시에는 메시지를 보내지않게끔 합치는것이 좋을까요?

2024-08-05 11:02 UTC, lsm7179 commented on src/main/java/gift/service/order/OrderService.java
> +        Order order = new Order(user, productOption, orderRequest.getQuantity(), orderRequest.getMessage(), LocalDateTime.now(), remainingCashAmount, pointsToUse);
비즈니스 로직은 동일해야 되고 카카오/사용자 서비스 로직은 나눠야될거 같습니다.
그렇게 한다면 서비스에서 공통으로 불어와서 사용하는 메소드가 있을것이고 그 이후 처리는 각각 서비스에서 진행해도 좋을거 같습니다.

2024-08-05 11:44 UTC, pjhcsols commented on src/main/java/gift/domain/point/Point.java
> +    public void charge(Long amount) {
validateAmount로 체킹을 하고 도메인과 서비스 로직을 테스트 코드로 검증하게 하였습니다.

2024-08-05 11:44 UTC, pjhcsols commented on src/main/java/gift/service/kakao/KakaoService.java
> +        Long pointsToEarn = (long) (remainingCashAmount * 0.05);
프로퍼티화 하였습니다!

2024-08-05 11:44 UTC, pjhcsols commented on src/main/java/gift/domain/point/Point.java
> +    }
기존의 charge로직을 add로 일괄적으로 사용하게 하였습니다.

2024-08-05 11:45 UTC, pjhcsols commented on src/main/java/gift/controller/order/OrderController.java
> +    @GetMapping("/getAll")
/orders로 restapi에 따라 수정하였습니다.

2024-08-06 09:44 UTC, lsm7179 approved these changes
한솔님 잘 정리해주었네요.
6주동안 step2과제 수고하셨습니다.😁

2024-08-06 09:44 UTC, lsm7179 commented on src/test/java/gift/domain/point/PointTest.java
> +class PointTest {
👍

2024-08-06 09:44 UTC, merged