충남대 BE 김유겸 6주차 과제 (1, 2, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #361
Opened 2024-08-04 08:56 UTC by rladbrua0207

6주동안 정말 감사했습니다!!

질문이 좀 많습니다..!

팀이 중간에 바뀌면서 명세가 많이 변경되어 커밋에 여러 기능이 겹치게 된 점 양해 부탁드립니다.

커밋 로그를 봤을 때 저도 이해하기 힘들 것 같아서, 코드 리뷰 시 아래 세 가지 사항에 중점을 두어 주시면 감사하겠습니다!

1. **API 명세에 맞게 DTO 세부적으로 분리**:
   - DTO(Data Transfer Object)를 API 명세에 맞게 세분화하여 필요한 데이터만 전송하도록 구현했습니다. 각 API가 요구하는 데이터 구조에 맞게 DTO를 설계하고 적용했습니다.

2. **할인 정책**:
   - 실제 프로젝트였다면 상품 또는 카테고리별로 필드에 적용할 정책을 설정했겠지만, 간소화하여 모든 상품에 동일한 정책을 적용하도록 구현했습니다. 할인 정책의 세부 사항과 적용 방식에 대해 검토해 주세요.

3. **CI/CD**:
   - CI/CD 관련 로직을 작성했으나, 현재 서브모듈을 적용 중에 있습니다.

# 질문

## 1. DTO 유지보수 측면에서의 질문

현재 저는 Service 계층에서 엔티티를 조회하여 필요한 정보만을 담아 DTO로 반환하는 방식으로 구현하고 있습니다. 예를 들어, Option 엔티티를 OptionServiceResponse DTO로 변환하는 코드입니다:

```java
package gift.option.application;

import gift.option.domain.Option;

public record OptionServiceResponse(
        Long id,
        String name,
        Integer quantity
) {
    public static OptionServiceResponse from(Option option) {
        return new OptionServiceResponse(
                option.getId(),
                option.getName(),
                option.getQuantity()
        );
    }
}
```

이렇게 하면 repository에서 조회한 엔티티 자체를 받아서 Controller에 필요한 정보만 주면 되고, 추후 Controller에서 필요한 정보가 바뀌더라도 해당 DTO만 바꾸면 되기 때문에 유지보수 측면에서 좋다고 생각합니다.

하지만, 4주차에 도메인 로직에서 Update 메서드 인자 처리에서 피드백 주신 내용에 대해서 혼란이 있습니다.

![image](https://github.com/user-attachments/assets/315b5f33-7408-4efc-b1eb-9370093c79f9)
[https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/191#discussion_r1683622319](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/191#discussion_r1683622319)

Update 메서드에 command DTO를 직접 전달받기보다 필요한 값만 전달받는 것이 유지보수에 더 유리하다고 하셨습니다. 예를 들면:

```java
public void update(String name, String color, String description, String imageUrl) {
    this.name = name;
    this.color = color;
    this.description = description;
    this.imageUrl = imageUrl;
}
```

와 같이 DTO를 넘겨주는 것이 아닌 실제 필요한 값들만 전달하는 것이 좋다고 하셨습니다.

물론 두 상황이 일치하는 것은 아니지만, 위 예시의 OptionServiceResponse에서는 "추후 변경사항이 생겼을 때 DTO만 바꾸면 된다"라는 이유로 괜찮은 방법이라고 생각하지만, 도메인 로직에서 필요한 정보만 주는 것이 왜 유지보수 측면에서 더 좋은지 명확하게 이해되지 않습니다. 이에 대한 설명을 부탁드립니다.

## 2. 카카오 로그인 로직 관련 질문

우선 제가 이해한 카카오 로그인의 흐름을 말씀드리겠습니다.

![image](https://github.com/user-attachments/assets/1dcd3979-ab45-4893-97df-de1c843c551d)
(출처: [카카오 로그인 플로우](https://velog.io/@padd60/%EB%84%A4%EC%9D%B4%EB%B2%84-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EB%BF%8C%EC%88%98%EA%B8%B0))

1. 프론트엔드가 카카오 로그인을 클릭합니다.
2. 서버가 프론트엔드를 카카오 측의 로그인 페이지로 리다이렉트 시켜줍니다 (이때 서버에서 설정한 `redirect_uri`를 포함합니다).
3. 로그인에 성공한 뒤, 카카오는 클라이언트를 `redirect_uri`로 리다이렉트 시키며 인가 코드를 쿼리 파라미터로 전달합니다.
4. 프론트엔드는 리다이렉트됨과 동시에 전달받은 인가 코드를 서버로 보내어 카카오 사용자 정보를 받아옵니다 (인가 코드를 서버로 전달할 때 서버는 `redirect_uri`를 카카오 서버로 보내어 카카오 앱 설정 시 입력한 `redirect_uri`와 같은지 검증합니다).
5. 서버는 카카오 사용자 정보를 통해 회원가입 또는 로그인 후 자체 토큰을 발급하여 클라이언트에게 전달합니다.

이해한 내용이 맞는지 궁금합니다.

이해한 내용을 바탕으로 구현을 완료했습니다. 그러나 프론트엔드 개발자가 카카오 로그인 로직을 구현할 수 없어서 혼자 테스트를 진행했습니다.

### 테스트 과정

`redirect_uri`는 프론트엔드가 없기 때문에 백엔드 서버의 `/api/login/kakao/callback`으로 설정했습니다. 이는 프론트엔드가 리다이렉트된 후 해당 엔드포인트에서 위의 흐름에서 4번을 수행하기 위해 요청해야 하는 엔드포인트이기 때문입니다.

CORS 관련 설정을 적용하여 다른 요청에서는 CORS 오류가 발생하지 않았지만, 카카오 관련 기능을 사용할 때 CORS 오류가 발생했습니다.

제 스웨거는 [http://43.203.170.141/swagger-ui/index.html#](http://43.203.170.141/swagger-ui/index.html#)입니다.

CORS는 SOP(Same-Origin Policy)를 위반하더라도 다른 출처의 리소스 공유를 허용해준다면 브라우저에서 리소스 요청을 막지 않는 것으로 이해하고 있습니다. 하지만 제 스웨거에서 요청할 때 백엔드 서버는 같은 출처인 `http://43.203.170.141/api`입니다.

![image](https://github.com/user-attachments/assets/b8490fc8-0e03-43a0-9c6a-e3a3556c8c0b)

스웨거에서 카카오 로그인을 요청하면 서버가 카카오 로그인 페이지로 리다이렉트합니다. 이때 리다이렉트되는 URI는 `https://kauth.kakao.com/oauth/authorize/~`입니다.

### 네트워크 요청 확인 결과

스웨거에서 카카오 로그인 요청을 보낼 때 네트워크를 확인해봤는데 다음과 같이 세 번의 요청이 확인됩니다:

1. 요청: `http://43.203.170.141/api/members/login/kakao`로 GET 요청을 보냅니다.
   - **Status Code**: 302 Found

2. 리다이렉트: `https://kauth.kakao.com/oauth/authorize`로 리다이렉트됩니다.
   - **Status Code**: 302 Found

3. 카카오 로그인 페이지: `https://accounts.kakao.com/login`으로 리다이렉트됩니다.
   - **Status Code**: 200 OK

3단계에서 CORS 오류가 발생하고, 요청 헤더에서 `Origin`이 `null`로 설정되어 있습니다.

### 질문

1. 카카오 로그인 관련 CORS 허용 설정은 카카오 서버에서 특정 `Origin`을 허용해야 한다고 알고 있습니다. 그렇기 때문에 카카오 로그인 관련 로직에서는 카카오에서 CORS 설정을 해줘야 한다고 생각합니다. 카카오에서 따로 CORS 설정을 해주지 않았는데 어떻게 설정이 적용되는 걸까요? 앱 설정에서 `redirect_uri`를 설정할 때 해당 `Origin`도 설정해주는 것인가요?
2. 위 질문이 맞다면, 클라이언트에서 `Origin`을 설정하지 않았기 때문에 CORS가 발생하는 것인가요?
3. 위 질문이 맞다면, 스웨거에서는 `Origin` 설정이 불가능하기 때문에 CORS가 발생하는 것인가요?

## 3. application.properties 관련 질문

CI/CD 파이프라인을 구축할 때, `application.properties` 파일은 `.gitignore`에 등록되어 있기 때문에 GitHub에서 빌드할 때 해당 파일이 존재하지 않습니다.

원래는 서브모듈로 `properties` 파일을 관리하여 배포를 하였습니다.

다른 방법으로는 공개되도 되는 설정 정보를 `application.properties`에 담고, 공개되면 안 되는 정보를 GitHub Secrets를 통해 개별적으로 설정하는 방법이 있는 것 같습니다. 하지만, 이러한 방법은 실수가 발생할 수 있고 번거로운 과정이라고 생각됩니다.

### 질문

현업에서는 민감한 설정 파일을 어떻게 관리하나요?

2024-08-04 11:36 UTC, Hyeon9mak requested changes
유겸님! 1~3단계까지 잘 진행해주셨습니다.
질문 주신 내용 집중적으로 코멘트 남겼어요.
추가로 미션 진행을 하실 것 같아서 우선 request changes 남길게요!

2024-08-04 11:36 UTC, Hyeon9mak commented on src/main/java/gift/product/presentation/response/ProductReadOptionResponse.java
> +    }
> Presentation과 Application 각 계층에서의 DTO통일성을 생각하며 구현하였습니다.

통일성은 가독성을 높이고, 가독성은 유지보수성을 높여주죠. 👍

2024-08-04 11:36 UTC, Hyeon9mak commented on src/main/java/gift/discount/domain/PercentageDiscountPolicy.java
> +    }
언제든지 할인정책을 갈아끼우기 좋은 상태로 구현해주셨군요 👍

2024-08-04 11:36 UTC, Hyeon9mak commented on .github/workflows/deploy.yml
> +        run: ./gradlew build
`./gradlew clean build` 와 차이는 어떻게 될까요?

2024-08-04 11:36 UTC, Hyeon9mak commented on .github/workflows/deploy.yml
> +        run: docker push yugyeom/spring-gift:latest
개인 docker hub 에 이미지 적재 후 로드하여 사용! 👍

2024-08-04 11:36 UTC, Hyeon9mak commented on src/main/java/gift/category/application/CategoryService.java
> +        return categoryRepository.save(command.toCategory()).getId();
> "추후 변경사항이 생겼을 때 DTO만 바꾸면 된다"라는 이유로 괜찮은 방법이라고 생각하지만, 도메인 로직에서 필요한 정보만 주는 것이 왜 유지보수 측면에서 더 좋은지 명확하게 이해되지 않습니다...

DTO만 바꾸면 된다도 동의해요~ 제가 유리하다고 생각하는 대표적인 상황은 코드를 읽을 때와 테스트 코드 작성시인데요,
코드를 처음 보는 사람은 `CategoryService` 와 `CategoryUpdateCommand`, `Category` 3개 클래스 파일을 읽어봐야하죠.
DTO 를 쓰지 않는다면 `CategoryService`, `Category` 만 보더라도 어떤 값에 대한 업데이트를 시도하는지 알 수 있겠네요.

또한 테스트 코드 작성시 아래와 같은 편의가 차이날거 같아요.

```java
category.update(
    "멋진 카테고리",
    "#001122",
    "멋진 카테고리입니다.",
    "https://image.url"
);
```

```java
CategoryUpdateCommand command = new CategoryUpdateCommand(
    "멋진 카테고리", 
    "#001122", 
    "멋진 카테고리입니다.", 
    "https://image.url"
);
category.update(command);
```

2024-08-04 11:36 UTC, Hyeon9mak commented on src/main/java/gift/auth/KakaoService.java
> +                        throw new UnAuthorizedException("code가 유효하지 않습니다.");
> 카카오 로그인 플로우 이해한 내용이 맞는지

맞습니다 👍 

> 카카오 로그인 관련 CORS 허용 설정은 카카오 서버에서 특정 Origin을 허용해야 한다고 알고 있습니다. 그렇기 때문에 카카오 로그인 관련 로직에서는 카카오에서 CORS 설정을 해줘야 한다고 생각합니다. 카카오에서 따로 CORS 설정을 해주지 않았는데 어떻게 설정이 적용되는 걸까요? 앱 설정에서 redirect_uri를 설정할 때 해당 Origin도 설정해주는 것인가요?

카카오측에서는 cors 관련 설정을 모두 열어둔 상태인 걸로 알고 있어요.
https://devtalk.kakao.com/t/cors-error/121958
그리고 유겸님께서도 CORS 설정을 전역으로 다 개방하셨던걸로 기억하고 있어요.
CORS 는 브라우저 레벨에서 차단하는거라, 클라이언트에서 서버를 어떻게 호출하고 있는지 확인해야할거 같아요.

정확한 에러 로그를 첨부해주시면 확인이 빠를 것 같은데,
추측키로는 말씀해주신 3번이 맞지 않나 싶네요.

> 현업에서는 민감한 설정 파일을 어떻게 관리하나요?

회사, 팀 마다 인프라를 어떻게 관리하느냐에 따라 크게 달라요.
현재 저희 조직은 aws 에서 제공하는 secret manager 라는 서비스에 민감한 데이터들을 관리하고 있어요.
secret manager 에 데이터들 저장해두면, aws 의 타 서비스(ec2 등)에서 해당 값을 끌어와 사용할 수 있습니다.
가령, ec2 인스턴스를 띄울 때 환경변수로 secret manager 에 적재된 값을 등록해주는 방식이에요.
그럼 ci-cd 동작 중 springboot app 을 띄울 때 환경변수를 그대로 집어넣는 명령어만 등록해주면 되겠죠!

2024-08-04 13:08 UTC, rladbrua0207 commented on .github/workflows/deploy.yml
> +        run: ./gradlew build
./gradlew build로 하면 이전 빌드를 캐시하여 변경된 부분만 빌드하고, ./gradlew clean build는 build파일을 완전히 지우고 빌드합니다.


검색해보니 gradlew build로 했을때 변경 된 부분을 추적할때 안되는 상황도 있어서 반영이 덜되거나 에러가 발생할 수 있군요!

./gradlew clean build로 바꿔야겠습니다.

2024-08-04 13:11 UTC, yugyeom-ghim commented on src/main/java/gift/category/application/CategoryService.java
> +        return categoryRepository.save(command.toCategory()).getId();
오.. 제가 생각해보지 못한 관점이네요.

제 코드를 보는 사람 입장에서 더 많은 클래스를 읽어봐야 이해 할 수 있겠네요..

너무 유지보수 하는 입장에서 생각했네요!

2024-08-04 13:48 UTC, rladbrua0207 commented on src/main/java/gift/auth/KakaoService.java
> +                        throw new UnAuthorizedException("code가 유효하지 않습니다.");
> 카카오측에서는 cors 관련 설정을 모두 열어둔 상태인 걸로 알고 있어요. https://devtalk.kakao.com/t/cors-error/121958

오... 그렇군요 감사합니다!

> 그리고 유겸님께서도 CORS 설정을 전역으로 다 개방하셨던걸로 기억하고 있어요.
저는 프론트분이 계신다면 프론트분 로컬에서 테스트 할 때를 생각해 localhost:3000을 설정해두었습니다!

> 추측키로는 말씀해주신 3번이 맞지 않나 싶네요.
브라우저 레벨에서 차단하는거기때문에 origin이 null이기 때문에 CORS 에러가 발생하는게 맞는거같습니다! 클라이언트에서 origin 설정을 따로 해주는게 맞는거같습니다!


위의 네트워크 요청 확인 결과 사진을 첨부하겠습니다
<img width="1072" alt="image" src="https://github.com/user-attachments/assets/9bde8e9a-9693-467d-b7a0-57e0ec9e817d">
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/93d8a898-28a3-41c0-8c57-d0a0c5beef98">
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/d0a66df1-8e3f-435a-952a-e3512c0c2b3a">


> 회사, 팀 마다 인프라를 어떻게 관리하느냐에 따라 크게 달라요.
현재 저희 조직은 aws 에서 제공하는 secret manager 라는 서비스에 민감한 데이터들을 관리하고 있어요.
secret manager 에 데이터들 저장해두면, aws 의 타 서비스(ec2 등)에서 해당 값을 끌어와 사용할 수 있습니다.
가령, ec2 인스턴스를 띄울 때 환경변수로 secret manager 에 적재된 값을 등록해주는 방식이에요.
그럼 ci-cd 동작 중 springboot app 을 띄울 때 환경변수를 그대로 집어넣는 명령어만 등록해주면 되겠죠!

그렇군요! 감사합니다!!

2024-08-05 01:03 UTC, Hyeon9mak commented on src/main/java/gift/auth/KakaoService.java
> +                        throw new UnAuthorizedException("code가 유효하지 않습니다.");
첨부해주신 사진은 에러로그 화면 아니라 header 화면이네요 😱 
자세한 건 따로 이야기 나누시죠!

2024-08-05 01:06 UTC, Hyeon9mak approved these changes
안녕하세요 유겸님! 미션 마지막까지 고생 많으셨어요.
해결 안된 오류는 따로 이야기 나눠요 ㅎㅎ
요구사항 모두 만족되어 approve 합니다!

그간 남겨드린 코멘트들이 도움이 되셨을까요?
앞으로의 팀 프로젝트도 즐겁게 해나가시면 좋겠습니다!
고생 많으셨어요! 👍 앞으로도 화이팅!

2024-08-05 01:06 UTC, Hyeon9mak commented on .github/workflows/deploy.yml
> +
😉 👍

2024-08-05 01:06 UTC, Hyeon9mak commented on .gitmodules
> +	url = https://github.com/rladbrua0207/spring-gift-submodule.git
접속이 잘 막히네요! 👍

2024-08-05 01:06 UTC, merged

2024-08-05 01:07 UTC, Hyeon9mak commented on src/main/java/gift/auth/KakaoService.java
> +                        throw new UnAuthorizedException("code가 유효하지 않습니다.");
아마 추측키는 localhost:3000 상태로 호출하다보니, 포트번호가 달라서 cors 가 발생하는거 같긴 하네요.

2024-08-05 01:14 UTC, rladbrua0207 commented on src/main/java/gift/auth/KakaoService.java
> +                        throw new UnAuthorizedException("code가 유효하지 않습니다.");
>첨부해주신 사진은 에러로그 화면 아니라 header 화면이네요 😱 
자세한 건 따로 이야기 나누시죠!
<img width="1346" alt="image" src="https://github.com/user-attachments/assets/21ed357d-3450-4df0-b69f-968ed0566f8c">

헉 CORS오류라 그런지 따로 로그에는 에러가 잡히지 않아 헤더를 보여드렸습니다..!


스웨거에서는 다음과 같이 CORS라고 나옵니다!
![image](https://github.com/user-attachments/assets/231e9510-82dd-407b-a93e-c6bd337482a3)

> 아마 추측키는 localhost:3000 상태로 호출하다보니, 포트번호가 달라서 cors 가 발생하는거 같긴 하네요.
프론트엔드 localhost:3000에서 테스트하진 못하고 스웨거에서 테스트해서 포트번호도 같습니다!


제 생각엔 확실하진 않지만 스웨거에서 요청할때 origin 요청헤더를 포함하지 않고 보내서 그런거라고 생각합니다!

2024-08-05 01:16 UTC, rladbrua0207 commented on .gitmodules
> +	url = https://github.com/rladbrua0207/spring-gift-submodule.git
> 안녕하세요 유겸님! 미션 마지막까지 고생 많으셨어요.
해결 안된 오류는 따로 이야기 나눠요 ㅎㅎ
요구사항 모두 만족되어 approve 합니다!

그간 남겨드린 코멘트들이 도움이 되셨을까요?
앞으로의 팀 프로젝트도 즐겁게 해나가시면 좋겠습니다!
고생 많으셨어요! 👍 앞으로도 화이팅!

너무 도움이 많이됐습니다!! 6주동안 정말 좋은 코멘트 감사했습니다!

2024-08-05 01:17 UTC, rladbrua0207 commented
> 안녕하세요 유겸님! 미션 마지막까지 고생 많으셨어요. 해결 안된 오류는 따로 이야기 나눠요 ㅎㅎ 요구사항 모두 만족되어 approve 합니다!
> 
> 그간 남겨드린 코멘트들이 도움이 되셨을까요? 앞으로의 팀 프로젝트도 즐겁게 해나가시면 좋겠습니다! 고생 많으셨어요! 👍 앞으로도 화이팅!


너무 도움이 많이됐습니다!! 6주동안 정말 좋은 코멘트 감사했습니다!