경북대 BE_정수현 6주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #370
Opened 2024-08-04 13:15 UTC by suhyeon7497

https://github.com/kakao-tech-campus-2nd-step2/spring-gift-point/pull/252
2단계 PR입니다.

저희 조의 point는 적립금 형식으로 "주문을 할때 사용할 포인트를 작성하고, 이후 포인트 할인 후 금액의 10%만큼 포인트를 획득한다." 라는 것을 중심으로 기능을 개발하였습니다. 현재는 cors연결에 성공하였습니다.

-협업 과정(*프론트 엔드 개발자가 한 명이어서 프론트 엔드 개발자가 사용한 url, request, response를 기준으로 백엔드 개발자들이 맞추었습니다.)
1. 처음으로 RequestMapping에 대한 url을 통일하였습니다.
2. 다른 백엔드 개발자 분들도 한 상품에 대한 주문이 완료되면 wish의 상품 개수 비교 없이 바로 삭제하는 로직으로 작성하여서, wish에 count가 불필요하게 되어 저번에 주석처리했었는데, 그래도 update가 필요하다고 생각 되어 product를 바꿀 수 있도록 변경하였습니다. https://github.com/kakao-tech-campus-2nd-step2/spring-gift-point/pull/252#discussion_r1702555744
3. 저희 조는 https 통신의 연결은 하지 않았지만, 개인적으로 다른 프로젝트에서 공부를 하다가 ERR_CERT_COMMON_NAME_INVALID 에러가 발생하였는데, 꾸준히 공부해볼 예정입니다!

느낀점.
 cors연결을 하면서 제대로 api명세를 명확히 설정해두지 않으면 누가 잘못된 코드를 작성하였는지, 빠르게 확인하기 어려울 것 같았습니다. 또한, 어느 정도 프론트엔드 분야의 지식이 있어야 한다고 느꼈습니다. 프론트 엔드 개발자 분이 말씀하실 때 무슨 의미로 말을 하는 지 잘 모를 때가 존재하였습니다. 백엔드 개발을 좀 해보고 어느 정도 숙달되면 프론트 엔드 개발도 한번 해볼 예정입니다. 
 첫 날에 다른 분들의 코드를 리뷰하는 시간을 가졌었는데, 다들 잘하시고 회의할때도 수용도 잘해주셔서 배울 점이 많다고 생각하였습니다. 누구에게나 배울점은 많고 적극 수용하는 자세를 가져야 겠다고 생각하였습니다.
 멘토님 6주 동안 코드리뷰 잘해주셔서 감사합니다. 멘토링하면서 좋은 소리, 쓴소리, 고민 상담도 많이 해주셔서 힘들었지만 의지도 되었고 많은 점을 배울 수 있었습니다. 짧은 시간이었지만 감사드립니다!

2024-08-05 17:24 UTC, sang5c approved these changes
마지막까지 고생 많으셨습니다. :)  
가독성 관련해서 리뷰 남겼으니, 읽어보시고 적용해보시면 좋을 것 같습니다.

2024-08-05 17:24 UTC, sang5c commented on src/main/java/gift/order/OrderService.java
> +    public OrderResponse createOrder(OrderRequest orderRequest, LoginMemberDto loginMemberDto)
메서드가 26라인이네요. 리팩터링을 진행해주세요~

2024-08-05 17:24 UTC, sang5c commented on src/main/java/gift/order/OrderService.java
> +    public OrderResponse createOrder(OrderRequest orderRequest, LoginMemberDto loginMemberDto)
메서드 내에서 하고자 하는 작업을 글로 작성해보고, 코드를 재작성해보면 어떨까요?  
어떤 일들이 이루어지고 있는지 알기 어렵네요 🤔

2024-08-05 17:24 UTC, sang5c commented on src/main/java/gift/order/OrderService.java
>          option.subtract(orderRequest.quantity());
멤버를 찾는다
멤버의 포인트를 사용한다
옵션을 찾는다.
위시리스트에서 멤버 아이디+프로덕트 아이디가 일치하는 것을 찾아 위시리스트를 삭제한다.
프로덕트를 찾는다.
옵션에서 주문 수량을 뺀다.

멤버 -> 옵션 -> 위시리스트 -> 프로덕트 -> 위시리스트 -> 프로덕트 -> 옵션

일부만 예시를 들어봤습니다만, 비즈니스 로직 가독성이 떨어진다고 느껴지네요!  
뒤에 이어지는 로직도 같은 느낌입니다.

2024-08-05 17:24 UTC, sang5c commented on src/main/java/gift/order/OrderService.java
> +            orderRequest.point(),
discountPrice에 orderRequest.point()를 전달하는게 어색하네요 🤔

2024-08-05 17:24 UTC, sang5c commented on src/main/java/gift/product/model/Product.java
> +    public Integer getTotalPrice(Integer quantity) {
연산작업이 있는 경우 메서드명으로 나타내주세요!

2024-08-05 17:25 UTC, sang5c requested changes
배포된 서버 접속 가능한 URL을 올려주세요~

2024-08-06 14:54 UTC, suhyeon7497 commented on src/main/java/gift/order/OrderService.java
> +            orderRequest.point(),
discountPrice가 사실상 할인될 금액이라 point와 동일해서 저도 불편하지만 그렇게 작성하였습니다..

2024-08-06 14:54 UTC, suhyeon7497 commented on src/main/java/gift/order/OrderService.java
>          option.subtract(orderRequest.quantity());
넵!

2024-08-06 14:56 UTC, suhyeon7497 commented on src/main/java/gift/order/OrderService.java
> +    public OrderResponse createOrder(OrderRequest orderRequest, LoginMemberDto loginMemberDto)
wish에 들어있으면 지우기,
option 개수 줄이기,
order 저장하기,
member point 사용하기,
order message 보내기의 작업을 합니다. 
이를 토대로 refactoring 진행해보겠습니다!

2024-08-06 14:56 UTC, suhyeon7497 commented on src/main/java/gift/product/model/Product.java
> +    public Integer getTotalPrice(Integer quantity) {
넵!

2024-08-06 15:03 UTC, suhyeon7497 commented
http://15.165.164.139:8080 입니다. 현재는 main의 기능만 작동하여 아마 step2까지만 반영되어있습니다.

2024-08-06 16:59 UTC, sang5c commented
백엔드 API를 호출해볼 수 있는 프론트엔드 페이지 URL을 알려주세요 🙂

2024-08-06 17:02 UTC, sang5c approved these changes
6주간 고생 많으셨습니다!  
앞으로 남은 과정도 응원합니다 💪💪  
이후에도 궁금한게 있으시면 편하게 물어보셔도 됩니다.

2024-08-06 17:02 UTC, merged

2024-08-08 04:31 UTC, suhyeon7497 commented
프론트엔드 주소는 http://kakaogift.s3-website.ap-northeast-2.amazonaws.com/ 입니다! 그런데 BaseUrl 변경을 안해두셔서 작동을 안합니다..

2024-08-08 04:31 UTC, suhyeon7497 commented
BaseUrl 변경이 확인 되는 이후에 연락주시면 aws서버 인스턴스를 키겠습니다!