충남대 BE_김민지 6주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #374
Opened 2024-08-04 14:41 UTC by alsswl

마지막 과제 제출입니다! 그동안 피드백해주셔서 감사합니다 많은 도움 되었어요😀

2024-08-05 01:19 UTC, Hyeon9mak requested changes
안녕하세요 민지님! 3단계 잘 진행해주셨어요.
마지막으로 간단한 코멘트 남겼으니 확인해주세요 😄

2024-08-05 01:19 UTC, Hyeon9mak commented on src/main/java/gift/domain/MemberDomain/MemberPoint.java
> +    }
객체 내부에 비즈니스 로직을 잘 심어주셨네요 👍

2024-08-05 01:19 UTC, Hyeon9mak commented on src/main/java/gift/domain/MemberDomain/MemberPoint.java
> +    }
`IllegalAccessException` 를 명세해둔 이유가 있을까요?

2024-08-05 01:19 UTC, Hyeon9mak commented on src/main/java/gift/service/MemberService.java
>              return new MemberResponse(memberRequest.email(),memberRequest.password());
회원가입시 기본 1000포인트가 지급된다는 것 또한 Member 내부에서 다뤄주는건 어떨까요?

2024-08-05 01:19 UTC, Hyeon9mak commented on src/test/java/gift/EntityTest/MemberPointTest.java
> +        });
꼼꼼한 테스트 👍

2024-08-07 06:48 UTC, alsswl commented on src/main/java/gift/domain/MemberDomain/MemberPoint.java
> +    }
이 에러가 발생했을 때 Controller가 이를 받고 responseEntity형식으로 응답을 보내는 로직을 구현하기 위함이었습니다!

2024-08-07 07:05 UTC, Hyeon9mak approved these changes
안녕하세요 민지님~ 6주간 고생 많으셨어요.
그간 남겨드린 코멘트가 도움이 되셨으면 좋겠네요 😄 
다음 과정들도 화이팅입니다!

2024-08-07 07:05 UTC, Hyeon9mak commented on src/main/java/gift/domain/MemberDomain/MemberPoint.java
> +    }
throws 를 명세하지 않아도, controller advice 가 runtime exception 을 잡아서 처리해줄 것 같아요!

또한 내부에서 `IllegalAccessException ` 가 아닌 `IllegalArgumentException` 를 던지고 있는 것 같은데요!
제대로 명세된게 맞는지 확인이 필요할거 같아요~!

2024-08-07 07:05 UTC, merged