충남대 BE_신성희 6주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #376
Opened 2024-08-04 14:58 UTC by Shsin9797

2024-08-04 18:46 UTC, asebn1 requested changes
성희님 안녕하세요~
3단계도 잘 구현해주셨네요
6주간 고생많으셨습니다 :)
PR 충돌나는 부분만 해결해주시면 머지하겠습니다

2024-08-04 18:46 UTC, asebn1 commented on src/main/java/gift/service/GiftOrderService.java
>      public GiftOrderResponseDto placeOrderWithMessage(GiftOrderRequestDto giftOrderRequestDto, Long orderMemberId) throws IllegalAccessException {
👍 👍

2024-08-04 18:46 UTC, asebn1 commented on README.md
> +  - [x] 5만 원 이상 주문 시 총 금액의 10%가 할인된다.
요구사항 정리 👍

2024-08-05 09:33 UTC, Shsin9797 commented
넵!! 멘토님도 6주간 고생많으셨습니다!! 감사합니다!!

2024-08-05 10:00 UTC, asebn1 approved these changes
성희님 안녕하세요~
6주간 고생많았습니다. 👍 👍 
이번 3단계는 이만 머지하겠습니다.
앞으로도 화이팅하세요!! ㅎㅎ

2024-08-05 10:00 UTC, merged