전남대_BE 김수랑 6주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #380
Opened 2024-08-04 15:56 UTC by rdme0

6주차 3단계 PR 올립니다!
저희는 포인트 개념을 현금 같은 느낌으로 적용하였으며, 5만원 이상 결제 시 10% 할인되도록 구현하였습니다!

2024-08-05 15:44 UTC, Hongdonggeon requested changes
안녕하세요 수랑님
미션 잘 구현해주셨네요!
코멘트 확인해주세요~ 수고하셨습니다!

2024-08-05 15:44 UTC, Hongdonggeon commented on src/main/java/gift/service/OrderService.java
> +        if(price >= 50000)
50000 상수로 빼도 좋을 것 같아요

2024-08-05 15:44 UTC, Hongdonggeon commented on src/main/java/gift/entity/OrderHistory.java
> +            throw new BadRequestException("올바르지 않은 전화번호 입니다.");
엔티티에서 badRequestException을 던지는건 엔티티가 웹계층에 너무 많이 알고있는 것 같아요
엔티티에서는 일반예외나 도메인 관련 커스텀 예외를 발생시키고 service 계층에서 도메인 예외를 잡고 badRequestException으로 전환하는게 어떨까요?

2024-08-05 15:44 UTC, Hongdonggeon commented on src/main/java/gift/entity/Member.java
> +            throw new BadRequestException("올바르지 않은 포인트 입니다.");
여기 예외도 고민해주세요!

2024-08-05 15:44 UTC, Hongdonggeon commented on src/main/java/gift/controller/MemberController.java
> +@RequestMapping("api/members")
앞에 / 붙어야하지 않나요?

2024-08-05 15:44 UTC, Hongdonggeon commented on src/main/java/gift/controller/MemberController.java
> +@Controller
restController에서 바꾼 이유가 어떻게 될까요?

2024-08-05 15:44 UTC, Hongdonggeon commented on src/main/java/gift/service/OrderService.java
>              kakaoTokenService.sendMsgToMe(accessToken, option, orderRequestDTO.message());
메서드 단위가 약간 큰 것 같은데요. 카카오톡 메시지 전송은 트랜잭션에서 분리할 수 있지 않을까요?

2024-08-06 07:50 UTC, rdme0 commented on src/main/java/gift/entity/OrderHistory.java
> +            throw new BadRequestException("올바르지 않은 전화번호 입니다.");
엔티티에서는 `IllegalArgumentException`을 던지도록 해놓고 서비스에서 그걸 잡아서 BadRequestException을 던지도록 리팩터링 하였습니다!

2024-08-06 07:57 UTC, rdme0 commented on src/main/java/gift/controller/MemberController.java
> +@Controller
이번 단계에서 포인트 기능이 추가됨에 따라 관리자 페이지에서 포인트를 조회하려면
그 전에 클라이언트가 로컬로 저장했던 토큰을 제출하기 위해 회원가입, 로그인 뷰가 필요해서 Controller로 리팩터링 하게 되었습니다.

2024-08-06 08:02 UTC, rdme0 commented on src/main/java/gift/service/OrderService.java
>              kakaoTokenService.sendMsgToMe(accessToken, option, orderRequestDTO.message());
카카오톡 메시지 전송을 컨트롤러로 올리려고 하다가 accessToken 체크 로직 때문에 복잡해질 거 같아서 어떻게 트랜잭션을 분리해야 할지 찾아보다가 `@Async`를 이용하여 트랜잭션을 분리하였습니다.

이로 인해 카카오톡 메시지 전송은 별도의 스레드에서 진행되고, 해당 메서드의 예외 여부나, 리턴 값이 트랜잭션에 아무 영향을 끼치지 않게 리팩터링 하였습니다.

2024-08-09 07:45 UTC, Hongdonggeon approved these changes
안녕하세요 수랑님
리뷰 반영해주셨네요!
6주동안 미션 진행하시느라 수고 많으셨습니다
앞으로도 화이팅입니다!

2024-08-09 07:45 UTC, merged