충남대 BE_박서현 6주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #384
Opened 2024-08-05 01:25 UTC by sseooh

2024-08-05 12:40 UTC, jjongwa requested changes
>상품 구매에 사용할 수 있는 포인트 기능을 구현한다.
포인트는 사용자별로 보유한다.
포인트 차감 방법 등 나머지 기능에 대해서는 팀과 논의하여 정책을 결정하고 구현한다.
e.g.
5만 원 이상 주문 시 총 금액의 10%가 할인된다.
현금 영수증을 받으려면 휴대전화 번호를 입력해야 한다.
API 명세는 팀과 협의하여 결정하고 구현한다.
관리자 화면에서 포인트를 충전할 수 있다.

포인트 차감 방법은 팀원들과 논의 후 결정했는지 (현재는 아예 없어 보이네요..!)
없다면 어떤 이유인지,

현재 구현한 기능이 정말 관리자 화면에서 포인트를 충전할 수 있는 것인지 (member로 로그인 되어 있으면 모두가 PointController의 api에 접근할 수 있을 것 같습니다.)
등등을 적어주세요.!

기한 안에 미션을 마치는 것도 중요하지만 가장 중요한건 **기능 요구 사항을 만족**하는 겁니다!
마지막까지 힘내 봅시다 🔥

2024-08-05 12:40 UTC, jjongwa commented on src/main/java/gift/service/PointService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당하는 회원이 존재하지 않습니다."));
중복되는 메서드는 분리해서 재사용 해볼까요?

2024-08-05 12:40 UTC, jjongwa commented on src/main/java/gift/service/PointService.java
> +    public int getPoint(Long memberId) {
조회에서 transaction이 필요한가요?

2024-08-06 00:16 UTC, sseooh commented
> > 상품 구매에 사용할 수 있는 포인트 기능을 구현한다.
> > 포인트는 사용자별로 보유한다.
> > 포인트 차감 방법 등 나머지 기능에 대해서는 팀과 논의하여 정책을 결정하고 구현한다.
> > e.g.
> > 5만 원 이상 주문 시 총 금액의 10%가 할인된다.
> > 현금 영수증을 받으려면 휴대전화 번호를 입력해야 한다.
> > API 명세는 팀과 협의하여 결정하고 구현한다.
> > 관리자 화면에서 포인트를 충전할 수 있다.
> 
> 포인트 차감 방법은 팀원들과 논의 후 결정했는지 (현재는 아예 없어 보이네요..!) 없다면 어떤 이유인지,
> 
> 현재 구현한 기능이 정말 관리자 화면에서 포인트를 충전할 수 있는 것인지 (member로 로그인 되어 있으면 모두가 PointController의 api에 접근할 수 있을 것 같습니다.) 등등을 적어주세요.!
> 
> 기한 안에 미션을 마치는 것도 중요하지만 가장 중요한건 **기능 요구 사항을 만족**하는 겁니다! 마지막까지 힘내 봅시다 🔥

https://www.notion.so/Day-30-7825aab2cd3d4b99945da0e97fd788a7 -> 포인트 차감 방법은 팀원들과 논의 후 결정했습니다!
포인트 충전은 관리자인지 확인 후 진행할 수 있도록 코드 수정했습니다..!

2024-08-06 00:29 UTC, closed without merging