전남대 BE_김보민 6주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #399
Opened 2024-08-05 15:12 UTC by KBM05haruin30

# 2단계
배포 셸 스크립트와 CORS 설정을 해주었습니다. 인텔리제이에 작성한 셸 스크립트를 aws 인스턴스에도 추가해 주었습니다. 배포 셸 스크립트를 잘 작성했는지 궁금합니다. 추가로 CORS 설정을 해주었는데 CORS 설정과 그에 관한 테스트 코드도 잘 작성했는지 봐주셨으면 합니다.

2024-08-05 15:25 UTC, Hongdonggeon requested changes
안녕하세요 보민님 
미션 잘 구현해주셨네요! 
cors 설정만 다시 확인해주세요

2024-08-05 15:25 UTC, Hongdonggeon commented on src/main/java/gift/config/WebConfig.java
> +            .allowCredentials(true);
api를 이렇게 따 분리해서 cors 설정을 한이유가 뭘까요?
아래와 같이 한번에 처리할 수 있지 않을까요?

```
     registry.addMapping("/api/**")
            .allowedOriginPatterns("*")
            .allowedMethods("GET", "POST", "PUT", "DELETE")
            .allowedHeaders("Content-Type", "Authorization")
            .exposedHeaders("Authorization", "Location")
            .maxAge(1800)
            .allowCredentials(true);
```

2024-08-05 15:32 UTC, KBM05haruin30 commented on src/main/java/gift/config/WebConfig.java
> +            .allowCredentials(true);
처음에 한꺼번에 처리하려고 멘토님께서 남겨주신 것처럼 작성을 했었습니다. `api/orders/` 같은 경우 `POST`만 필요하지만 한꺼번에 처리하게 되면 다른 메서드들도 허용될까봐 이렇게 따로 분리해서 작성했습니다. `api/wishes/`는 `GET, POST, DELETE`만 사용하고 `api/members/`는 `POST`만 사용하고 있어 이렇게 작성했습니다. 따로 분리해서 작성하지 않고 한번에 처리하게 코드를 수정해도 괜찮은지 궁금합니다.

2024-08-09 07:41 UTC, Hongdonggeon commented on src/main/java/gift/config/WebConfig.java
> +            .allowCredentials(true);
다른 http 메서드에 대해 사용하지 않더라도 cors 에 대한 설정을 미리해줘도 괜찮을 것 같아요! 한번에 설정으로 하는게 좋을 것 같아요

2024-08-09 07:55 UTC, Hongdonggeon commented on src/main/java/gift/config/WebConfig.java
> +            .allowCredentials(true);
api 별로 인가와 같은 설정을 다르게 해주어야하는 상황이라면 분리해서 설정하는게 좋겠지만, cors 설정은 api마다 다른게 아닌 이 어플리케이션의 공통적인 성격이니 한번에 하는게 좋은 것 같아요

2024-08-09 07:59 UTC, KBM05haruin30 commented on src/main/java/gift/config/WebConfig.java
> +            .allowCredentials(true);
넵 알겠습니다!

2024-08-13 07:26 UTC, Hongdonggeon approved these changes
보민님!
리뷰 반영하신거 확인했어요! 머지할게요!

2024-08-13 07:26 UTC, merged