경북대 BE_장우석 6주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #401
Opened 2024-08-05 16:29 UTC by us4c0d3

## 구현

* 저희 팀은 포인트가 적립금 개념이라고 생각하고 [이렇게](https://supreme-jewel-53e.notion.site/api-orders-bd9a986201f3473bbb9a23fdfad520c2?pvs=4) 명세를 정해 포인트 기능을 구현했습니다. 
  * 결제 과정에서 생기거나/필요로 하는 정보가 많아 PaymentInfo라는 DTO를 사용했습니다.

* 사용자 관리 페이지
  * 사용자 관리 페이지가 기존에 존재하지 않아 만들었습니다. 이 과정에서 로그인 시 반환하는 user response와는 별개의 데이터가 필요해 UserInfo를 모델로 사용했습니다.
  * 사용자 관리 페이지에서 포인트를 충전할 수 있도록 했습니다.
  * 문제점
    * 관리자 페이지에서 구현했던 카카오 로그인을 그대로 재활용하여 프론트에서 사용하도록 해 카카오 로그인시 토큰을 로컬스토리지에 저장한 상태로 메인 페이지로 리디렉션되는 것이 아닌 로그인 json을 반환합니다.
    * 카카오 로그인 시 토큰이 반환되는 json페이지의 url이 콜백 url에서 따로 추가작업을 하지 않아 인가 코드가 그대로 노출됩니다. 이 부분은 한 번 더 리디렉션을 하든가 프론트와 협의하여 response url을 변경할 필요가 있습니다.

2024-08-05 17:54 UTC, sang5c requested changes
웹 페이지에 접근할 수 있는 주소 알려주세요~

2024-08-05 18:17 UTC, us4c0d3 commented
http://13.124.136.144:8080/ 입니다!

2024-08-06 16:29 UTC, sang5c approved these changes
마지막으로 생각해볼만한 부분에 리뷰 남겼으니 확인해주세요!  
6주간 고생 많으셨습니다 :)  

이전 댓글은 프론트/백엔드가 연동된 페이지를 보고싶어서 접근 URL을  요청드리는 의도였습니다 ㅎㅎ

2024-08-06 16:29 UTC, sang5c commented on src/main/java/gift/order/service/OrderService.java
> +            discountedPrice = request.point();
if문 내에서 외부 값을 변경하면 코드가 길어질수록 추적이 어렵습니다.  
if (request.usePoint())인 경우 point가 무조건 0이 아닌걸로 보이는데, validation을 통해 point 값의 범위를 제어하면 if(request.usePoint()) { ... user.usePoint() } 형태의 코드를 제거할 수 있을 것 같아요.

2024-08-06 16:29 UTC, sang5c commented on src/main/java/gift/order/service/OrderService.java
> +        Order savedOrder = orderRepository.save(new Order(pay(user, option, request)));
`order`의 의미를 어떻게 정의하셨는지 모르지만, order가 선행되고 pay가 후행되어야 코드가 자연스럽게 읽힌다고 느낍니다.  
현재 코드상으로는 pay가 선행되네요. (주문하지 않았는데 지불함)

2024-08-06 16:29 UTC, sang5c commented on src/main/java/gift/user/entity/User.java
> +        if (this.point < point) {
👍

2024-08-06 16:29 UTC, sang5c commented on src/main/java/gift/user/entity/User.java
> +        this.point = 0;
저는 이런 경우엔 생성자에선 포인트를 파라미터로 받고 생성자를 private로 변경한 다음, 정적 팩토리 메서드로 createZeroPointUser(...) 형태 혹은 무조건 0포인트로 시작한다면 create(...) 형태로 메서드를 두는 방식을 선호합니다.  
따라하시라는 의견은 아니니 참고만 해주세요~

2024-08-06 16:29 UTC, merged