강원대 BE_오승규 6주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #405
Opened 2024-08-06 12:20 UTC by 5win

안녕하세요 제이님
6주차 마지막 과제 완료하여 PR드립니다!

6주간 부족한 코드에 리뷰해주시느라 고생 많으셨습니다!
덕분에 좋은 방향을 유지하며 배울 수 있었던 것 같습니다 :)

테스트 코드나 API 문서화와 같이 아직 부족하거나 구현하지 못한 부분도 있고 이런 부분에 대한 고민이 충분하지 못헀던 것 같아 아쉬운 마음이 있지만, 추후에 코드를 좀 리팩토링 해보는 과정과 함께 꼭 마무리 짓도록 하겠습니다! 
감사합니다!

2024-08-06 12:24 UTC, 5win commented on src/main/java/gift/entity/Order.java
> +        return sum / 100 * 5;
포인트 적립은 주문 금액의 5%를 적립하도록 했습니다.
만약 실제로 서비스를 해야한다면 소수점 부분에 대한 정책도 고려를 해야할 것 같다는 생각이드네요.

2024-08-08 14:45 UTC, jaymarystella requested changes
안녕하세요 좀 늦었네요.
마지막 단계까지 고생많으셨습니다.
간단한 피드백 남겼는데 확인부탁드릴게요~

2024-08-08 14:45 UTC, jaymarystella commented on src/main/java/gift/entity/Order.java
> +        return (int) (sum / 100.0 * 5);
신규 메서드에 대한 테스트코드도 같이 있어야겠네요!

2024-08-08 14:45 UTC, jaymarystella commented on src/main/java/gift/entity/Order.java
> +            .mapToLong(productOption -> productOption.getProduct().getPrice())
중첩된 get을 개선해볼까요?

2024-08-08 14:45 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +        addPoint(order);
point관련한 동작은 하나의 private method로 구분해볼수도있을거같아요. 참고만해주세요!

2024-08-08 14:45 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +        order.getMember().addPoint(point);
이 부분도 주문에서 멤버를 가져오지말고 point를 넘겨서 주문자체에서 해결할 수 있도록 해볼까요?

2024-08-08 14:47 UTC, jaymarystella commented on src/main/java/gift/entity/Order.java
> +        return sum / 100 * 5;
적립은 말씀주신대로 말그대로 정책이기때문에 정하시면 될거같아요! (제가 포인트 적립 정책이 일반화된게 있는지는 모르겠지만.. 버림처리를 해도 될거같긴하네요)

2024-08-12 13:22 UTC, 5win commented on src/main/java/gift/entity/Order.java
> +            .mapToLong(productOption -> productOption.getProduct().getPrice())
상품 객체는 얻어야하기 때문에 두 번의 get을 사용하는건 불가피할 것 같다고 생각이 됩니다.
그래도 가독성적인 측면에서 두 get 호출을 나눠서 처리하도록 변경해보았습니다!

2024-08-12 13:25 UTC, 5win commented on src/main/java/gift/service/OrderService.java
> +        order.getMember().addPoint(point);
포인트 추가라는 책임을 주문을 통해 멤버에게 전달되도록 하는 관점은 생각하지 못했네요.
getter를 줄이는 부분과 응집성적인 측면에서 주문 자체에서 해결하는 것이 더 좋을 것 같단 생각이 드네요 감사합니다 :)

2024-08-15 14:12 UTC, jaymarystella approved these changes
마지막까지 고생많으셨습니다.
앞으로 미션도 화이팅 하시길 바랍니다.

2024-08-15 14:12 UTC, merged

2024-09-27 05:44 UTC, 5win commented
@jaymarystella 
안녕하세요 제이님!
혹시 이 경로로 연락이 닿을지 모르겠네요
이번 하반기 준비하며 이력서와 포트폴리오를 작성해서 첨삭 도움을 받고자 했는데
슬랙 연락 경로가 사라져서 부득이하게 이렇게라도 언급드려봅니다..!