강원대 BE_안승환 6주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #408
Opened 2024-08-07 18:46 UTC by Awhn

- 회원 테이블에 포인트 칼럼을 추가하고, 주문을 수행할 때 50000원이 넘는 경우 거래액의 10%를 포인트로 적립하는 기능을 추가하였습니다.
- 이에 더해서 스트림 API를 연습하기 위해 위시리스트에서 가장 빈번한 카테고리를 찾고, 해당 카테고리의 상품을 추천하는 기능을 추가하였습니다.

지난 6주간 피드백 주신 점 진심으로 감사드립니다. 코드나 피드백 반영에 부족한 점이 많았기에 죄송한 마음이 있지만, 멘토님 덕분에 끝까지 따라올 수 있었던 거 같습니다. 앞으로도 그동안 말씀해주신 내용들을 계속 되새기며 좋은 개발자가 될 수 있도록 노력하겠습니다.

2024-08-08 14:59 UTC, jaymarystella requested changes
안녕하세요 
마지막 미션까지 고생많으셨습니다.
간단한 코멘트 몇가지만 남겨두었습니다!

2024-08-08 14:59 UTC, jaymarystella commented on src/main/java/gift/controller/WishlistController.java
> +        return ResponseEntity.ok().body(body);
컨트롤러에 로직은 지양하는것이 좋습니다. 서비스안에서 해결하고 결과를 모아서 리턴하는방식으로 개선이 가능할까요? 
(+ 테스트하시기도 더 용이할거에요!)

2024-08-08 14:59 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +        return 0;
서비스로직으로 전개가 되어있군요, 주문 엔티티에서 판단하도록 구조 개선이 가능할까요?

2024-08-09 19:49 UTC, Awhn commented on src/main/java/gift/controller/WishlistController.java
> +        return ResponseEntity.ok().body(body);
넵, wishlist 서비스 안에서 처리하도록 변경하였습니다. 테스트 코드가 하나로 줄어 훨씬 가독성이 좋은 거 같습니다.

2024-08-09 19:50 UTC, Awhn commented on src/main/java/gift/service/OrderService.java
> +        return 0;
넵, 이전에는 주문 엔티티에 product가 포함되지 않아 가격 정보를 획득할 수 없었는데, 주문 엔티티에서 product id를 외래키로 갖게 하여 주문 엔티티 내에서 가격 정보를 확인하고 포인트 계산을 처리할 수 있도록 변경하였습니다.

2024-08-11 12:13 UTC, jaymarystella approved these changes
그동안 고생많으셨습니다.
다음 미션들도 화이팅입니다!

2024-08-11 12:13 UTC, merged