강원대 BE_김병수 6주차 과제 (step3)
kakao-tech-campus-2nd-step2/spring-gift-point pull request #410
Opened 2024-08-09 20:02 UTC by GamJaDo

팀 내에서 정한 포인트 정책을 추가하였습니다.

2024-08-11 07:35 UTC, jaymarystella requested changes
안녕하세요 마지막 단계까지 고생많으셨어요.
몇가지 코멘트 남겨두었는데 확인 후 반영부탁드릴게요~

2024-08-11 07:35 UTC, jaymarystella commented on src/main/java/gift/dto/OrderRequest.java
> +    }
dto가 해당 로직을 가지고있는것이 어색해보입니다. 역할을 다른쪽에 부여하면 어떨까요?

2024-08-11 07:35 UTC, jaymarystella commented on src/main/java/gift/entity/User.java
> +	    }
👍🏼

2024-08-11 07:35 UTC, jaymarystella commented on src/main/java/gift/entity/User.java
> +	    setPoints(newPoints);
set을 하기전에 검사를 함으로써 안정성을 높여보면 어떨까요? (+테스트코드)

2024-08-11 07:35 UTC, jaymarystella commented on src/main/java/gift/service/OrderService.java
> +        return pointService.deductPoints(user.getId(), totalPrice);
포인트가 유효한지의 판단로직이 서비스내에 파편화되어있는데요, 도메인안에서 판단할 수 있을지 고민해보시면 좋을것같아요. 이부분은 반영보다는 고려만 해주셔도 좋습니다.

2024-08-11 07:35 UTC, jaymarystella commented on src/main/java/gift/service/PointService.java
> +public class PointService {
작성한 기능에 대해서는 테스트코드를 만들어주세요!

2024-08-12 18:40 UTC, GamJaDo commented on src/main/java/gift/dto/OrderRequest.java
> +    }
해당 역할을 OrderService로 부여하였습니다.

2024-08-12 18:41 UTC, GamJaDo commented on src/main/java/gift/entity/User.java
> +	    setPoints(newPoints);
set을 하기전 검사를 하도록 변경하였습니다.
테스트는 PointServiceTest의 `testDeductPoints` 메서드에서 실시 하였습니다.

2024-08-12 18:42 UTC, GamJaDo commented on src/main/java/gift/service/OrderService.java
> +        return pointService.deductPoints(user.getId(), totalPrice);
`processPayment` 메서드를 도메인으로 빼는게 적절할것 같습니다.

2024-08-12 18:43 UTC, GamJaDo commented on src/main/java/gift/service/PointService.java
> +public class PointService {
`PointServiceTest`를 작성하였습니다.

2024-08-15 14:12 UTC, jaymarystella approved these changes
피드백 반영하느라 고생많으셨습니다.
앞으로 미션들도 화이팅하시길 바랍니다.

2024-08-15 14:13 UTC, merged